### ISSUE TITLE
what file?

### ISSUE THREAD

**Issue by Feqg** [barryvdh/laravel-snappy#1]
what is the file to add this: 'binary' => base_path('vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64'), And its route, thank you

**Comment by Hesesses** [comment]
I'm getting this error:

vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64: error while loading shared libraries: libXrender.so.1: cannot open shared object file: No such file or directory

Any ideas how to fix this?

**Comment by silverdr** [comment]
By installing libXrender? There is a sentence about it at the beginning of README.md…

**Comment by chikitovivas** [comment]
how to set up the bootstrap grip, for this pdf generator?

**Comment by majidkamal-vbase** [comment]
where to add this line    'binary' => base_path('vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64').   and also i am unable to run this command  php artisan config:publish barryvdh/laravel-snappy.

**Comment by cheanj** [comment]
Hi I tried using this barryvdh/laravel-snappy

I followed the installation instruction.. 

but when I tried to use the wrapper 
$pdf = App::make('snappy.pdf.wrapper');
$pdf->loadHTML('<h1>Test</h1>');
return $pdf->inline();

it will say Class 'App\Http\Controllers\App' not found

It would be a great help for any response

**Comment by brudascacosmin** [comment]
Hi, 
I just installed laravel-snappy, and try to follow example from readme:
$pdf = App::make('snappy.pdf.wrapper');
			$pdf->loadView('invoice.show', [ $data ]);
			return $pdf->download('invoice.pdf');
But i see the fallowing error in log: Invalid request (Unexpected EOF)
If I use loadHtml  function it work fine. 
Any ideas how to figure out what it is happening here?
