### ISSUE TITLE
Windows server 2012, IIS, exit status code '1'

### ISSUE THREAD

**Issue by j4r3kb** [barryvdh/laravel-snappy#100]
Hello,
I'm running Windows Server 2012 R2 + IIS + Symfony2.
Wkhtmltopdf 0.12.3.2 64 bit.
Path written as: "\"E:\wkhtmltopdf\bin\wkhtmltopdf.exe\"";
IUSR (IIS server user) has all permissions on Windows\Temp.
It does not matter if Temp is used or I set:
temporary_folder: %kernel.cache_dir%/snappy #(with all permissions of course)

I always get:
The exit status code '1' says something went wrong:
stderr: ""
stdout: ""
command: "E:\wkhtmltopdf\bin\wkhtmltopdf.exe" --lowquality --footer-font-name "Verdana" --footer-font-size "9" --footer-left ...(and so on)"

Only solution is as posted in this thread https://github.com/barryvdh/laravel-snappy/issues/31 - modify the AbstractGenerator generate():
`exec($command);`

Any other workarounds for this or a possibility for a patch in AbstractGenerator?

As a side note: I wrote a class for Symfony2 for running the process of Libreoffice (headless) and got the same problem - on Windows Server + IIS the "new Process()" just does not work. Ended up with:
`
if (PHP_OS === 'Linux') {
  $process = new Process($command);
...
} elseif (PHP_OS === 'WINNT') {
  exec($command);
}
`

**Comment by nzphoenix** [comment]
Hi @j4r3kb did you end up finding a solution to this? I'm experiencing the same thing. No matter which path is being used to write to and the permissions on that folder, the symfony process command fails.

**Comment by j4r3kb** [comment]
No other that I posted in my first message.

**Comment by hectorh30** [comment]
#46 might be helpful, but it didn't make the trick for me
