### ISSUE TITLE
Problem With Encoding

### ISSUE THREAD

**Issue by ibrahimirsyad** [barryvdh/laravel-snappy#102]
can some one help me, i got this problem :
i have been googling many times, but no one can resolve this problem.
such us encoding utf-8, reinstalling wkhtml. etc
![untitled](https://cloud.githubusercontent.com/assets/10241107/13766648/5efcff8c-ea96-11e5-8acd-99e50d5c05fa.png)
note my config : 
- CENTOS 6.5 (64 bit)
- PHP
- MYSQL
- Laravel 4.2

Thx you very much for helping

**Comment by adumskis** [comment]
Adding meta to head helped me:

<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

**Comment by gihandilanka-github** [comment]
> <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

I added this, working fine in local machine, but not working in linux server, appeared black colour square boxes instead of Unicode texts.

**Comment by satputekuldip** [comment]
> > 
> 
> I added this, working fine in local machine, but not working in linux server, appeared black colour square boxes instead of Unicode texts.

Have You solve this
