### ISSUE TITLE
Image is not processed while creating PDF

### ISSUE THREAD

**Issue by Nextt1** [barryvdh/laravel-snappy#105]
The exit status code '1' says something went wrong:
stderr: "Loading pages (1/6)
[> ] 0%
[======> ] 10%
[=======> ] 12%
[===============> ] 25%
Warning: Failed to load file:///doctors/eKdlroQwpv/diagnosis/DGS-2/10/2016-03-30_04-44-05_program-hd-wallpapers-798x350 - Copy - Copy.jpg (ignore)
[=================================================> ] 82%
[=====================================================> ] 89%
[============================================================] 100%
Counting pages (2/6) 
[============================================================] Object 1 of 1
Resolving links (4/6) 
[============================================================] Object 1 of 1
Loading headers and footers (5/6) 
Printing pages (6/6)
[> ] Preparing
[============================================================] Page 1 of 1
Done 
Exit with code 1 due to network error: ContentNotFoundError
"
stdout: ""
command: /home/vagrant/Code/prectice/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64 --lowquality '/tmp/knp_snappy56fb67388f1c20.58266027.html' '/tmp/knp_snappy56fb67388f2279.15513327.pdf'.

Whenever I use `img` tag It is showing me this error. If I comment my `img` tag PDF will be generated as desired. My images are stored in `storage` directory and I am using 		
	`$pdf = \PDF::loadView('print.temp1', $data);`

Now, Since `loadView` is calling `render` method internally So It should work. What am I missing ?

**Comment by apstyx** [comment]
In mycase the issues was related to js and css files using relative paths. Please see the issue at  [ContentNotFoundError on pdf generation](https://github.com/KnpLabs/snappy/issues/177)

**Comment by khaldounnd** [comment]
@Nextt1 how did you end up fixing it? All the solutions use the public directory and I don't want to expose the images to the public since they contain sensitive information
