### ISSUE TITLE
thead and tbody contents overlap from second page onwards

### ISSUE THREAD

**Issue by amritshrestha** [barryvdh/laravel-snappy#106]
I have got thead which is supposed to be repeated to each page. It is working correctly in first page, but from second page onwards contents from tbody is overlaping thead.
I used wkhtmltopdf options --margin-top, --header-spacing, but those options only push the content (thead & tbody) downwards creating black space on top of the page.

Anybody have solution to this problem. Any help would be appreciated.
Thanks in advance.

**Comment by amritshrestha** [comment]
**found the solution: ** this worked for me
thead{display: table-header-group;}
tfoot {display: table-row-group;}
 {page-break-inside: avoid;}

**Comment by JapSeyz** [comment]
Thanks!

**Comment by InstanceOfMichael** [comment]
this worked for me:
```
        thead {
            display: table-header-group;
        }
        tfoot {
            display: table-row-group;
        }
        tr {
            page-break-inside: avoid;
        }
```

**Comment by kojilab** [comment]
I keep trying that solution and it doesn't work for me. I'm on Ubuntu

**Comment by amritshrestha** [comment]
Encountered weird situation few days earlier. If you have underscore in your domain or subdomain, the footer don't render properly. Replaced underscore with dash and the footer was rendering properly. Be weary of that.

**Comment by zurez** [comment]
@InstanceOfMichael : Thanks. Your solution worked for me.

**Comment by nasirkhan** [comment]
I put my table info a DIV which has a class `export-table` and added the following CSS and it resolved the issue. 

```
@media print {
    .export-table {
        overflow: visible !important;
    }
}
```

**Comment by MartinThoma** [comment]
Version 0.12.2.2 did not repeat the table headers. 0.12.4 does.

**Comment by usmanr149** [comment]
Thanks!

**Comment by Aphinith** [comment]
Adding this worked for me:
```
table thead {
    display: table-row-group;
  }
```

**Comment by damonbakker** [comment]
I would like to add to this, if you're using bootstrap tables. Having a wrapper around your table using the class  "table-responsive" breaks the whole `page-break-inside: avoid;`

**Comment by mohamed199320** [comment]
I have the same problem and it doesn't work i tried everything .
anyone can help ??
Thanks

```
  <template id="new_facture">
      <t t-call="report.html_container">
          <t t-call="facture_layout.facture_layout">
          <div class="page">
            <!-- Report page content -->
            <style>
					       tbody {font-size: 10px;}
	               .police {font-size: 10px;}
                 thead{display: table-header-group;}
                 tfoot {display: table-row-group;}
                 tr {page-break-inside: avoid;}
            </style>

            <t t-foreach="docs" t-as="o">
                  
                  <table class="table table-condensed table-bordered table-responsive">
                        	<thead>
                                    <tr style="background-color:#A9E2F3;">
                                        <th>Description</th>
                                        <th class="hidden">Source Document</th>
                                        <th class="text-right">P.U</th>
                                        <th class="text-right">PPA</th>
                                        <th class="text-right">PPH</th>
                                        <th class="text-right">Qté</th>
                                        <th class="text-center">UM</th>
                                        <th class="text-center">Mnt Brut</th>
                                        <th class="text-right">RM(%)</th>
                                        <th class="text-right">Montant HT</th>
                                    </tr>
                                </thead>
                       
                                <tbody>
                                    <tr t-foreach="o.invoice_line_ids" t-as="l">
                                        <tr>
                                        	<td>
                                        
                                            <span t-field="l.name"/>

                                                <t t-if="(l.lot_formatted_note is not False)">
                                                <div style="margin-left:25px;" t-field="l.lot_formatted_note" />
                                                </t>



                                            
                                        </td>
                                        
                                        <td class="hidden"><span t-field="l.origin"/></td>
                                        <td class="text-right">
                                            <span t-field="l.price_unit"/>
                                        </td>
                                        <td class="text-right">
                                            <span t-field="l.ppa"/>
                                        </td>

                                        <td class="text-right">
                                            <span t-field="l.prix_pharmacien"/>
                                        </td>

                                        <td class="text-right">
                                            <span t-esc="'%.0f'%(l.quantity)"/>
                                        </td>

                                        <td class="text-center">
                                            <span t-field="l.uom_id" groups="product.group_uom"/>
                                        </td>

                                        <td class="text-right">
                                            <span t-field="l.price_subtotal_brut"/>
                                        </td>

                                        <td class="text-right">
                                            <span t-field="l.discount"/>
                                        </td>

                                        <td class="text-right">
                                            <span t-field="l.price_subtotal" t-options="{&quot;widget&quot;: &quot;monetary&quot;, &quot;display_currency&quot;: o.currency_id}"/>
                                        </td>

                                        </tr>
                                    </tr>
                                 </tbody>
                            </table>
              </t>
            </div>
</t>
</t>
</template>
```




            </style>

            <t t-foreach="docs" t-as="o">






  
<div class="export-table">
  <table class="table table-condensed table-bordered table-responsive">
        	<thead>
                    <tr style="background-color:#A9E2F3;">
                        <th>Description</th>
                        <th class="hidden">Source Document</th>
                        <th class="text-right">P.U</th>
                        <th class="text-right">PPA</th>
                        <th class="text-right">PPH</th>
                        <th class="text-right">Qté</th>
                        <th class="text-center">UM</th>
                        <th class="text-center">Mnt Brut</th>
                        <th class="text-right">RM(%)</th>
                        <th class="text-right">Montant HT</th>
                    </tr>
                </thead>
       
                <tbody>
                    <tr t-foreach="o.invoice_line_ids" t-as="l">
                        <tr>
                        	<td>
                        
                            <span t-field="l.name"/>

                                <t t-if="(l.lot_formatted_note is not False)">
                                <div style="margin-left:25px;" t-field="l.lot_formatted_note" />
                                </t>



                            
                        </td>
                        
                        <td class="hidden"><span t-field="l.origin"/></td>
                        <td class="text-right">
                            <span t-field="l.price_unit"/>
                        </td>
                        <td class="text-right">
                            <span t-field="l.ppa"/>
                        </td>

                        <td class="text-right">
                            <span t-field="l.prix_pharmacien"/>
                        </td>

                        <td class="text-right">
                            <span t-esc="'%.0f'%(l.quantity)"/>
                        </td>

                        <td class="text-center">
                            <span t-field="l.uom_id" groups="product.group_uom"/>
                        </td>

                        <td class="text-right">
                            <span t-field="l.price_subtotal_brut"/>
                        </td>

                        <td class="text-right">
                            <span t-field="l.discount"/>
                        </td>

                        <td class="text-right">
                            <span t-field="l.price_subtotal" t-options="{&quot;widget&quot;: &quot;monetary&quot;, &quot;display_currency&quot;: o.currency_id}"/>
                        </td>

                        </tr>
                    </tr>
                 </tbody>
            </table>
</div>

**Comment by mohamed199320** [comment]
am using odoo 10 Ubuntu 16 & 18 wkhtmltopdf 1.2.1 & 1.2.4

**Comment by dennismunene** [comment]
> Adding this worked for me:
> 
> ```
> table thead {
>     display: table-row-group;
>   }
> ```

This worked for me as well

**Comment by MartinP7r** [comment]
@mohamed199320 try `thead{display: table-row-group;}`

**Comment by rayalois22** [comment]
You are also likely to encounter this problem if you explicitly set `height` on a thead element to a non-relative value like pixels.
