### ISSUE TITLE
Method setOption() removes HTML symbol on Linux

### ISSUE THREAD

**Issue by fschmtt** [barryvdh/laravel-snappy#111]
When I use 

`->setOption('footer-left', '© 2016 Company')`

it will output me 

`2016 Company`

but when I use wkhtmltopdf from the command line like this

`wkhtmltopdf http://google.com --footer-left "©" google.pdf`

the output is correct.

**EDIT:**

`->getCommand()` returns
`/usr/bin/wkhtmltopdf [...] --footer-left ' 2016 XXX' [...] 'http://google.com' 'google.pdf'`

**Comment by FiloSpaTeam** [comment]
I'm using Heroku platform for testing and production environments and (C) is removed.
In our local machines (Fedora 25) it works but the same code is deployed
