### ISSUE TITLE
Unable to call the Snappy from within the Controller

### ISSUE THREAD

**Issue by AshishGupta001** [barryvdh/laravel-snappy#112]
Hi,
I have installed Laravel-Snappy (L5.1) and have done necessary configuration. I am able to call and create a PDF file from directly invoking a anonymous function within the route.php. But when I place the same code within a controller, nothing happens. Neither any PDF file is generated nor any error is thrown.

Appreciate some help in getting the issue resolved.
## **Sample Code**

**routes.php**

```
// This one below works just fine
Route::get('printPDF', function(){
        $text = "<p align='center'><h3>Hi Bill</h3></p><br><p>You owe me money dude</p>";
        $pdf = PDF::loadHTML($text);
        $pdf->save('/tmp/invoice.pdf', true);
});

// This one below does not work. Instead being returned to home page. Even the debug statements and **debugdump** does not help
Route::get('printPDF1', PDFController@printPDF);
```

**PDFController**

```
public function printPDF() { 
    $text = "<p align='center'><h3>Hi Bill</h3></p><br><p>You owe me money dude</p>";
        $pdf = PDF::loadHTML($text);
    $pdf->save('/tmp/invoice.pdf', true);
}
```

**Comment by chopf** [comment]
`routes.php` does not have a namespace defined, so when you try to use the `PDF` facade, you are already in the needed global namespace.

Your `PDFController` is *probably* namespaced to something like `App\Http\Controllers`. To use a facade in this context you must simply call it like `\PDF::loadHtml($text);`

**Comment by Tebogo-Seshibe-Retro** [comment]
@AshishGupta001 How did you call the anon function from within your view?
