### ISSUE TITLE
Exit with code 1 due to network error: HostNotFoundError

### ISSUE THREAD

**Issue by leandrovergara** [barryvdh/laravel-snappy#120]
Hi,

I'm making a Software on Laravel 5.2 in Vagrant Homestead Enviroment.

I'm having an issue with using Laravel Snappy when i don't have any ehternet connection on host machine (WiFi is off).

When I'm without internet connection in host machine , the generation of any PDF to download dumps this error:

```
RuntimeException in AbstractGenerator.php line 336:
The exit status code '1' says something went wrong:
stderr: "Loading pages (1/6)
[> ] 0%
[======> ] 10%
[======> ] 11%
[==========> ] 18%
[===============> ] 25%
[================> ] 28%
[==================> ] 30%
[====================> ] 34%
[======================> ] 37%
[========================> ] 40%
[=========================> ] 43%
[===========================> ] 46%
[============================> ] 48%
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
[==================================================> ] 84%
[============================================================] 100%
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
Counting pages (2/6) 
[============================================================] Object 1 of 1
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
Resolving links (4/6)
[============================================================] Object 1 of 1
Loading headers and footers (5/6) 
Printing pages (6/6)
[> ] Preparing
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
[============================================================] Page 1 of 1
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
Done 
Exit with code 1 due to network error: HostNotFoundError
"
stdout: ""
command: /home/vagrant/Proyectos/Cognitio/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64 --lowquality --orientation 'landscape' --page-size 'a4' '/tmp/knp_snappy579f60541a7b69.41947737.html' '/tmp/knp_snappy579f60541a8891.45175495.pdf'.
```

I tried to execute directly the command from bash on Vagrant having the same results.

```
/home/vagrant/Proyectos/Cognitio/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64 --lowquality --orientation 'landscape' --page-size 'a4' 'http://192.168.10.10:80/reportesPrestamosXFechaXTipo/T/1900-01-01/2999-12-31/PANTALLA' '/tmp/knp_snappy579f42ef0cec48.01067573.pdf'

Loading pages (1/6)
Counting pages (2/6)
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
Exit with code 1 due to network error: HostNotFoundError
```

It's any solution with this issue?

**Comment by arasmit2453** [comment]
Are you loading any images or external assets?.

This error is because snappy is trying to load an external image or asset

**Comment by sharfaz** [comment]
I had same problem and spend number of days to find out what causing the issue. When you using snappy in Vagrant environment it looks for virtual host (in most cases you have one to access VM) to load the local assets if you have any in pdf. In most cases we do have VH in our hosts config file in Host machine but not in VM itself.

So edit your VM (homestead) host file.

/etc/hosts
127.0.0.1 #add your virtual host

This resolved my problem.
I have Bootstrap and local css assets in my pdf header and after changing host file everything worked!!!

**Comment by tobysommer** [comment]
[L5.4] I also had the same problem using `<link rel="stylesheet" href="{{ mix('css/pdf.css') }}">`. I fixed it using `<link rel="stylesheet" href="{{ url('/').mix('css/pdf.css') }}">` to get a full path to the linked CSS file. Works well so far.

**Comment by namtenten** [comment]
@sharfaz 
Thank you. It worked in my case.
> So edit your VM (homestead) host file.
> 
> /etc/hosts
> 127.0.0.1 #add your virtual host

My dev environment is CentOS 7.
Somehow, I think snappy should ignore this issue by default. Because when developer checks in PDF file, he/she will know what is incorrect, then he/she can fix at that point (easy seeing result by PDF) more than see this common error and do not know where the problems in HTML file.
