### ISSUE TITLE
The exit status code '134' says something went wrong stderr: "QXcbConnection: Could not connect to display Abosrted"

### ISSUE THREAD

**Issue by ehobeika1994** [barryvdh/laravel-snappy#122]
I am getting this error. Anyone has a solution to it as I tried so many places for solutions and no one has one. I have been trying for 2 days now and nothing. 

Please help 

Full error: 

RuntimeException in AbstractGenerator.php line 336:
The exit status code '134' says something went wrong:
stderr: "QXcbConnection: Could not connect to display 
Aborted
"
stdout: ""
command: /usr/local/bin/wkhtmltopdf --lowquality '/tmp/knp_snappy57a1e734659907.44841494.html' '/tmp/knp_snappy57a1e73465a2e7.61452492.pdf'.

**Comment by webcrazy** [comment]
Yeah me too. I get the same error. I tried looking for that issue and found that this is a bug from wkhtmltopdf.

```
[2016-08-04 15:28:04] local.ERROR: RuntimeException: The exit status code '134' says something went wrong:
stderr: "QXcbConnection: Could not connect to display 
Aborted (core dumped)
```

But if I run from command line, it's working fine but from supervisor queue.

**Comment by webcrazy** [comment]
@ehobeika1994 you may want to take a look at this.

https://github.com/KnpLabs/KnpSnappyBundle/issues/116

We may have faced the same issue. not sure though.

**Comment by barryvdh** [comment]
First try if wkhtmltopdf is working at all in your install: `wkhtmltopdf google.com google.pdf`

Otherwise try to fix that first, this is just a wrapper.
See also https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2037 and http://unix.stackexchange.com/questions/192642/wkhtmltopdf-qxcbconnection-could-not-connect-to-display as I said on Twitter.
You could also try one of the binaries from the composer package (see readme), which can be newer then yum/apt-get etc.

**Comment by webcrazy** [comment]
@barryvdh Thanks for reply

First try if wkhtmltopdf is working at all in your install: /usr/local/bin/wkhtmltopdf google.com google.pdf
That is working fine.

Now I'm trying from this h4cc/wkhtmltopdf-amd64 package. Your link is also great.

**Comment by webcrazy** [comment]
For me, It is ok by installing h4cc/wkhtmltopdf-amd64 package and 
sudo apt-get update && sudo apt-get upgrade because I had outdated packages.

Thanks a lot @barryvdh

**Comment by Airmovz** [comment]
Hello @barryvdh 

We have wkhtmltopdf (version 0.12.2.4) installed in our server (Ubuntu). When we update our server from 14.04 to 16.04.1 LTS wkhtmltopdf is not working anymore. We keep getting this error : 
```QXcbConnection: Could not connect to display
Aborted (core dumped)```.

Is it an issue of compatibility of my wkhtmltopdf on 16.04?

**Comment by barryvdh** [comment]
No idea, please create an issue in the wkhtmltopdf repo

**Comment by dustinalan** [comment]
@Airmovz see posted work-arounds:
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2037#issuecomment-62019521

**Comment by larsbadke** [comment]
There is a more easy way to make John WH Smith solution.

Just install xvfb from apt and then, you can run:

xvfb-run wkhtmltopdf
(just put xvfb-run before any wkhtmltopdf command.)

https://unix.stackexchange.com/questions/192642/wkhtmltopdf-qxcbconnection-could-not-connect-to-display

Then chnage your snappy config

```
'pdf' => array(
        'enabled' => true,
        'binary'  => 'xvfb-run /usr/local/bin/wkhtmltopdf',
        'timeout' => false,
        'options' => array(),
        'env'     => array(),
    ),
```

That worked for me

**Comment by mashcom** [comment]
larsbadke solution worked like a charm. Thanks a lot that saved me a lot of time

**Comment by rwinzhang** [comment]
Another solution is to upgrade `wkhtmltopdf` to version 1.12.5 (latest) with this guide https://gist.github.com/srmds/2507aa3bcdb464085413c650fe42e31d

**Comment by heidy-miguel** [comment]
> There is a more easy way to make John WH Smith solution.
> 
> Just install xvfb from apt and then, you can run:
> 
> xvfb-run wkhtmltopdf
> (just put xvfb-run before any wkhtmltopdf command.)
> 
> (see - https://unix.stackexchange.com/questions/192642/wkhtmltopdf-qxcbconnection-could-not-connect-to-display)
> 
> Then change your snappy config (app/config/snappy.php) to
> 
> ```
> 'pdf' => array(
>         'enabled' => true,
>         'binary'  => 'xvfb-run /usr/local/bin/wkhtmltopdf',
>         'timeout' => false,
>         'options' => array(),
>         'env'     => array(),
>     ),
> ```
> 
> That worked for me

After trying a lot of things to solve, this worked for me.

**Comment by AsyncWizard** [comment]
It's quite weird because I had exactly the same problem in a docker container.
On the other hand, I found an archive containing working binaries: https://github.com/frappe/wkhtmltopdf/blob/master/wkhtmltox-0.12.3_linux-generic-amd64.tar.xz

The versions are roughly the same:
 - Problem version: v0.12.3.2
 - Ok version: v0.12.3 (with patched qt)

If it ever helps someone stuck on a 0.12 version...
