### ISSUE TITLE
Add method setTemporaryFolder()

### ISSUE THREAD

**Issue by molbi** [barryvdh/laravel-snappy#123]
Hi, first of all, thank you for your package. Everything working fine, but i had some problem with saving PDF on production server, because server has permission on writing to /tmp directory. For that reason snappy has method setTemporaryFolder, but not your package. 

it will by good add temporary_folder_path to config file, and set temporary folder for ImageWrapper and PdfWrapper depend on config file.

In my case i had to make own service provider what extend your service provider and my own PdfWrapper class, where i added setter and getter for temporary folder.

**Comment by rollercontainer** [comment]
I also need this option.

**Comment by molbi** [comment]
Hi,

this is possible to set.. in first time, when i have this problem, I make my version of PdfWrapper, service provider and add necessary methods, but in other project, i had a problem with saving cache in /tmp folder (no space left :-D)...and was necessary change path to temporary folder...

solution without changing anything in package, or making own class:

$wrapper = app('snappy.pdf.wrapper');
$wrapper->setTemporaryFolder(storage_path('snappy'));

$wrapper->loadView('pdf.invoice', compact('invoice', 'print'))->download(sprintf('%s.pdf',$invoice->number));

I hope it helps you.

**Comment by rollercontainer** [comment]
I digged around further and found the env Array for setting the path:

    'pdf' => array(
        'enabled' => true,
        'binary'  => '/usr/bin/wkhtmltopdf',
        'timeout' => false,
        'options' => [ 'page-size' => 'A4' ],
        'env'     => [ 'setTemporaryFolder' => '/path/to/temp'],
    ),

**Comment by molbi** [comment]
Hi, thx, good to know ;) For my case, i have to set temporary folder by my way, because I need in some cases different folder.

But if you dont need this, your solution is the best ;)

**Comment by rollercontainer** [comment]
It doesn't work, so I deleted it. What I can do is this:

    $pdf = App::make('snappy.pdf');
    $pdf->setTemporaryFolder("/var/xyz/temp");

But this does not use the barryvdh/laravel-snappy wrapper, correct?

**Comment by molbi** [comment]
You should try call this

`get_class($pdf)`

it return namespace of class, what DI container give you. 
But may be will be better use `App::make('snappy.pdf.wrapper')`, because here you can set temporary folder.

```
    public function __call($name, array $arguments)
    {
        $method = 'load' . ucfirst($name);
        if (method_exists($this, $method))
        {
            return call_user_func_array(array($this, $method), $arguments);
        }
        
        return call_user_func_array (array($this->snappy, $name), $arguments);
    }
```


this method call $this->snappy, if method missing in this class and in $this->snappy is object, which contains setTeporaryFolder method.

**Comment by rollercontainer** [comment]
get_class($pdf) returned 
Barryvdh\Snappy\IlluminateSnappyPdf

I do not understand your code. My approach above is working, so whats wrong with that?

**Comment by molbi** [comment]
The code i posted, is from LaravelSnappy class (just prove, how it is call right method).

And yes your code working too :) and `get_class($pdf)` prove to you, that it uses laravel-snappy package ;) 

I just use only different part of larave-snappy ;)
