### ISSUE TITLE
The exit status code '2'

### ISSUE THREAD

**Issue by atefBB** [barryvdh/laravel-snappy#124]
Hey !
I got this err:
`The exit status code '2' says something went wrong: stderr: "/home/atef/public_html/seomara/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64: 2: /home/atef/public_html/seomara/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64: Syntax error: Unterminated quoted string " stdout: "" command: /home/atef/public_html/seomara/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64 --lowquality --margin-bottom '0' --orientation 'landscape' --page-size 'a4' '/tmp/knp_snappy57aeef435c6397.94651265.html' 'myfile.pdf'.`
My test code is :
`return PDF::loadHTML('<h1>Test</h1>')
                ->setPaper('a4')
                ->setOrientation('landscape')
                ->setOption('margin-bottom', 0)
                ->save('myfile.pdf');`
any ideas?

**Comment by Holisollogistics** [comment]
m getting same error any expert here ???

**Comment by atefBB** [comment]
I abandon it! try to use https://github.com/dompdf/dompdf.
