### ISSUE TITLE
The process has been signaled with signal "11".

### ISSUE THREAD

**Issue by adnanmokhtar** [barryvdh/laravel-snappy#127]
i have shared hosting on godaddy. i have issue when i use wkhtmltopdf.

i have this message:
The process has been signaled with signal "11".

any help?

**Comment by rasheed436** [comment]
have you found the solution "The process has been signaled with signal "11"."

**Comment by rasheed436** [comment]
with wkhtmltopdf

**Comment by adnanmokhtar** [comment]
Not yet

**Comment by rasheed436** [comment]
it means there is no use of laravel-snappy except in offline? Is there any solution to create the snapshot of a website other than laravel-snappy?

**Comment by KevAtKloc** [comment]
I've got the same issue.
Binaries have been given 777 (full access) and also created a tmp folder in the bin directory and given that 777.
I get this error:

RuntimeException in Process.php line 380:
The process has been signaled with signal "11".

Any ideas?

**Comment by maxdmo** [comment]
Any solution to this issue? Thx.

**Comment by akulubala** [comment]
still stucking here

**Comment by ralphdegoma** [comment]
im still stuck in here pls help

**Comment by AdrianKielbasa** [comment]
+1

**Comment by saad3074** [comment]
same issue

**Comment by francescozanoni** [comment]
Hi.
In case of HTML-2-PDF, our workaroud is to slightly change the font size:
- this makes rendering fail:
  ````css
  body {
    font-size: 14px;
  }
  ````
- this works:
  ````css
  body {
    font-size: 13px;
  }
  ````
- this works:
  ````css
  body {
    font-size: 15px;
  }
  ````
Let's be honest: we do not know why...

**Comment by wanlerong** [comment]
stucking here

**Comment by yaroslawww** [comment]
I had the same problem on СentOS 8.
You can install specialized version for your OS  https://wkhtmltopdf.org/downloads.html
and change config:

*config/snappy.php*
```php
'binary'  => '/usr/local/bin/wkhtmltopdf', // or other installation path
```

**Comment by anteeek** [comment]
One of the reasons this could be happening is... loading google fonts in your document. When I removed them from the template it's gone
