### ISSUE TITLE
Greek characters problem in footer and header

### ISSUE THREAD

**Issue by mariosvasiliou** [barryvdh/laravel-snappy#131]
Hello,
Great work man,
I am testing this package to change my reports but i have problem with greek characters..
Page is displaying correctly in greek language but footer and header shows ??? instead of text...

This is my options

```
$pdfOptions = [
            'encoding'=>'UTF-8',
            'footer-font-name'=>'sans-serif',
            'footer-left'=> utf8_decode(trans('reports.createdby')),
            'footer-right'=> utf8_decode(trans('grid.page')) . ':[page]/[toPage]',
            'footer-font-size'=> 8,
            'footer-line'=>true,
            'lowquality'=>true
        ];

```

I have tried sans-serif,open sans and dejavu sans without luck...
Also in my view i have 

```
<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
```

This is how it looks...
![2016-09-21 10_18_05- - test](https://cloud.githubusercontent.com/assets/19802112/18701395/05accc0c-7fe5-11e6-8a82-279549f07ede.png)

I have search the comments and issues but nothing worked for me...Anyone else have this problem??

**Comment by barryvdh** [comment]
Does you font support the characters? You might need to install some fonts on your server with support for those chars.

**Comment by mariosvasiliou** [comment]
Hey Barry,
Thanks for the reply,
Yes i am using the same font as i use in blade view file...
In view file everything looks OK but footer appears ???
I have tried to load html file instead of setting text in PDF options but i have problem with page counter so i cannot go with alternative way...

**Comment by espiro** [comment]
install microsoft fonts on my centOs Solve problem

also add these two lines 
->setOption('encoding', 'utf-8')
and inside head
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

**Comment by romulomac** [comment]
[relatorio_ocorrencia (25).pdf](https://github.com/barryvdh/laravel-snappy/files/1649101/relatorio_ocorrencia.25.pdf)

Problema corrigido
