### ISSUE TITLE
margin-top cuts off header

### ISSUE THREAD

**Issue by ghost** [barryvdh/laravel-snappy#133]
I expected the header to expand downwards from margin top. Instead it seems that margin is treated like the bottom. Is normal behaviour?

Controller:
![controller](https://cloud.githubusercontent.com/assets/11746412/18798447/e6ed2cea-81d2-11e6-9b42-6644e62dff64.JPG)

Header:
![header](https://cloud.githubusercontent.com/assets/11746412/18798448/e6ef009c-81d2-11e6-89b0-b365833acfde.JPG)

Page:
![page](https://cloud.githubusercontent.com/assets/11746412/18798450/e6f3aac0-81d2-11e6-9738-05ad045bfbf8.JPG)

Result:
![test](https://cloud.githubusercontent.com/assets/11746412/18798449/e6f32c12-81d2-11e6-8c01-5ac434d50a45.JPG)

**Comment by jgreaves8** [comment]
@salacis same thing happens to the header if you add a "footer-html" option too.

What happens if you set a margin-top (in CSS) for the body as a whole?
