### ISSUE TITLE
PDF/Image not loading CSS when using versioned CSS

### ISSUE THREAD

**Issue by ryanmortier** [barryvdh/laravel-snappy#136]
For example, if I use `<link href="{{ elixir('css/app.css') }}" rel="stylesheet">` then none of my CSS is ever loaded and my PDF breaks spectacularly.

However, if I use `<link href="{{ asset('css/app.css') }}" rel="stylesheet">` then my CSS loads just fine and the PDF works. Easy workaround I suppose but do you know why this would be the case?

Sorry, I'm not even sure if this is a problem with `laravel-snappy` or if it's a problem with `wkhtmltopdf`.

Thank you.

**Comment by barryvdh** [comment]
Does elixir generate absolute paths? Can you combine them? `{{ asset(elixir('css/app.css')) }}`

**Comment by ryanmortier** [comment]
Ah you're correct, `elixir()` does relative paths and `asset()` does absolute paths. Combining them works great. Thank you.
