### ISSUE TITLE
Problem display Asset

### ISSUE THREAD

**Issue by shmoolki** [barryvdh/laravel-snappy#137]

**Comment by shmoolki** [comment]
I want to display pdf from view> That is a blade view, but when i put in this view asset like pictures with {{ asset(...) }} My pdf don't display and i have a timeout error.
So i ask how can i generate pdf with images.

Thanks

**Comment by mprandot** [comment]
Do like this : 

```html
<div class="col-xs-6">
            <img src="{{public_path($data->imagePath)}}">
</div>
```

**Comment by barryvdh** [comment]
Are you using a real web server? Php built in server doesn't work with concurrent requests.

**Comment by shmoolki** [comment]
I am using php artisan serve in local
But i tried too in my godaddy webserver and it is the same for the stlesheet
<link href="{{ asset("/css/style_pdf.css")}}" rel="stylesheet" type="text/css" />

**Comment by infernobass7** [comment]
I use an image in a PDF that i generate with this package. I believe it works best if you use the full URL (ex. http://www.mydomain.com/lib/images/pic.png )

**Comment by mprandot** [comment]
To me work in one way (using public_path):

CSS : 
```
<link rel="stylesheet" href="{{public_path('css/name.css')}}">
```

IMG :
```
<img alt="Logo" src="{{public_path(filename.extension)}}"/>
```

**Comment by danielroymoore** [comment]
I can confirm that mprandot's solution works

**Comment by Kikerrobles** [comment]
Works for me too. Before 06/17 it works with "asset", I was thinking that it was a server error for a month (stops working in two server at same time).
