### ISSUE TITLE
RuntimeException

### ISSUE THREAD

**Issue by ruchisheth** [barryvdh/laravel-snappy#138]
RuntimeException in Process.php line 371: The process has been signaled with signal "11".

This is my config file
<?php
return array(
    'pdf' => array(
        'enabled' => true,
        'binary' => base_path('vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64'),
        'timeout' => false,
        'options' => array(),
    ),
    'image' => array(
        'enabled' => true,
        'binary'  => base_path('vendor/h4cc/wkhtmltoimage-amd64/bin/wkhtmltoimage-amd64'),
        'timeout' => false,
        'options' => array(),
        // 'env'     => array(),
    ),
);

and this how I am trying to create a pdf from blade view
<?php
$pdf = PDF::loadView('admin.surveys.export_survey', $data);
return $pdf->inline('invoice.pdf');
?>

**Comment by saad3074** [comment]
i have the same issue

**Comment by saad3074** [comment]
@ruchisheth  can you find the solution . if yes then please share with me :)

Advance thanks

**Comment by ruchisheth** [comment]
Nope.... I just leaved it... Sorry can't help you
