### ISSUE TITLE
Class Barryvdh\Snappy\ServiceProvider not found

### ISSUE THREAD

**Issue by LucasPantoja** [barryvdh/laravel-snappy#140]
Did all the install steps, but when i run php artisan vendor:publish --provider="Barryvdh\Snappy\ServiceProvider", i got [Symfony\Component\Debug\Exception\FatalErrorException] Barryvdh\Snappy\ServiceProvider not found

my app.php providers contais Barryvdh\Snappy\ServiceProvider::class

**Comment by mihailbishkek** [comment]
I have exactly the same problem.

**Comment by Noctis17** [comment]
any solutions for this one?

**Comment by mattharley** [comment]
me too :(

**Comment by cwxorochi** [comment]
@LucasPantoja  try run command
`composer require barryvdh/laravel-snappy`

**Comment by anandnaga** [comment]
i have all so same issue....: (

 (1/1) Error

Class 'Barryvdh\Snappy\ServiceProvider' not found

**Comment by pendledt** [comment]
Have you tried running `composer dump-autoload`?

**Comment by onofreliscano** [comment]
> @LucasPantoja try run command `composer require barryvdh/laravel-snappy`

Thanks my friend!
