### ISSUE TITLE
The exit status code '127' says something went wrong

### ISSUE THREAD

**Issue by zhuojiawei** [barryvdh/laravel-snappy#141]
The exit status code '127' says something went wrong:\nstderr: \"/data/code/php/XXX/20161020-132810/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64: error while loading shared libraries: libXrender.so.1: cannot open shared object file: No such file or directory\n\"\nstdout: \"\"\ncommand: /data/code/php/XXX/20161020-132810/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64 --lowquality '/tmp/knp_snappy580d6f92e677a6.84880552.html' '/data/code/php/XXX/20161020-132810/storage/uploads/tmp/bill-123.pdf'.

**Comment by smplyjr** [comment]
Hi @zhuojiawei, I'm facing the same issue now. How do you solve this? Can you share?

**Comment by Brokan** [comment]
Has same problem. 
Solved by installing wkhtmltopdf:

sudo apt-get install wkhtmltopdf

**Comment by Dictator1999** [comment]
``ijhhjj

> Has same problem.
> Solved by installing wkhtmltopdf:
> 
> sudo apt-get install wkhtmltopdf
Hi Brokan, I install wkhtmltopdf by composer. but facing same error.
![image](https://user-images.githubusercontent.com/39425065/67012773-cc8d5d80-f113-11e9-9f3e-9fc4132238c5.png)

**Comment by mirihen** [comment]
has a same problem
sudo apt-get install wkhtmltopdf
The exit status code '127' says something went wrong: stderr: "sh: 1: /usr/bin/xvfb-run: not found " stdout: "" command: /usr/bin/xvfb-run --auto-servernum --server-num=1 wkhtmltopdf --lowquality '/home/ssheng/Documents/workspace/Jax/front/app/../web/snappy/knp_snappy5e0340977e54f6.46617670.html' '/home/ssheng/Documents/workspace/Jax/front/app/../web/snappy/knp_snappy5e0340977e5ab7.51080369.pdf'.
