### ISSUE TITLE
The exit status code '126' says something went wrong

### ISSUE THREAD

**Issue by neethukc** [barryvdh/laravel-snappy#142]
Hi,

I'm using linux os and this package run perfectly in my system.
But while i'm upload the project to production server it shows an error like

```
The exit status code '126' says something went wrong:
stderr: "sh: /home/projectname/public_html/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64: Permission denied
"
stdout: ""
command: /home/projectname/public_html/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64 --lowquality --page-size 'A4' '/tmp/knp_snappy5818127f177ea0.35948598.html' '/home/projectname/public_html/uploads/filename.pdf'.
```

Example code im using:

```
$pdf = App::make('snappy.pdf.wrapper');
 $contents = (string) $html;
$pdf->loadHTML($contents)
         ->setOption('page-size', 'A4');
$path = base_path() .'/uploads/'.$pdfname.'.pdf';
$pdf->save($path);
echo $pdfname;
```

Anybody have solution to this problem. Any help would be appreciated.
Thanks in advance.

**Comment by barryvdh** [comment]
Make your binary executable (chmod +x)

**Comment by Holisollogistics** [comment]
After make binary executable by (chmod +x) command, getting this error below
The exit status code '2' says something went wrong:
stderr: "/home/eps/public_html/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64: 2: /home/eps/public_html/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64: Syntax error: Unterminated quoted string
"
stdout: ""
command: /home/eps/public_html/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64 --lowquality --no-background '/tmp/knp_snappy58b807df5b6579.76174024.html' 'po/HLPL/PS/16-17/HOLISOL-PO_78787878.pdf'.

**Comment by rsteuber** [comment]
Doesn't work for me! Still got this error-msg. I also gave the path the right permissions and still got this error.

**Comment by deffisoan** [comment]
@rsteuber I got the same problem, do you have solutions?

**Comment by rsteuber** [comment]
Maybe youre page is beïnvloed rendered via ssl? Make Shure you don't using HTTPS .
