### ISSUE TITLE
Rasterize PDF and Signature Field

### ISSUE THREAD

**Issue by lrojas94** [barryvdh/laravel-snappy#143]
Hello!

Just wanted to see if there was a way to add a signature field using this plugin, and also, if there's a way to rasterize the PDF so that is not modifiable. As far as I can see, opening with Illustrator would mean I can change whatever I want from it, so wanted to make sure if this was a possibility.

Thanks in advance,
Luis.

**Comment by barryvdh** [comment]
Sorry, no idea. This is just a wrapper for Snappy, which is a wrapper for wkhtmltopdf
