### ISSUE TITLE
Unable to render Charts

### ISSUE THREAD

**Issue by rahularctic** [barryvdh/laravel-snappy#145]
I have used Morris js library to generate charts.
I dont get the chart displayed in the PDF.
Any modification required please let me know.

Thanks
![screenshot](https://cloud.githubusercontent.com/assets/16879826/20526911/26daa47a-b0ec-11e6-9624-5217d61c783e.png)

**Comment by barryvdh** [comment]
Perhaps you need to add a timeout or check for javascript errors.

**Comment by rahularctic** [comment]
Could you please post a sample snipper for that ?
I tried with the below script but it dint work.Am i missing something ?
        $data = array(); // contains nothing for time being
        $pdf = PDF::loadView('PDFTest', $data);
        $pdf->setOption('enable-javascript', true);
        $pdf->setOption('javascript-delay', 13500);
        $pdf->setOption('enable-smart-shrinking', true);
        $pdf->setOption('no-stop-slow-scripts', true);
        return $pdf->download('invoice.pdf');

**Comment by dorsho88** [comment]
This saved my life.

http://stackoverflow.com/questions/42561036/wkhtmltopdf-does-not-render-chart-js-2-5-0-graph

**Comment by admicaa** [comment]
Yup I had solved this problem 
try to use **Chartjs 1** not new chart js 
because laravel snappy uses wkhtmltopdf which doesn't support css animation 
and new  chartjs uses css animation 
[#4767](https://github.com/chartjs/Chart.js/issues/4767) show that 
and the solution i found is to use google chart which uses svg so you can get high resolution chart

**Comment by Badane** [comment]
Hi,
I facing the same issue. No matter what, there still is a problem when I want to render a chart in my PDF. I use to deal with ChartJs, but even with the @admicaa advice and changing for GoogleChart, I still have blank in my generated PDF. 
I have a simple view with google example chart, and tried two different way to use Snappy in my controller.
Some help please ;)

```
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
	<title>Export</title>
	<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['Year', 'Sales', 'Expenses'],
          ['2004',  1000,      400],
          ['2005',  1170,      460],
          ['2006',  660,       1120],
          ['2007',  1030,      540]
        ]);

        var options = {
          title: 'Company Performance',
          curveType: 'function',
          legend: { position: 'bottom' }
        };

        var chart = new google.visualization.LineChart(document.getElementById('curve_chart'));

        chart.draw(data, options);
      }
    </script>
</head>
<body class='sticky-header'>
	<section>
		<div id="curve_chart" style="width: 900px; height: 500px"></div>
		coucou
	</section>
</body>
</html>
```

```

//       $export =  PDF::loadView('report.pdfexport',array('data' => $jsonData))->setPaper('a4')
//       ->setOption('margin-top', 10)
// ->setOption('margin-bottom', 45);
//       $name = 'output.pdf';
//       return $export->download($name);

        $name = 'output.pdf';
        return app('snappy.pdf.wrapper')->setOption('javascript-delay', 5000)
           ->loadHTML(view('report.pdfexport', array('data' => $jsonData))
           ->render())->download($name . '.pdf');
```

**Comment by admicaa** [comment]
@Badane   , I hope you solved this problem, (I'm sorry I just saw the comment).

- don't use url() fucntion if you wanted to include js in your document you have to require it or include it,\

-  use chartjs 1.1 no higher version .
You can see this working example right here https://github.com/admicaa/larabook

**Comment by RitaP06** [comment]
@admicaa i have cloning yaor larabook project
but it still not working

Warning: require(C:\xampp\htdocs\larabook\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\larabook\bootstrap\autoload.php on line 17

Fatal error: require(): Failed opening required 'C:\xampp\htdocs\larabook\bootstrap/../vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\larabook\bootstrap\autoload.php on line 17

please give me advice
