### ISSUE TITLE
Footer encoding problem Win10/Ubuntu14

### ISSUE THREAD

**Issue by EcoFreak** [barryvdh/laravel-snappy#150]
I'm currently setting the footer info like so:
`->setOption('footer-right', utf8_decode('Página [page] de [toPage]'))     `
`->setOption('footer-left', utf8_decode('Extraída a ' . Carbon::now()->toDateTimeString()))
`
In Win 10 it all works ok:

![image](https://cloud.githubusercontent.com/assets/3418386/21181582/906f7c60-c1f6-11e6-8f9d-49620198067d.png)

But in Ubuntu 14, not so much:

![image](https://cloud.githubusercontent.com/assets/3418386/21181598/a5e9f0e8-c1f6-11e6-9e09-f8fa465e2546.png)

Any ideas?

**Comment by mprandot** [comment]
Do you have put UTF-8 in your HTML?

**Comment by EcoFreak** [comment]
@mprandot  Yes, html has the UTF-8 metadata tag. But I think it has no impact here, mainly due to the fact that both servers are generating the same html file. The only difference is this encoding issue in the footer.

**Comment by EcoFreak** [comment]
@mprandot Any ideas on how to solve the problem :) ?

**Comment by mprandot** [comment]
@EcoFreak, put the data inside a file. Maybe it's work.

**Comment by EcoFreak** [comment]
@mprandot But how can I use variables like current page and total pages?
