### ISSUE TITLE
Two different PHP to one PDF

### ISSUE THREAD

**Issue by MaximeDawn** [barryvdh/laravel-snappy#151]
Hello,

Is it possible to print for exemple www.google.com on page 1 and www.facebook.com on page 2. This would really help. 

And btw, thanks for Snappy, this is awesome !

**Comment by barryvdh** [comment]
Not sure, perhaps better to find a pdf merge (command line) utility

**Comment by MaximeDawn** [comment]
Yes that was i was looking for while waiting for an answer. I'll probably use that. Thanks !

**Comment by njanik** [comment]
Even if it's already possible with snappy?
https://github.com/KnpLabs/snappy#merge-multiple-urls-into-one-pdf
