### ISSUE TITLE
Problem with Laravel queues

### ISSUE THREAD

**Issue by MaximeDawn** [barryvdh/laravel-snappy#152]
Hi, 
As I have to generates multiple PDF at one time, I decided t put it in a queue. The problem is that it totally fails. The pdf generated has no CSS at all, and the code stops just after the ->save() method.

If i just move the part of code to my controller, it works perfectly well. Any idea ?

**Comment by barryvdh** [comment]
Did you configure the APP_URL?

**Comment by MaximeDawn** [comment]
@barryvdh I figured out what the problem is ! It comes from the URL::asset() function. When in my controller i have "http://localhost/lam/foo", and from the job "http://localhost/foo". Looks like the job doesn't care of 'APP_URL' config. Any idea ? When i set my CSS paths to full URL, but I really don't want that solution 😞 You can if u want see my "lamouroux-webapps" repo ! THanks in advance
