### ISSUE TITLE
wkhtmltopdf-i386: cannot execute binary file

### ISSUE THREAD

**Issue by mparicioitb** [barryvdh/laravel-snappy#156]
I install using composer

When i try to do:
vendor/h4cc/wkhtmltopdf-i386/bin/wkhtmltopdf-i386 --version

This give me the error: cannot execute binary file.

Then, in snappy.php i use:
     'binary' => base_path('vendor/h4cc/wkhtmltopdf-i386/bin/wkhtmltopdf-i386'),
The file exists, but seems not work.

In the view:

RuntimeException in AbstractGenerator.php line 336:
The exit status code '2' says something went wrong:
stderr: "/media/pi_develop/www/html/sgitv/vendor/h4cc/wkhtmltopdf-i386/bin/wkhtmltopdf-i386: 1: /media/pi_develop/www/html/sgitv/vendor/h4cc/wkhtmltopdf-i386/bin/wkhtmltopdf-i386: Syntax error: "(" unexpected
"
stdout: ""
command: /media/pi_develop/www/html/sgitv/vendor/h4cc/wkhtmltopdf-i386/bin/wkhtmltopdf-i386 --lowquality '/tmp/knp_snappy5880a49b3d15d5.78290934.html' '/tmp/bill-123.pdf'.

What can i do? Thx. -María.

**Comment by jgreaves8** [comment]
@mparicioitb What type of server are you running this on? Wampp?

**Comment by mparicioitb** [comment]
Hi! thanks for yout answer.
My server its a LAMP with a Raspberry 3 model B.

**Comment by fskirschbaum** [comment]
I know it's late, but stumbled over this one...

Raspberry Pi 3 is ARM architecture, so i386 built binary won't work. You'd have to either compile wkhtmltopdf yourself or find a binary already compiled against ARM architecture to get it working.

**Comment by mparicioitb** [comment]
Thank you, I found a temporary solution.
If someone else has this problem:
I finally installed wkhtmltopdf with apt-get and changed the path of the snappy file to:
'binary' => '/usr/local/bin/wkhtmltopdf.sh',

Requires installing and configuring xvfb.

For the installation to work with Raspberry 3, wkhtmltopdf version 0.12.1 must be installed.
The footers do not work with version 0.12.1.
