### ISSUE TITLE
exceeded the timeout of 60 seconds

### ISSUE THREAD

**Issue by mapb1990** [barryvdh/laravel-snappy#16]
Hi,

I'm try to use this package, but I am getting the following error:

> The process "C:\"Program Files"\wkhtmltopdf\bin\wkhtmltopdf --lowquality "C:\Users\MIGUEL~1\AppData\Local\Temp\knp_snappy54052f4d61f0d1.70329205.html" "C:\Users\MIGUEL~1\AppData\Local\Temp\knp_snappy54052f4d6234f1.36255900.pdf"" exceeded the timeout of 60 seconds.

If I run the cmd in console works.

**My code:**

``` php
    public function test()
    {
        $budget = Budget::with(['creator', 'client', 'items'])->findOrFail(1);
        $this->theme->asset()->usePath()->add('styles', 'css/styles.min.css');
        set_time_limit(60*5);

        $html = '<!DOCTYPE html>
        <html>
            <head>
                <meta charset="utf-8">
                <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
                <title>' . Theme::get('title')  . '</title>
                <meta name="viewport" content="width=device-width">' .
                $this->theme->asset()->styles() . '
            </head>
            <body id="invoice-page">' . View::make('budgets.theme1', compact('budget'))->render() . '
            <body>
        </html>';
        $pdf = PDF::loadHTML($html);
        // return $html;
        return $pdf->download('invoice.pdf');
        return $pdf->save('D:\\o.pdf');
        return $pdf->stream();
    }
```

**Comment by itsazzad** [comment]
I am  also having the same problem.
Tried with upgrading default_socket_timeout=value

**Comment by cadyfatcat** [comment]
Check out this issue for potential solution if you are trying this on artisan dev server: https://github.com/KnpLabs/snappy/issues/58

**Comment by AshishGupta001** [comment]
I use **barryvdh/laravel-snappy": "^0.3.0** had face the timeout issue when trying to include a logo in the HTML file to be printed. Issue is wiered as the PDF file is actually printed but process keeps running for about a min or so and then fails.

If I remove the logo then PDF is printed instantly without any timeout exception been thrown.

I am using PHP 5.5.9 and Laravel 5.0.X. Looked at KnpLabs/snappy#58 but not sure what I need to change to fix the "false negative".

Any pointer will be helpful.

**Comment by kheengz** [comment]
try using `{{public_path('css/mycss.css')}}` instead of `URL::to()` or `asset()`

**Comment by ingamartinez** [comment]
> try using `public_path('')` instead of `URL::to()` or `asset()`

This is solution worked for me, I replaced all my `asset()` but why it works?

**Comment by gogilo2003** [comment]
I used intervention/image and encoded the image to base64 and it solved my problem
```
<img src="{{ \Intervention\Image\Facades\Image::make(public_path('img/logo.png'))->encode('data-url') }}" alt="">
```
I hope that helps somebody
