### ISSUE TITLE
How to can print user using search filter functionality?

### ISSUE THREAD

**Issue by vipin733** [barryvdh/laravel-snappy#163]
Like I have filter functionality in my app where we can search users in specific year or class but problem is that how can print that like if I search for class Ma and I got total 25 students so how can print them
   `public function unpaid(Request $request)
   {

     $coursewise = $request->course;

     $dt = Carbon::now();

     if ($coursewise)
     {
       $sub = Student::where('status',1)->where('course_id',$coursewise)->whereDoesntHave('subscriptions', function ($query) use($dt) {

              $query->whereMonth('created_at','=',$dt->month);

           })->with('courses')->paginate(15);
     }

     else
     {
       $sub = Student::where('status',1)->whereDoesntHave('subscriptions', function ($query) use($dt) {

              $query->whereMonth('created_at','=',$dt->month);

           })->with('courses')->paginate(15);
     }

     $courses = DB::table("courses")->pluck("name","id");

     if ($request->print)
      {
         $pdf=PDF::loadView('fee.printpdf',compact('sub','courses'));

         return $pdf->stream($sub->student_name. '.' .'pdf');

     }else
     {
        return view('search.search_unpaid',compact('sub','courses'));
     }
     
   }`

**Comment by jgreaves8** [comment]
@vipin733 I'm assuming this is Laravel? you'll need to pass any dynamic data to a view, and then maybe use a foreach loop within the view

Looks like you'd need to add this loop inside your fee.printpdf view?

**Comment by vipin733** [comment]
@jgreaves8 i did
 ` @foreach($sub as $s)
            <?php $i++ ?>
              <tr>
                  <td>{{ $i }}</td>
                  <td>{{ $s['student_name'] }}</td>
                  <td>{{ $s['reg_no'] }}</td>
                  <td>{{ $s->courses['name'] }}</td>
                  <td>{{ $s['father_name'] }}</td>
                  <td>{{ $s['mother_name'] }}</td>
              </tr>
 @endforeach`
here u can see in above my first post "loadView I'm passing $sub variable"

**Comment by jgreaves8** [comment]
@vipin733 what do you get if you do dd($sub) inside the view?

Also I might be wrong but shouldn't you be getting "student name" etc. by $s->student_name ?

**Comment by vipin733** [comment]
yes I'm getting .problem is that when i try to filer the student by selecting course_id but when i hit the print button its print all student instead of only filter atudent
