### ISSUE TITLE
Different results when processing on different servers

### ISSUE THREAD

**Issue by calina-c** [barryvdh/laravel-snappy#164]
Hello! I am using Laravel Snappy and wkhtmltopdf for some clients who are very specific about font sizes and spacing. The result looks great *locally* without any extra options, but on the production server the font sizes and spacings are different. I used the `disable-smart-shrinking` option on the production server and now it looks similar to the local result. I would like to mention that applying the same option locally results in a total mess.

Does Laravel Snappy (or wkhtmltopdf) assume or infer any options that might be different between the two servers? If so, how can I see which options are used each time? Alternately, could there be any other reason to the different outcomes?

Any help on this matter will be greatly appreciated. Thank you!

**Comment by RodrigoFraga** [comment]
I'm having this same problem with how fonts

**Comment by jgreaves8** [comment]
@calina-c are you loading views? or just passing raw HTML?

**Comment by calina-c** [comment]
@jgreaves8 I was loading views.

The problem was solved using another PDF rendering library (TCPDF). Should I close this, or leave it open for future reference?

**Comment by barryvdh** [comment]
I think it also depends on which fonts are installed on your platform. It uses webkit to render + print to pdf internally, so if you have different fonts installed (for example) it can differ.
