### ISSUE TITLE
Laravel 5.4

### ISSUE THREAD

**Issue by furkanayata** [barryvdh/laravel-snappy#168]
Hi, It seems that laravel-snappy is not Laravel 5.4 compatible. 

`PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Illuminate\Foundation\Application::share() in /***/***/***/vendor/barryvdh/laravel-snappy/src/ServiceProvider.php:31  `

**Comment by barryvdh** [comment]
Can you try with latest tag (0.3.3)

**Comment by furkanayata** [comment]
Nice! It's working now :) Thanks
