### ISSUE TITLE
Open an PDF and change information

### ISSUE THREAD

**Issue by vinigarcia87** [barryvdh/laravel-snappy#169]
Hi!
How can I open an PDF file, change information in it (example, I want to search for [[name]] and replace by a name from my sistem), then save it back to PDF?

Also, I wanna know how can I duplicate sheets of a PDF or merge two PDF file's in one.

Thanks!

**Comment by barryvdh** [comment]
Don't know, but not with snappy

**Comment by mikevrind** [comment]
I know that pdflib (https://www.pdflib.com) offers a lot more options but as far as I know, this is (or was) a paid PHP extension.
