### ISSUE TITLE
stream not working?

### ISSUE THREAD

**Issue by vipin733** [barryvdh/laravel-snappy#170]
I try to stream page in browser user $pdf->stream(name.pdf) its automatically download  but i want stream in browser. any idea where i doing wrong

**Comment by MSMontenegro** [comment]
I have they same problem. Any solution?

**Comment by barryvdh** [comment]
Are you sending other headers in htaccess or nginx?

**Comment by byustephen** [comment]
If you are using Google Chrome it might have a setting that overrides the stream command. I turned it off and the stream command and inline command now works for me. 

Check out this post for more info:

[](https://support.google.com/chrome/answer/6213030?hl=en)
