### ISSUE TITLE
footer-html with page number

### ISSUE THREAD

**Issue by rafwell** [barryvdh/laravel-snappy#174]
Hi, the replace of currenty page number [page] and total page [toPage] not working when use footer-html. It's the expected behavior? I really need this.

**Comment by rafwell** [comment]
This work fine: http://stackoverflow.com/a/37807113/4470071
I'ts the correcty/only way? Maybe add this on documentation is a good idea.

**Comment by oscarAG** [comment]
Try setting the footer text via the options in config/snappy.php file. 

    'pdf' => array(
        'enabled' => true,
        'binary'  => base_path('vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64'),
        'timeout' => false,
        'options' => array(
            'page-size' => 'A4',
            'margin-top' => 5,
            'margin-right' => 5,
            'margin-left' => 5,
            'margin-bottom' => 6,
            'orientation' => 'Landscape',
            'footer-center' => 'Page [page] of [toPage]',
            'footer-font-size' => 8,
            'footer-left' => 'Confidential'
        ),
        'env'     => array(),
    )

You can see a full list of options in the [wkhtmltopdf documentation](http://wkhtmltopdf.org/usage/wkhtmltopdf.txt). 

This is how I do it, I haven't tried this, but you should also be able to set options at runtime using chain methods. 

`PDF::loadHTML($html)->setOption('footer-center', 'Page [page]')->save('myfile.pdf'); `

**Comment by rafwell** [comment]
Thanks for reply @oscarAG. With footer-center/footer-right work fine, i've tested. But, the question is over footer-html.

**Comment by dct24** [comment]
@rafwell 
I think I got it working.

as [Doc of wkhtmltopdf](https://wkhtmltopdf.org/usage/wkhtmltopdf.txt ) stand : 

>  As can be seen from the example, the arguments are sent to the header/footer
  html documents in get fashion.

1) prepare route, for example:
 `Route::get('pdf/footer', 'PDFController@getFooter')->name('pdf.footer');`

2) construct PDF, with route passed to 'footer-html' for example:
`$pdf = PDF::loadView('content.pdf', $data)
->setOption('footer-html', route('pdf.footer'))
->setOption('margin-bottom', 10)
->setPaper('a4'); 

return $pdf->inline();`

3) in PDFController - compact "$_GET params" to your footer blade
`public function getFooter(Request $request)
    {
    	$query = $request->all();
    	return view('pdfFooter',compact('query'));
    }`

4) now in footer blade you have an array, sth like:
  "page" => "1"
  "section" => ""
  "sitepage" => "1"
  "title" => null
  "subsection" => ""
  "frompage" => "1"
  "subsubsection" => null
  "isodate" => "2017-06-12"
  "topage" => "1"
  "doctitle" => null
  "sitepages" => "1"
  "webpage" => ""
  "time" => "16:02:14"
  "date" => "2017-06-12"
]`

5) and can access it like:
`Page {{ $query['page'] }} of {{ $query['topage'] }}`

Sorry for my english. Any code improvements are welcomed.

**Comment by twf-nikhila** [comment]
@rafwell: the javascript mentioned on the StackOverflow link works. (y) , 

Passing $_GET param doesn't work for me.

**Comment by enricooliva** [comment]
> @rafwell
> I think I got it working.
> 
> as [Doc of wkhtmltopdf](https://wkhtmltopdf.org/usage/wkhtmltopdf.txt) stand :
> 
> > As can be seen from the example, the arguments are sent to the header/footer
> > html documents in get fashion.
> 
> 1. prepare route, for example:
>    `Route::get('pdf/footer', 'PDFController@getFooter')->name('pdf.footer');`
> 2. construct PDF, with route passed to 'footer-html' for example:
> 
> ```
> $pdf = PDF::loadView('content.pdf', $data)
> ->setOption('footer-html', route('pdf.footer'))
> ->setOption('margin-bottom', 10)
> ->setPaper('a4'); 
> 
> return $pdf->inline();
> ```
> 
> 1. in PDFController - compact "$_GET params" to your footer blade
> 
> ```
> public function getFooter(Request $request) 
> {
> $query = $request->all();
> return view('pdfFooter',compact('query'));
> }
> ```
> 
> 1. now in footer blade you have an array, sth like:
> 
> ```
>   "page" => "1"
>   "section" => ""
>   "sitepage" => "1"
>   "title" => null
>   "subsection" => ""
>   "frompage" => "1"
>   "subsubsection" => null
>   "isodate" => "2017-06-12"
>   "topage" => "1"
>   "doctitle" => null
>   "sitepages" => "1"
>   "webpage" => ""
>   "time" => "16:02:14"
>   "date" => "2017-06-12"
> ]
> ```
> 
> 1. and can access it like:
>    `Page {{ $query['page'] }} of {{ $query['topage'] }}`
> 
> Sorry for my english. Any code improvements are welcomed.

I like the approach but I'm getting the error:
Failed to load ... with network status code 3 and http status code 0 - Host ... not found.

**Comment by hellomohsinhello** [comment]
@enricooliva 
Did you find the solution?

**Comment by enricooliva** [comment]
> @enricooliva
> Did you find the solution?

I used the approach with JavaScript code mentioned in the documentation and  StackOverflow in the header-html and also upgrading the wkhtmltopdf package on Ubuntu.

`$pdf->setOption('header-html', $header);`

JavaScript code:
```
function subst() {        
        var vars={};        
        var x=window.location.search.substring(1).split('&');
        for (var i in x) {
            var z=x[i].split('=',2);
            vars[z[0]] = unescape(z[1]);
        }
        if(vars.page > 1){ 
...
        }
    }
```
