### ISSUE TITLE
Adding header-html causing error

### ISSUE THREAD

**Issue by netm** [barryvdh/laravel-snappy#175]
I'm trying to add a page header and have setup a route resolving to a blade template so wkhtmltopdf can include it as a header. When I go to the route it's working fine but wkhtmltopdf throws the following error. If I comment out the header-html line the pdf generates great.

	$pdf = PDF::loadView('customer.report_pdf.gps', $data)
		->setOption('header-html', 'http://localhost/customer/genome/report/header/AAA-AAA-AAA/weightLoss')
		->setPaper('a4')
		->setOrientation('portrait');

![image](https://cloud.githubusercontent.com/assets/1432243/23236939/18171b54-f9c0-11e6-89b3-4f41b26b2971.png)

**Comment by coolsam726** [comment]
@netm This should be reopened. I am encountering the same error
