### ISSUE TITLE
Question: how do i getSize for newly created PDF's

### ISSUE THREAD

**Issue by h3ndro** [barryvdh/laravel-snappy#176]
Hi, I wonder is there some way to return newly generated pdf's meta's such as file size, mimetype etc?i need to save this information to table after pdf's are generated.

thank you

**Comment by barryvdh** [comment]
Not that I know of

**Comment by h3ndro** [comment]
oo,.ic,... i guess i just have to find workaround then :)

**Comment by h3ndro** [comment]
got it,...here's what i got using `filesize()` and `mime_content_type()`
`$file = PDF::loadView('report.pendaftaran', $data)->setPaper('legal')->setOrientation('portrait')->save('uploads/filename.pdf');`
`$getfile = 'uploads/filename.pdf';`
`$getFSize = filesize($getfile);`
`$getFMime = mime_content_type($getfile);`
after that i just save the info i got to table. well, i guess i just have to visit php manual more often :)

thanks
