### ISSUE TITLE
config base in environments

### ISSUE THREAD

**Issue by scortes1989** [barryvdh/laravel-snappy#178]
update config/snappy.php based in enviroments config.

 `  'pdf' => [
        'enabled' => true,
        'binary' =>  env('PDF_BINARY'),
        'timeout' => false,
        'options' => array(),
        'env'     => array(),
    ],

    'image' => [
        'enabled' => true,
        'binary' => env('IMAGE_BINARY'),
        'timeout' => false,
        'options' => array(),
        'env'     => array(),
    ],`

**Comment by barryvdh** [comment]
Is this meant to be a PR?

**Comment by byjujohn** [comment]
Please see the PR #361
