### ISSUE TITLE
Error generating pdf

### ISSUE THREAD

**Issue by thiagodionizio** [barryvdh/laravel-snappy#181]
I'm encountering problems using the package. Would you help me

`/vendor/knplabs/knp-snappy/src/Knp/Snappy/AbstractGenerator.php line 364:`

`Unable to write in directory: / var / folders / 48 / 1m5p9s490s57zyqb0th1flvw0000gn / T
`

I am generating a pdf from a View, detail are more than 600 pages.

**Comment by nepfrank** [comment]
I am exactly having the same problem. Any solutions?

**Comment by dotcomlab** [comment]
Having the same issue. Anyone figured out a fix?

**Comment by Boomchart** [comment]
The solution to this is to edit the package code, not recommended, but it works.
Navigate to vendor/knplabs/knp-snappy/src/Knp/Snappy/AbstractGenerator.php line 340
Change return \sys_get_temp_dir(); to return storage_path('tempdir');
That is all. This will storing temporary files in OS temp files and use laravel storage folder.
