### ISSUE TITLE
How can I set margin on Cover Page ?

### ISSUE THREAD

**Issue by tbaraiya** [barryvdh/laravel-snappy#182]
I have a pdf with Cover page. 

I use laravel 5.2 with snappy pdf.

My code is ::

```
$pdf = \PDF::loadHTML($view->render());
         $pdf->setOption('cover', View::make('generatereport.pdfcoverpage', $dataArray));
        $pdf->setOption('margin-top',0);
        $pdf->setOption('margin-bottom',10);
        $pdf->setOption('margin-left',0);
        $pdf->setOption('margin-right',0);
        $pdf->setOption('footer-html',  View::make('generatereport.pdffooter'));
```

The problem is 'margin-bottom' in also apply on cover page.
any way here to set cover page 'margin-bottom = 0' ?

**Comment by ghanshyamtank59** [comment]
I have same problem

**Comment by ghanshyamtank59** [comment]
I have include PDFMerger library with this library (laravel-snappy).

`
                    // Install new library for PDFMerger - "rguedes/pdfmerger": "^1.0",
                    // Include PDFMerger library in file - use PDFMerger;

                    $file_name_generated = 'test.pdf';
                    $subfolder_path = 'test_pdf';
                    $exact_path = '../storage/'.$subfolder_path;

                    $headerHtml = view()->make('pdf.header')->render();

                    // Generate cover PDF
                    $cover = PDF::loadView('pdf.cover', $coverData)
                        ->setOption('no-background', false)
                        ->setOption('background', true)
                        ->setOption('disable-javascript', true)
                        ->setOption('print-media-type', false)
                        ->setOption('margin-bottom', 0)
                        ->setOption('margin-left', 0)
                        ->setOption('margin-right', 0)
                        ->setOption('margin-top', 0)
                        ->save($exact_path.'/tmp/cover_'.$file_name_generated);
                    $coverUrl = storage_path($subfolder_path.'/tmp/cover_'.$file_name_generated);

                    // Generate Draft Care Plan PDF
                    $pdf = PDF::loadView('pdf.content', $pdfContentData)
                        ->setOption('margin-left','15')
                        ->setOption('margin-right','15')
                        ->setOption('margin-top','30')
                        ->setOption('margin-bottom','20')
                        ->setOption('header-html', $headerHtml)
                        ->setOption('footer-html', route('pdf.footer'))
                        ->save($exact_path.'/tmp/'.$file_name_generated);
                    $contentUrl = storage_path($subfolder_path.'/tmp/'.$file_name_generated);
                    $tempFolderPath = storage_path($subfolder_path.'/tmp_'.$draftId);

                    // Merge PDF
                    $newpdf = new PDFMerger();
                    $newpdf->addPDF($coverUrl, '1');
                    $newpdf->addPDF($contentUrl, 'all');
                    $newpdf->merge('file', $exact_path.'/'.$file_name_generated);

`
Thanks
