### ISSUE TITLE
Wrong Template When PDF is generate via laravel's mail queue run as a daemon after an exception

### ISSUE THREAD

**Issue by mohamedazher** [barryvdh/laravel-snappy#185]
I have been debugging this issue all day and this is what i have noticed.

When you generate PDF inside laravel's Mail::later closure, while the Laravel's queue listener is run as daemon (i use redis for queues), if there if there is an exception while the view is rendered, the exceptions does not get thrown back the stack trace and hence the view sections are not flushed as the exceptional handlers in the view class are not called.  

Now the next time a proper PDF is generated you get the last properly generated view/PDF not the current one. This issue is exactly the same as the one mentioned here https://github.com/laravel/framework/issues/9881 where the email template views were not flushed during an exception. This was late fixed as mentioned in this issue. 

The solution seems to be to call View::flushSections() whenever there is an exception. Now since the view generation happens inside mail's closure, the exception not throw back to the view's class, rather is just skips and goes to mark the queue as failed. 

I tried adding \Illuminate\Support\Facades\View::flushSections(); to Illuminate\View\Engines\PhpEngine.php in handleViewException method, and it does seem to solve the issue, but it would be better if there was some way to handle this issue.

This is only an issue if the queue listener is running as a daemon

**Comment by barryvdh** [comment]
Not sure if this is an issue with Snappy or with Laravel?

**Comment by mohamedazher** [comment]
I am not really sure myself. The issue occurs when an error in view occurs, this exception is not handled by the view's exception handler rather gets thrown elsewhere, the exception handlers in Snappy do not work either.

I tried  adding View::flushSections() just before calling the PDF::loadView() method and it seems to have take care of the issue for now as the view sections stack gets cleared. The exception handlers in Views class do the same, and since the queue listener runs as daemon until killed/restarted, it seems to have the View sections in memory and does not/cannot clear it if an error occurs.

It would be great Snappy can check and clear sections before generating a new view. This should solve the problem.
