### ISSUE TITLE
Mixed Orientation possible?

### ISSUE THREAD

**Issue by gkallian** [barryvdh/laravel-snappy#187]
Is there any way to achieve mixed orientation? I want the first page to have portrait orientation while the others landscape.

**Comment by twf-nikhila** [comment]
@gkallian : Did you got any solution here? I'm looking for the same.

**Comment by gkallian** [comment]
@twf-nikhila : Nope, no solution found.

**Comment by willsmanley** [comment]
Was this ever resolved? I figure there is probably a way to create separate PDF documents (one document with a few pages in landscape, and one document with a few pages in portrait) and then merge them (although I haven't looked into this).

**Comment by leond08** [comment]
Did you get any solution? I'm looking also for this

**Comment by ifly-leonard** [comment]
@leond08 There is no way to do it directly via snappy. The best way to do it is, to generate your PDF's in different layouts separately and then merge them together. There is a package to do that. https://github.com/GrofGraf/laravel-pdf-merger 

There are also free API's online too, one google search away.  Hope it's helpful.
