### ISSUE TITLE
setOption('title', 'value') not working

### ISSUE THREAD

**Issue by stijnvanouplines** [barryvdh/laravel-snappy#189]
Hi,

I want to set the name of the PDF with the option 'title', but it is using the ID of the model.

This is the code inside the controller:

```
$pdf = PDF::loadView('pdf', [
        'model'  => $model,
    ])
    ->setOption('title', env('APP_NAME').$model->name)
    ->output();
```

The title in the view is also set to:
`<title>{{ env('APP_NAME') }} {{ $model->name }}</title>`

Thanks!

**Comment by stijnvanouplines** [comment]
Never mind, I found the problem!

I'm attaching the file to an email and I had to specify the filename as follow:
`->attachData($this->pdf, env('APP_NAME').'.pdf')`

**Comment by stijnvanouplines** [comment]
Never mind, I found the problem!

I'm attaching the file to an email and I had to specify the filename as follow:
`->attachData($this->pdf, env('APP_NAME').'.pdf')`

**Comment by etmind** [comment]
i still have this problem. Do you found some solution ?

**Comment by stijnvanouplines** [comment]
You can try to add a `<title>` tag to your view.

**Comment by etmind** [comment]
i do that, but no effect.
