### ISSUE TITLE
Passing variables.

### ISSUE THREAD

**Issue by babakshaban** [barryvdh/laravel-snappy#190]
Hi,

I have a function from within my controller (projectController) from which I call PDF::loadView in the hope of passing the view with a variable ($projects) to snappy.

My code is as 

`public function exportPdf()
    {
        //$snappy = App::make("snappy.pdf");
        //$snappy->generate("http://www.github.com", "/tmp/github2.pdf");
        //
      //$pdf=App::make("snappy.pdf.wrapper");
       //$pdf->loadHTML("testing");
       //

       $projects = Project::all();
       $projects->toArray();      
        $pdf = PDF::loadView("projects.index", $projects);
        return $pdf->download("invoice.pdf");
       
    }`
The two commented out bits of code above work fine I am getting errors when passing a variable to loadView. The error is as follows.

`Whoops, looks like something went wrong.

2/2
ErrorException in 815b10a9263616cef7f18e26d46f3bd36ae10e37.php line 8:
Undefined variable: projects (View: D:\git\portal\resources\views\projects\index.blade.php)
in 815b10a9263616cef7f18e26d46f3bd36ae10e37.php line 8
at CompilerEngine->handleViewException(object(ErrorException), "1") in PhpEngine.php line 44
at PhpEngine->evaluatePath("D:\git\portal\storage\framework\views/815b10a9263616cef7f18e26d46f3bd36ae10e37.php", array("__env" => object(Factory), "app" => object(Application), "errors" => object(ViewErrorBag), array("id" => "7", "code" => "typical project", 
<--- Section deleted for brevity -->
, "updated_at" => "2017-04-10 05:53:16", "created_at" => "2017-04-07 01:36:34", "submitterId" => "22"))) in CompilerEngine.php line 59`

The $projects array is being passed but it doesn"t seem like it is being recognised by the view? I"m I doing this the wrong way? I know variables can be passed to it.

Any hep would be greatly appreciated,
Thanks,
Bobbie.

Edit: Sorry for the formatting the output didn"t seem to format very well.

**Comment by barryvdh** [comment]
Same as a normal view, pass an array with data.
