### ISSUE TITLE
table tr spanning over a page break causes content issues

### ISSUE THREAD

**Issue by AndreasElia** [barryvdh/laravel-snappy#191]
Hello!

So I have a table with around 50 paragraphs of Lipsum, I then have the table setup so that the `thead` displays on the fresh page after a page break using `style="display: table-header-group;"` - this appears to work up until noticing the text actually overlays the `thead`.

I've spent longer than I'd like to admit trying to fix this and have found no working solution. I've had to simply use `style="display: table-row-group;"` and have no table heading after a page break (which sucks).

Any help would be greatly appreciated.

Related:
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1524
https://github.com/barryvdh/laravel-snappy/issues/106

**Comment by nasirkhan** [comment]
I found many suggestions to hide the table header. But it was a must for me to show the header. The following CSS resolved the page header overlap issue, i hope this might help you too. 

I put my table info a DIV which has a class `export-table` and added the following CSS and it resolved the issue. 

```
@media print {
    .export-table {
        overflow: visible !important;
    }
}
```


You can updated your css like follows,

```
@media print {
    .class-name-which-holds-the-table {
        overflow: visible !important;
    }
}
```
