### ISSUE TITLE
String svg will not render in PDF

### ISSUE THREAD

**Issue by LeAcid** [barryvdh/laravel-snappy#192]
I have a string that I am passing up to the server with <svg></svg> tags and I am only able to render the html around the svg tags. Is there something that I should be doing to make this happen. Or is it outside of the scope of this package to render svg's into pdfs?

**Comment by barryvdh** [comment]
Not sure, should be possible I think. But depends on wkhtmltopdf itself.

**Comment by LeAcid** [comment]
Yeah I have been digging into that for a little while now. While it looks possible the documentation for doing something like that is non-existent. I found one issue thread that looked promising but doesn't seem to work. At least not on the newer versions. So for me for now, I am letting this one go. Thanks for getting back to me though and awesome package!

**Comment by vool** [comment]
For anyone else caught by this, encoding the image as bas64 is a workaround eg

`$svg = '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 36 36" class="circular-chart">
    <path class="circle-bg"
          stroke-width="1"
          fill="none"
          stroke="#ddd"
          d="M18 2.0845
             a 15.9155 15.9155 0 0 1 0 31.831
             a 15.9155 15.9155 0 0 1 0 -31.831"
          />
</svg>';

$html = '<img src="data:image/svg+xml;base64,'.base64_encode($svg).'"  width="100" height="100" />';
`
Ref: https://stackoverflow.com/a/59529460/147323
