### ISSUE TITLE
Easy way to save files directly to S3?

### ISSUE THREAD

**Issue by mozami** [barryvdh/laravel-snappy#193]
Hi,

So I can generate pdf files on my server and save them locally or download to browser. However, instead of storing them on the web server, it would be ideal if the files could be pushed directly to S3. 

Currently, I am saving them to local storage path, then uploading the pdf to S3 (using `Storage::put` to move to AWS S3) and deleting the local copy. Is there a way to save files directly to cloud?

Thanks!

**Comment by mozami** [comment]
Fixed! In case anyone else is wondering, just use $pdf->output() to stream the file:

```
$pdf = PDF::loadView('pdf.invoice', $data);
Storage::put($file, $pdf->output()); 
```

In my case, default storage has already been setup as "S3" in config

**Comment by shahrukh4** [comment]
Thanks, this saved my life..phewww

**Comment by elvis-chuks** [comment]
Hello there,
in your response you have `Storage::put($file, $pdf->output()); `
what data does the `$file` variable hold?

**Comment by audetcameron** [comment]
> Hello there,
> in your response you have `Storage::put($file, $pdf->output()); `
> what data does the `$file` variable hold?

something like 'somefolder/somepath/filename.jpg'

**Comment by elvis-chuks** [comment]
thanks!!

**Comment by audetcameron** [comment]
> > Hello there,
> > in your response you have `Storage::put($file, $pdf->output()); `
> > what data does the `$file` variable hold?
> 
> something like 'somefolder/somepath/filename.jpg'
> 
> Example from Storage:: docs
> ![image](https://user-images.githubusercontent.com/6738453/104034876-746ecb00-519f-11eb-87d7-261247b8ef8a.png)

please note that if you are using the Request facade and want to bypass local storage, use putFile / putFileAs
https://laravel.com/docs/8.x/filesystem#automatic-streaming
