### ISSUE TITLE
How to save PDF on Amazon S3

### ISSUE THREAD

**Issue by dalcero** [barryvdh/laravel-snappy#196]
Hello. I need to save my files to Amazon S3 storage. How should I proceed?

**Comment by barryvdh** [comment]
See https://laravel.com/docs/5.4/filesystem#storing-files

**Comment by mcblum** [comment]
@barryvdh one quick followup to this -- does your save method accept the filesystem that we'd like to use to save it? We have S3 configured but it's not the default file system. Thanks for this awesome package - you make some really awesome stuff!

**Comment by abhijiy** [comment]
I want to upload a PDF file to s3 server.
