### ISSUE TITLE
The Process class relies on proc_open, which is not available on your PHP installation.

### ISSUE THREAD

**Issue by danjswade** [barryvdh/laravel-snappy#197]
I've had this message come up. I understand it's disabled on my shared hosting. Is there a workaround I can use to still generate the PDF without using proc_open?

**Comment by barryvdh** [comment]
Currently not.

**Comment by abhishek-pokhriyal** [comment]
@barryvdh A few years have passed...any solution now?

**Comment by barryvdh** [comment]
Yeah find better hosting ;)

But no. You can still use dompdf if you need PDF.

**Comment by abhishek-pokhriyal** [comment]
Yeah, it seems like I anyhow need to `proc_open` to run the `wkhtmltopdf` command.
