### ISSUE TITLE
Reset options between multiple calls

### ISSUE THREAD

**Issue by cdarken** [barryvdh/laravel-snappy#199]
I'm creating multiple PDFs in the same call. I'm setting different page sizes on each PDF and I tried to reset them using `setOptions([])` but it's not working. Any ideas?

Edit: Just saw the code of `setOptions()`. It doesn't reset anything, of course it won't work :)

**Comment by rubenflush** [comment]
I had this problem aswell. My current solution is to create your own PDFWrapper by rebinding the facade and resetting options on every PDF generation.

**Rebinding the wrapper**

```php
/* AppServiceProvider.php */

//overwrite PDF class
if($this->app['config']->get('snappy.pdf.enabled')) {
    $this->app->alias('snappy.pdf.wrapper', 'Lib\PDF');
    $this->app->bind('snappy.pdf.wrapper', function($app) {
        return new \Lib\PDF($app['snappy.pdf']);
    });
}
```

**Reset default options on generate**

```php
/* Lib\PDF.php  */

public function loadHTML($string)
{
    $this->resetOptions();
    return parent::loadHTML(self::replaceLinks($string));
}

/**
 * Reset all options to it's default value to prevent data being shared between PDF's
 *
 * @return $this
 */
private function resetOptions()
{
    $snappy = $this->snappy();
    if(is_null($this->defaultOptions)) {
        //set default options to be able to check differences
        $this->defaultOptions = $snappy->getOptions();
    } else {
        //reset all changed options
        $currentOptions = $snappy->getOptions();
        foreach($this->defaultOptions as $name => $value) {
            //reset option to it's default value when changed (to prevent enormous logs)
            if($currentOptions[$name] != $value) {
                $snappy->setOption($name, $value);
            }
        }
    }

    return $this;
}
```

**Comment by alschnei529** [comment]
I have this issue too, but only when working with facades. Using the wrappers seems to prevent this issue.

using `$pdf = PDF::loadView('pdf.invoice', $data);` seems to reference an existing instance
using `$pdf = App::make('snappy.pdf.wrapper');` seems to load a fresh instance

just gunna reiterate the same thing but in a code example
```php
$pdf1 = PDF::loadView('pdf.invoice', $data)->setOption('zoom', 1);
// zoom of pdf1 is 1

$pdf2 = PDF::loadView('pdf.invoice', $data)->setOption('zoom', 2);
// zoom of BOTH pdf1 and pdf2 are set to 2

$pdf3 = App::make('snappy.pdf.wrapper')->setOption('zoom', 1);
// zoom of pdf3 is 1

$pdf4 = App::make('snappy.pdf.wrapper')->setOption('zoom', 2);
// zoom of pdf4 is 2, but zoom of pdf3 still 1
```


I'm not sure sure if this is a bug, or intended? I thought the wrapper and facade were supposed to work interchangeably, so I'm leaning towards bug... but could be wrong.

**Comment by johnwilhite** [comment]
Resolving the PdfWrapper directly, instead of using the facade, has fixed the issue for me:
```
$pdfWrapper = resolve(\Barryvdh\Snappy\PdfWrapper::class);
$pdf = $pdfWrapper->loadView('view.name');
$pdf->setOption('page-size', 'letter');
```
