### ISSUE TITLE
Set page break

### ISSUE THREAD

**Issue by closca** [barryvdh/laravel-snappy#2]
How can i force page break?

**Comment by rcamposp** [comment]
I've tried every single way suggested and only the one posted by @barryvdh worked for me. Thanks!

**Comment by mtpultz** [comment]
This isn't working for me.  Adding the below markup and including the styles above I get all of these on a single page.

<div class="page">
    page 1
</div>
<div class="page">
    page 2
</div>
<div class="page">
    page 3
</div>
<div class="page">
    page 4
</div>

**Comment by mtpultz** [comment]
Never mind I had to remove `media="print"`

**Comment by brunoneve** [comment]
Works for me..

<style type="text/css">
    .page {
        overflow: hidden;
        page-break-after: always;
    }
    .page:last-of-type {
        page-break-after: auto
    }
</style>

**Comment by abhishek-ejam** [comment]
Just a note that page breaks do not work inside absolutely positioned elements or elements with a display value of `inline, inline-block, inline-table, table-column, table-column-group, table-header-group, table-footer-group, table-row, or table-cell`.
