### ISSUE TITLE
Class not found on laravel version 5.4

### ISSUE THREAD

**Issue by 123bistami** [barryvdh/laravel-snappy#200]
Hello,

I try everything but get everytime error class not found, on facades and on Serviceprovider, if i run command vendor: publish get error Serviceprovider not found, i do everything loke doc, add package to composer. json require it but not working, after i install the snappy package on laravel version 5.1 and its work, seems that laravel changes how it load providers and facdes. Pls help.

**Comment by larryu** [comment]
@123bistami could you give us the detail error message? Because I also use laravel 5.4, I haven't met any problem when running vendor:publish command.

**Comment by 123bistami** [comment]
I delete package between, error is e.g. Barryvidth\..\class not found are in L5 global vars so they cant find the class i do composer dump-autoload added facade path Serviceprovider path i got this error many times so i dont think its package error but i dont now why i get this error, in L5.1 is everything fine i change in .env file localhost to localhost:8000 and back nothing helps
