### ISSUE TITLE
Cannot execute binary file

### ISSUE THREAD

**Issue by nam-co** [barryvdh/laravel-snappy#205]
Hi Barry, thank you for the package, I know you have received many 126, but please help me, Im getting this on my Mac (using Mamp pro):
RuntimeException
The exit status code '126' says something went wrong:
stderr: "sh: /Users/xx/Dropbox/PROJECTS/xx/L5_4/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64: cannot execute binary file

I install "h4cc/wkhtmltopdf-amd64": "0.12.x" inside the laravel vendor project, 
in the config I have: 'binary' => base_path('vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64'),
And on the Controller I have: 
$pdf = \PDF::loadView('pdf.basic', ['biz' => $biz,'client' => $client]);
return $pdf->download('thefile.pdf');
I tried: chmod +x /Users/xx/Dropbox/PROJECTS/xx/L5_4/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64 

Appreciate any help from anyone

**Comment by nam-co** [comment]
Fix it by installing directly on forge and then using sudo apt-get install libxrender1

**Comment by veed76** [comment]
Hi @nam-co 
I getting same error, I have mac, I tried this command: `sudo apt-get install libxrender1` but it display this `sudo: apt-get: command not found` please help me with this.

Thank You.
