### ISSUE TITLE
snappy.php config not being read

### ISSUE THREAD

**Issue by signet-planet** [barryvdh/laravel-snappy#206]
Having troubles getting it to see the options set in config/snappy.php

After installing with composer I ran

```php
php artisan vendor:publish --provider="Barryvdh\Snappy\ServiceProvider"
```

And that showed it copied the config file over to config/snappy.php. However if I edit that file, it doesn't actually seem to be reading regardless. I moved the binaries to where it thinks they should be so it runs but it means I have to pass options to each object manually. 

I've got in config/app.php this as an Application Service Provider
Barryvdh\Snappy\ServiceProvider::class,

And this as a class alias.
'PDF' => Barryvdh\Snappy\Facades\SnappyPdf::class,
'SnappyImage' => Barryvdh\Snappy\Facades\SnappyImage::class,

In my config/snappy.php I have in both pdf and image I have options set to:

```php
<?php
   'options' => array(
            'disable-external-links' => true,
            'toc' => true,
            'enable-local-file-access' => true,
            'enable-internal-links' => true
   ),
```

I then call the class using a facade to PDF

```php
return \PDF::loadView('survey')->inline();
```

If I use:

```php
return \PDF::loadView('survey')
    ->setOption('disable-external-links' ,true)
    ->setOption('toc' , true)
    ->setOption('enable-local-file-access', true)
    ->setOption('enable-internal-links' , true)
    ->inline();
```

Then the pdf has the options set, but I'd like to get the config file going so I don't have to define those options each time.  I'm wondering if this is a namespace issue I'm not seeing or is it simply a bug with Laravel 5.4.25

**Comment by signet-planet** [comment]
Everything I see suggests this should work so I pushed it to a production server just out of curiosity and it works perfectly there.  So this is not an issue with your package.

I ran an apt-get update/upgrade on my vagrant homestead box to get wkhtmltopdf to install properly and since then php is apparently (while running on linux) no longer case sensitive. So I can get 'test' === 'Test' to pass and if I have a variable $test I can access it via $teSt $TEST or anyway I want. Time to dump this box and rebuild it again from scratch I think...sigh...

**Comment by Javier-Solis** [comment]
for anyone else just try clear all the cache stuff particularly the config cache

php artisan view:clear
php artisan route:clear
php artisan cache:clear
php artisan config:clear
php artisan clear-complied
composer dump-autoload
php artisan vendor:publish
