### ISSUE TITLE
wkhtmltopdf: cannot connect to X server

### ISSUE THREAD

**Issue by 17421932** [barryvdh/laravel-snappy#210]
RuntimeException in AbstractGenerator.php line 336:
The exit status code '1' says something went wrong:
stderr: "wkhtmltopdf: cannot connect to X server 
"
stdout: ""
command: /usr/bin/wkhtmltopdf --lowquality 'http://rcpq.net/admin/pdf/1' '/tmp/knp_snappy59545cf9070c97.38917981.pdf'.

how to deal this in center OS 7,

**Comment by gholami-mohammad** [comment]
Try reinstall wkhtmltopdf stable version from binary file.
I have the same problem, remove wkhtmltopdf and install latest stable version [https://wkhtmltopdf.org/downloads.html](url).
Install dependencies before install.
It depends on: zlib, fontconfig, freetype, X11 libs (libX11, libXext, libXrender)
