### ISSUE TITLE
Generate only the first page in PDF

### ISSUE THREAD

**Issue by sonoftheweb** [barryvdh/laravel-snappy#215]
This is the bit of code I am using

`$cert = \PDF::loadView('pdf.certificate',$data);

        $filename = str_random(5).'_certificate.pdf';
        $certFile = public_path('collection-files/'.$collection_id.'/'.$filename);

        $cert->setPaper($paper_size)
            ->setOrientation($paper_orientation)
            ->setOption('margin-top', 0)
            ->setOption('margin-left', 0)
            ->setOption('margin-bottom', 0)
            ->setOption('margin-right', 0)
            ->setOption('page-width', $page_width)
            ->setOption('page-height', $page_height)
            ->save($certFile);`

I however would like to save just the first page of the generated file. Are there ways to do this?

**Comment by jakenoble** [comment]
Any news on this?

**Comment by ErickTucto** [comment]
any news on this ?
