### ISSUE TITLE
How to solve diff between development environment and production environment

### ISSUE THREAD

**Issue by Minotti** [barryvdh/laravel-snappy#216]
I've been facing a very common problem among developers. In my development environment PDF is generated normally on both the async and redis drivers. However, within the production environment the fonts becomes very large when using redis driver. It "breaks" the layout and does not change at all.

What should I do to solve this problem? Would Docker be a solution?

I'm not finding nice solutions let alone getting close to a solution.

Please help me.

**Comment by barryvdh** [comment]
perhaps the font is not installed on your system?

**Comment by Minotti** [comment]
Which font needs to be installed? I installed xfonts-75dpi and xfonts-base

**Comment by Minotti** [comment]
Well ... for now I have changed some properties of css and it is almost as I expected .. I will leave so for now. Thank you.
