### ISSUE TITLE
SSL resources not loading

### ISSUE THREAD

**Issue by khanof89** [barryvdh/laravel-snappy#217]
I am trying to load a view which generates charts and bars using google charts library, because the chart library is hosted on google server with an SSL, I get the following error : 

 

> (1/1) RuntimeException
> 
> The exit status code '1' says something went wrong:
> stderr: "Loading pages (1/6)
> [> ] 0%
> [======> ] 10%
> QSslSocket: cannot resolve CRYPTO_num_locks
> QSslSocket: cannot resolve CRYPTO_set_id_callback
> QSslSocket: cannot resolve CRYPTO_set_locking_callback
> QSslSocket: cannot resolve sk_free
> QSslSocket: cannot resolve sk_num
> QSslSocket: cannot resolve sk_pop_free
> QSslSocket: cannot resolve sk_value
> QSslSocket: cannot resolve SSL_library_init
> QSslSocket: cannot resolve SSL_load_error_strings
> QSslSocket: cannot resolve SSLv3_client_method
> QSslSocket: cannot resolve SSLv23_client_method
> QSslSocket: cannot resolve SSLv3_server_method
> QSslSocket: cannot resolve SSLv23_server_method
> QSslSocket: cannot resolve X509_STORE_CTX_get_chain
> QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
> QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
> QSslSocket: cannot resolve SSLeay
> QSslSocket: cannot call unresolved function CRYPTO_num_locks
> QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
> QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
> QSslSocket: cannot call unresolved function SSL_library_init
> QSslSocket: cannot call unresolved function SSLv23_client_method
> QSslSocket: cannot call unresolved function sk_num
> [===============> ] 25%
> [=====================> ] 36%
> [=========================> ] 43%
> QSslSocket: cannot call unresolved function SSLv23_client_method
> QSslSocket: cannot call unresolved function SSL_library_init
> Warning: Failed to load https://www.gstatic.com/charts/45.2/loader.js (ignore)
> [============================================================] 100%
> Counting pages (2/6)
> [============================================================] Object 1 of 1
> Resolving links (4/6)
> [============================================================] Object 1 of 1
> Loading headers and footers (5/6)
> Printing pages (6/6)
> [> ] Preparing
> [===================> ] Page 1 of 3
> [=======================================> ] Page 2 of 3
> [============================================================] Page 3 of 3
> Done
> Exit with code 1 due to network error: ContentNotFoundError
> QSslSocket: cannot call unresolved function CRYPTO_num_locks
> QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
> QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
> "
> stdout: ""
> command: /usr/local/bin/wkhtmltopdf-amd64 --lowquality '/tmp/knp_snappy59719aad573823.86128540.html' '/tmp/knp_snappy59719aad573c74.43593591.pdf'.

Just so you know, following is my code which I have tried 

```
//return view('pdf.reports', compact('merged', 'request', 'marketplaces', 'brands', 'title', 'type'));
        //$pdf = App::make('snappy.pdf');
        return SnappyPdf::loadView('pdf.reports', ['merged' => $merged, 'request' => $request, 'marketplaces' => $marketplaces, 'brands' => $brands, 'title' => $title, 'type' => $title])->inline('page.pdf');
        //$pdf = SnappyPdf::loadView('pdf.reports', compact('merged', 'request', 'marketplaces', 'brands', 'title', 'type'));
        //return $pdf->download();
```

and the error is because of SSL is my wild guess, I just tried to load a simple view which also didnt work

**Comment by siddharthghedia** [comment]
@khanof89 I'm facing the same issue, please let me know if you find any solution for this.

**Comment by khanof89** [comment]
@siddharthghedia no solutions so far, google charts doesn't work locally and it is their TOS also that you cannot use it locally, and wkhtmltopdf doesn't handle ssl properly

**Comment by siddharthghedia** [comment]
@khanof89 I guess problem is not with SSL, I just tried removing the SSL, and is still showing the same error :(

**Comment by siddharthghedia** [comment]
@khanof89 ssl is the problem yeah :D :D , was working when removed ssl, when added back, its not working :(

**Comment by nonsocode** [comment]
I found a solution that works. checkout  [@Kaicastledine's](https://github.com/Kaicastledine) solution on  [this thread](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3001)

Summary

Downgrade libssl
`apt install libssl-dev=1.0.2g-1ubuntu4.8`

Lock it from future upgrades
`apt-mark hold libssl-dev`

**Comment by Sunyuzhu** [comment]
@nonsocode Thanks very much!!!

**Comment by roni-estein** [comment]
The downgrade libs change, right now it's 4.10 not 4.8, look here for the current version for you.
https://packages.ubuntu.com/xenial/libssl1.0.0

**Comment by esobolev** [comment]
For Ubuntu 17.10:

apt install libssl-dev=1.0.2g-1ubuntu13.3

**Comment by leemarkwood** [comment]
On Ubuntu 17.10 I used the following package to fix this issue.

apt-get install libssl1.0-dev

**Comment by vnetmx** [comment]
14.04 = apt install libssl-dev=1.0.1f-1ubuntu2.25 (Tested and worked)
18.04 = apt install libssl-dev=1.0.2n-1ubuntu5 (Not tested) @bluemountainteam

**Comment by icaroscherma** [comment]
@vnetmx 
Tried in Ubuntu 18.04 Linux AMI (AWS)
```
sudo apt install libssl-dev=1.0.2n-1ubuntu5
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Version '1.0.2n-1ubuntu5' for 'libssl-dev' was not found
```

**Comment by vnetmx** [comment]
@icaroscherma 

Try this:
sudo apt install libssl1.0-dev=1.0.2n-1ubuntu5

**Comment by FelipeeDev** [comment]
@vnetmx 

`sudo apt install libssl1.0-dev=1.0.2n-1ubuntu5`

Works on Ubuntu 18.04. Thx a lot!

**Comment by barryvdh** [comment]
Yeah but I'm not sure that is the best way, as you're actually downgrading lib ssl, right?

**Comment by vnetmx** [comment]
@barryvdh I think we are only installing Development Files, not downgrading lib. But this is only a workaround, maybe we need a fix to work with newer versions.

**Comment by nam-co** [comment]
Hi @barryvdh , I understand its not a problem of you're package, but a problem with new versions of Ubuntu, anyway as you can see here https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3001#issuecomment-396815585 the issue was resolved (much better than downgrading) , but the composer package maintainer hasn't updated to the new version (0.12.5), is there any way to use another package or fork?

Appreciate any help

**Comment by barryvdh** [comment]
See https://github.com/h4cc/wkhtmltopdf-amd64/issues/31
You are free to fork or install it yourself, I don't maintain wkhtmltopdf of the composer binaries.

But glad it's solved with the latest version :)

**Comment by mariapaulinar** [comment]
Ubuntu 18.04.1:

`sudo apt-get install libssl1.0-dev`

https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3001

**Comment by Brokan** [comment]
Upgdaring wkhtmltopdf to **0.12.5** solve SSL problem.

**Comment by AugmentBLU** [comment]
I have the same issue. Using Ubuntu 18.04. I installed wkhtmltopdf to 0.12.5 and still have the same issues.

What is a safe way to fix this, without downgrading SSL libs?

**Comment by ajcastro** [comment]
In my case I fixed it by not using https when rendering in snappy... like
```
{{ request()->boolean('use_snappy') ? 'http' : 'https' }}://some-url.com/assets/style.css
```

**Comment by dwijonarko** [comment]
update wkhtmltopdf to version 0.12.6 fixed this error

**Comment by casperwitting** [comment]
> update wkhtmltopdf to version 0.12.6 fixed this error

This version doesn't exist? 0.12.4 is the latest -> https://github.com/h4cc/wkhtmltopdf-amd64/tags

**Comment by barryvdh** [comment]
Not as composer package; https://github.com/h4cc/wkhtmltopdf-amd64/pull/44
I suggest you download the binary directly: https://wkhtmltopdf.org/downloads.html

**Comment by barryvdh** [comment]
Forge recipe to install:

```
echo ">> Installing WkhtmltoPDF 0.12.6"
wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.focal_amd64.deb
sudo dpkg -i wkhtmltox_0.12.6-1.focal_amd64.deb
sudo apt-get --yes -f install
sudo cp /usr/local/bin/wkhtmlto* /usr/bin/
```

**Comment by casperwitting** [comment]
Thanks @barryvdh, this worked for me! I added wkhtmltopdf as dependency to my docker configuration and pointed the`WKHTMLTOPDF_PATH` value to it.

**Comment by ismailansari** [comment]
Well I found a hack for this in Laravel  I did like the following and it worked 
`<img class="w100" editable="" mc:edit="mm-92" label="image"  src="data:image/jpeg;base64,{{ \base64_encode(@file_get_contents($booking_detail['hotel_picture'])) }}">`

**Comment by wisquimas** [comment]
> I have the same issue. Using Ubuntu 18.04. I installed wkhtmltopdf to 0.12.5 and still have the same issues.
> 
> What is a safe way to fix this, without downgrading SSL libs?

Have you been able to solve the problem?

For me @barryvdh solutions is not working

**Comment by itzmj-23** [comment]
My fix:

Installed wkhtmltopdf on my server
`sudo apt update`
`sudo apt install wkhtmltopdf`

After successful installation, I find the wkhtmltopdf and create a symlink
`find / -name wkhtmltopdf`
`ln -s /usr/bin/wkhtmltopdf /usr/local/bin/whtmltopdf-amd64`

For me, this is the fix for my encountered errors such as 'ssl resources not loading, error 127, libssl error, and many more'
I think it is case to case basis depends on the environment and versions of platforms. Thanks.

My Platform Details:
- Ubuntu 22.04
- Laravel Forge on DigitalOcean
- Laravel 9 
- PHP 8.1
