### ISSUE TITLE
Problem to download/save PDF with assets

### ISSUE THREAD

**Issue by mdeorue** [barryvdh/laravel-snappy#222]
Hi guys,

I got a problem when I want to download a PDF from view.

When I remove the assets its works fine, but when I use them I got this error... 
`he exit status code '1' says something went wrong:
stderr: "Loading pages (1/6)
[> ] 0%
[======> ] 10%
QSslSocket: cannot resolve CRYPTO_num_locks
QSslSocket: cannot resolve CRYPTO_set_id_callback
QSslSocket: cannot resolve CRYPTO_set_locking_callback
QSslSocket: cannot resolve sk_free
QSslSocket: cannot resolve sk_num
QSslSocket: cannot resolve sk_pop_free
QSslSocket: cannot resolve sk_value
QSslSocket: cannot resolve SSL_library_init
QSslSocket: cannot resolve SSL_load_error_strings
QSslSocket: cannot resolve SSLv3_client_method
QSslSocket: cannot resolve SSLv23_client_method
QSslSocket: cannot resolve SSLv3_server_method
QSslSocket: cannot resolve SSLv23_server_method
QSslSocket: cannot resolve X509_STORE_CTX_get_chain
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
QSslSocket: cannot resolve SSLeay
QSslSocket: cannot call unresolved function CRYPTO_num_locks
QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
QSslSocket: cannot call unresolved function SSL_library_init
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function sk_num
[==========> ] 18%
[===============> ] 25%
[==================> ] 31%
[======================> ] 38%
[=========================> ] 43%
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function SSL_library_init
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function SSL_library_init
[============================================================] 100%
Counting pages (2/6) 
[============================================================] Object 1 of 1
Resolving links (4/6) 
[============================================================] Object 1 of 1
Loading headers and footers (5/6) 
Printing pages (6/6)
[> ] Preparing
[==============================> ] Page 1 of 2
[============================================================] Page 2 of 2
Done 
Exit with code 1 due to network error: UnknownNetworkError
QSslSocket: cannot call unresolved function CRYPTO_num_locks
QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
"
stdout: ""
command: /usr/local/bin/wkhtmltopdf-amd64 --lowquality --page-size 'letter' --enable-javascript --javascript-delay '4000' --viewport-size '1366x1024' '/tmp/knp_snappy5991c1b4cb1a41.29456871.html' '/tmp/knp_snappy5991c1b4cb2446.10870121.pdf'.`

I have two assets (css and js).
`<link rel="stylesheet" href="{{ url('/').mix('css/pdf.css') }}">`
and
`<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.min.js"></script>
`
The view render without problem.

Can you help me pls, this problem repeats in Homestead (Windows) and Forge (Ubuntu Server).

Regards.

**Comment by mdeorue** [comment]
This is the Controller instance...

```
$invoiceFile = 'invoice_filename.pdf';
$pdf = \PDF::loadHTML($view->render())
            ->setOption('viewport-size', '1366x1024')
            ->setOption('enable-javascript', true)
            ->setOption('javascript-delay', 4000)
            ->setPaper('letter');
$pdf->download($invoiceFile);
```

**Comment by parth999** [comment]
Remove "https" from all the resources
`<script src="http://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.min.js"></script>`

**Comment by Benjyclay** [comment]
This might help - https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3001

**Comment by j88per** [comment]
thanks, I moved on and found a different solution that didn't require snappy/wkhtmltopdf.

**Comment by nam-co** [comment]
Hi @ghost, what solution did you use instead? thanks

**Comment by sergomet** [comment]
Worked for me: apt-get install libssl1.0-dev

**Comment by msd1810** [comment]
> Worked for me: apt-get install libssl1.0-dev

thanks a lot its working for me

**Comment by carlosevieira** [comment]
> Worked for me: apt-get install libssl1.0-dev

Cool, worked for me <3

**Comment by nishh06** [comment]
> Worked for me: apt-get install libssl1.0-dev

Excellent.. Thank You.. Worked for me..

**Comment by johnathansantos** [comment]
Worked for me: `apt-get install libssl1.0.0`

**Comment by harryperz** [comment]
> > Worked for me: apt-get install libssl1.0-dev
> 
> thanks a lot its working for me

Great solution!!!

**Comment by sensoeurn** [comment]
Thanks @sergomet It works for me

**Comment by xyzdddd** [comment]
Thanks @bibhash it works for me, to use cmd apt-get install libssl1.0-dev.

**Comment by TheFrankman** [comment]
This issue occurs still on Ubuntu 20.04.1 (homestead latest) there is no longer a candidate for libssl1.0-dev

I'm still trying to resolve this myself, but not getting very far :(

**Comment by kamelher** [comment]
This issue occurs On Ubuntu 20.10; Is there any Solution ?

**Comment by nchatzidakis** [comment]
I fixed the problem in Ubuntu 20 by installing wkhtmltopdf manually, check this article for instructions 
https://computingforgeeks.com/install-wkhtmltopdf-on-ubuntu-debian-linux/

**Comment by omarjavierr277** [comment]
Este problema todavía me sigue causando error en el ubuntu 20

inatale pero no es la solucion:  apt-get install libssl-dev 

Hay alguna solución que les aya funcionado ?? 


The exit status code '1' says something went wrong:\nstderr: \"Loading pages (1/6)\n[>                                                           ] 0%\r[======>                                                     ] 10%\rQSslSocket: cannot resolve CRYPTO_num_locks\nQSslSocket: cannot resolve CRYPTO_set_id_callback\nQSslSocket: cannot resolve CRYPTO_set_locking_callback\nQSslSocket: cannot resolve sk_free\nQSslSocket: cannot resolve sk_num\nQSslSocket: cannot resolve sk_pop_free\nQSslSocket: cannot resolve sk_value\nQSslSocket: cannot resolve SSL_library_init\nQSslSocket: cannot resolve SSL_load_error_strings\nQSslSocket: cannot resolve SSLv3_client_method\nQSslSocket: cannot resolve SSLv23_client_method\nQSslSocket: cannot resolve SSLv3_server_method\nQSslSocket: cannot resolve SSLv23_server_method\nQSslSocket: cannot resolve X509_STORE_CTX_get_chain\nQSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf\nQSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf\nQSslSocket: cannot resolve SSLeay\nQSslSocket: cannot call unresolved function CRYPTO_num_locks\nQSslSocket: cannot call unresolved function CRYPTO_set_id_callback\nQSslSocket: cannot call unresolved function CRYPTO_set_locking_callback\nQSslSocket: cannot call unresolved function SSL_library_init\nQSslSocket: cannot call unresolved function SSLv23_client_method\nQSslSocket: cannot call unresolved function sk_num\n

**Comment by sensoeurn** [comment]
Make sure your view/html page without error (missing assets such as image, font, css, js or incorrect tag). Fix it first before load into snappy pdf.

**Comment by itzmj-23** [comment]
My fix:

Installed wkhtmltopdf on my server
`sudo apt update`
`sudo apt install wkhtmltopdf`

After successful installation, I find the wkhtmltopdf and create a symlink
`find / -name wkhtmltopdf`
`ln -s /usr/bin/wkhtmltopdf /usr/local/bin/whtmltopdf-amd64`

For me, this is the fix for my encountered errors such as 'ssl resources not loading, error 127, libssl error, and many more'
I think it is case to case basis depends on the environment and versions of platforms. Thanks.

My Platform Details:
- Ubuntu 22.04
- Laravel Forge on DigitalOcean
- Laravel 9 
- PHP 8.1

**Comment by juni-core** [comment]
Thanks you

**Comment by alessiogori** [comment]
> sudo apt install wkhtmltopdf

This worked. Thank you!

**Comment by molzieyy** [comment]
I am running Ubuntu I did this:
My fix:

then, change the config/snappy.php like this:
'binary' => 'wkhtmltopdf',


> My fix:
> 
> Installed wkhtmltopdf on my server `sudo apt update` `sudo apt install wkhtmltopdf`
> 
> After successful installation, I find the wkhtmltopdf and create a symlink `find / -name wkhtmltopdf` `ln -s /usr/bin/wkhtmltopdf /usr/local/bin/whtmltopdf-amd64`
> 
> For me, this is the fix for my encountered errors such as 'ssl resources not loading, error 127, libssl error, and many more' I think it is case to case basis depends on the environment and versions of platforms. Thanks.
> 
> My Platform Details:
> 
>     * Ubuntu 22.04
> 
>     * Laravel Forge on DigitalOcean
> 
>     * Laravel 9
> 
>     * PHP 8.1

Then then, change the config/snappy.php like this:
'binary' => 'wkhtmltopdf',

**Comment by sibabale** [comment]
> My fix:
> 
> Installed wkhtmltopdf on my server `sudo apt update` `sudo apt install wkhtmltopdf`
> 
> After successful installation, I find the wkhtmltopdf and create a symlink `find / -name wkhtmltopdf` `ln -s /usr/bin/wkhtmltopdf /usr/local/bin/whtmltopdf-amd64`
> 
> For me, this is the fix for my encountered errors such as 'ssl resources not loading, error 127, libssl error, and many more' I think it is case to case basis depends on the environment and versions of platforms. Thanks.
> 
> My Platform Details:
> 
> * Ubuntu 22.04
> * Laravel Forge on DigitalOcean
> * Laravel 9
> * PHP 8.1

How did anyone run these scripts on Forge?
