### ISSUE TITLE
Difference between snappy and dompdf ?

### ISSUE THREAD

**Issue by damosse31** [barryvdh/laravel-snappy#226]
Hi !

maybe a stupid question... but I don't find the differences between [laravel-dompdf](https://github.com/barryvdh/laravel-dompdf) and [laravel-snappy](https://github.com/barryvdh/laravel-snappy).

Both can create PDF from view, from raw HTML etc...

Wich package is recommanded to create invoice from blade view ?

Regards

**Comment by vlamirc** [comment]
Hi @damosse31. Maybe #74 answer part of your question.

**Comment by barryvdh** [comment]
Snappy uses wkhtmltopdf, a binary file using Webkit to render the page.
Dompdf uses php to render the page.

Use dompdf for simple pages, table based layouts (invoices etc), snappy for complicated HTML.

**Comment by raducruceana** [comment]
Hello barryvdh, I have used dompdf Laravel facade with succes to render documents of 3-4 pages with tables in it, it takes around 2 to 4 minutes to render them. Only one question, is laravel-snappy faster than DomPDF? Thank you for attention and for such a great interface!

**Comment by prllxtchz** [comment]
Yes definitely. There is huge performance difference. I switched from dompdf to snappy and now rapidly generating PDFs.

**Comment by stevebauman** [comment]
@raducruceana There is a large performance difference. DomPDF will always be slower than wkhtmltopdf (with its current implementation).

**Comment by Fionajeremychik** [comment]
Hello barryvdh, 

I found the problem for dompdf Laravel which cannot save pdf file to the directory inside window platform.
$path = storage_path('\pdf\')
$fileName = 'abc.pdf'
$pdf->save($path.filename);
