### ISSUE TITLE
[REQUEST][HELP] Shared Hosting (GoDaddy)

### ISSUE THREAD

**Issue by sinandomeng** [barryvdh/laravel-snappy#232]
Hi devs, I'm new to laravel including snappy. On my windows machine where I installed locally wkhtmltopdf, I can convert and download HTML to PDF on my site localhost. But on the live server, it gives me an error of 127 exit code. What cause this? Can you give me a clue how to set it up in GoDaddy. :(

I have this on my LOCAL config/snappy.php (Localhost)
```php
'binary'  => '"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf"',
```

I have this on my SERVER config/snappy.php (GoDaddy)
```php
'binary'  => '/usr/local/bin/wkhtmltopdf',
```

Please help. :( I found the same thread also [#94](https://github.com/barryvdh/laravel-snappy/issues/94)

**Comment by anishdcruz** [comment]
@jpellissari you need to install x-server in NON-GUI machine.

https://stackoverflow.com/questions/9604625/wkhtmltopdf-cannot-connect-to-x-server

**Comment by eclipsebeat** [comment]
Install the binary version from the https://github.com/KnpLabs/snappy#wkhtmltopdf-binary-as-composer-dependencies. then upload vendor folder to your hosting, dont forget to make the binary executables.

after that change the config to the binary location at the vendor folder.
