### ISSUE TITLE
Cannot Change Font Size

### ISSUE THREAD

**Issue by adriangordon1231** [barryvdh/laravel-snappy#235]
For some reason, I am not able to change the font size for any of the text in my pdf. In fact, what I am noticing is that any style that is being defined in pixels (px) is not working. Has anyone experienced a similar issue?

`
#presentation-title{
            color: white !important;
            display: inline-block;
            font-size: 53px !important;
            position: relative !important;
            font-weight: bold !important;
            top: 159px !important;
            left: 150px !important;
            width: 60% !important;
        }
`

**Comment by adriangordon1231** [comment]
I am now noticing that if I switch to using inches 'in' it works!

**Comment by desarrolladorsingh** [comment]
Cuando genero imagen no se me cargan los fuentes de estilo de texto a la hora de generar la imagen, pero si solo veo la plantilla antes de mandarlo a generar la imagen si se me cargan las fuentes de estilo de texto.


        @font-face{
        font-family: "hind-bold"; 
        src: url("{{ asset('public/fonts/Hind/Hind-Bold.ttf') }}") format('truetype');
        font-style: normal;
        } 
        
        
        .nombre{
            position: absolute;
            color: white;
            font-size: 25pt;
            margin: 105px 0px 0px 380px ;
            font-family: "hind-bold"  !important;
        }
