### ISSUE TITLE
I updated the latest version, I got this exception.

### ISSUE THREAD

**Issue by semsphy** [barryvdh/laravel-snappy#236]
```
ErrorException: var_export does not handle circular references 
vendor/knplabs/knp-snappy/src/Knp/Snappy/AbstractGenerator.php:117
```
**Note**: `knp snappy` was updated from v0.5.0 to v1.0.1.

**Comment by barryvdh** [comment]
See https://github.com/KnpLabs/snappy/issues/274

**Comment by barryvdh** [comment]
Can you check with https://github.com/barryvdh/laravel-snappy/commit/6904ebb784ffd696c2bceec23e70457787fc5754
