### ISSUE TITLE
Images hosted in AWS BUCKET is not showing

### ISSUE THREAD

**Issue by danilosantosdev** [barryvdh/laravel-snappy#240]
Hi guys,

I'm having a problem to show images that are hosted in a AWS BUCKET.

In my local environment, it's working right, but when i deploy my application to AWS Server, not work.

*Local Environment*
![local](https://user-images.githubusercontent.com/2335679/31791130-1595a3ac-b4ee-11e7-924e-c6de359c9422.png)

*Production Environment*
![production](https://user-images.githubusercontent.com/2335679/31791174-2abe3a6e-b4ee-11e7-9cf0-2bb8bb565de4.png)

As you can see, the second image in the second print, don't show.

How can i fix it?
Thanks!

**Comment by danilosantosdev** [comment]
@barryvdh or someone can help me please?

**Comment by edbizarro** [comment]
have the same issue

**Comment by danilosantosdev** [comment]
@edbizarro I don't find a solution to this issue.

But to solve this situation, before print the report, i download all the images to the application (to the public directory) and later show the report based on it.

**Comment by edbizarro** [comment]
@danilosantosdev I solved in a similar way, downloading the images and convert to `base64` to include in the `src`

**Comment by danilosantosdev** [comment]
@edbizarro very good.

**Comment by blogui91** [comment]
I followed [this tutorial](https://codingexplained.com/dev-ops/installing-wkhtmltopdf-on-ubuntu-14-04-and-16-04) and I could make it work
