### ISSUE TITLE
didn't work in Amazon Linux AMI release 2017.09

### ISSUE THREAD

**Issue by dhakalsuresh** [barryvdh/laravel-snappy#241]
I tried to install in my aws linux, but it's didn't work, it's shows me message below. 
`The exit status code '127' says something went wrong:
stderr: "/var/www/html/tikesh.com/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64: error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or directory
"
stdout: ""
command: /var/www/html/tikesh.com/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64 --lowquality 'http://www.github.com' '/tmp/knp_snappy59ec0e3d22bd63.37878050.pdf'.`
![capture](https://user-images.githubusercontent.com/8805646/31857937-38422e24-b715-11e7-8390-12496ef92c2f.PNG)

OS: `Amazon Linux AMI release 2017.09
Kernel \r on an \m`

**Comment by mirceabaicu** [comment]
Same here. Do you guys have any ideas what can be done to fix this ?
