### ISSUE TITLE
Laravel 5.5.4 composer update failed

### ISSUE THREAD

**Issue by mpixelz** [barryvdh/laravel-snappy#242]
Hi,
im on laravel 5.5.3 at the moment and this package is working.. but when i try composer update in order to update my laravel version as well as all other package.. im getting:
```
Problem 1
    - barryvdh/laravel-snappy dev-master requires knplabs/knp-snappy ^1 -> satisfiable by knplabs/knp-snappy[1.0.x-dev].
    - barryvdh/laravel-snappy dev-master requires knplabs/knp-snappy ^1 -> satisfiable by knplabs/knp-snappy[1.0.x-dev].
    - Conclusion: don't install knplabs/knp-snappy 1.0.x-dev
    - Installation request for barryvdh/laravel-snappy dev-master -> satisfiable by barryvdh/laravel-snappy[dev-master].
```
my composer.json :
```
        "h4cc/wkhtmltopdf-amd64": "0.12.x",
        "h4cc/wkhtmltoimage-amd64": "0.12.x",
        "knplabs/knp-snappy": "dev-master",
        "barryvdh/laravel-snappy": "dev-master",
```
please advice how to update them?
thanks.

**Comment by flexgrip** [comment]
Same issue. Laravel version 5.5.19 for me.

**Comment by flexgrip** [comment]
Actually no. I think your issue @mpixelz is that you are using dev-master. I just removed the dep, and used composer require again and I noticed it switched me to the 0.0.4 tag. Now I just need to test to make sure everything is working.
