### ISSUE TITLE
Deleting files in temporary directory.

### ISSUE THREAD

**Issue by akaamitgupta** [barryvdh/laravel-snappy#245]
We are using this library to generate PDFs in the **queue**.

The library is designed to delete all the tmp files after execution of the script. This is due to the following code in `Knp\Snappy\AbstractGenerator` class :

    public function __destruct()
    {
        $this->removeTemporaryFiles();
    }
Reference - https://github.com/KnpLabs/snappy/blob/master/src/Knp/Snappy/AbstractGenerator.php#L57

As we are using this inside a queue job and in Laravel once the `queue:work` command has started, it will continue to run until it is manually stopped or you close your terminal. 

So to clean the tmp files I have to restart the queue worker everytime.

Is there any alternative to this?

Note - The instance of class `Knp\Snappy\AbstractGenerator` inside the wrapper of laravel-snappy is `protected`. So I can't call its methods directly.

Reference - https://github.com/barryvdh/laravel-snappy/blob/master/src/PdfWrapper.php#L20

  [1]: https://github.com/barryvdh/laravel-snappy

**Comment by akaamitgupta** [comment]
@barryvdh any update on this.

**Comment by BARNZ** [comment]
I stumbled across this problem today. I found the `snappy()` function gives you what you need (although might have been added after you had logged this)

I ended up just using `$pdf->snappy()->removeTemporaryFiles()` at the end of my job which did the trick for me.

**Comment by akaamitgupta** [comment]
@BARNZ Thanks for informing, will check it soon.

**Comment by jochellemendonca** [comment]
Any update on this? Facing the same issue. Can't seem to get a workaround

**Comment by BARNZ** [comment]
Might wanna double check things on your end. It definitely does the trick for me.

Heres an example of what I'm using at the end of my job. Without the `removeTemporaryFiles` call the temp html files are left in my `storage/temp/reports` directory.

![image](https://user-images.githubusercontent.com/2202345/54351704-efa2eb00-46b4-11e9-8326-bf4ff15e2850.png)

**Comment by akaamitgupta** [comment]
@BARNZ This approach worked for me.

Closing the issue.

**Comment by Mr-Anonymous** [comment]
> Might wanna double check things on your end. It definitely does the trick for me.
> 
> Heres an example of what I'm using at the end of my job. Without the `removeTemporaryFiles` call the temp html files are left in my `storage/temp/reports` directory.
> 
> ![image](https://user-images.githubusercontent.com/2202345/54351704-efa2eb00-46b4-11e9-8326-bf4ff15e2850.png)

Thank you @BARNZ Your solution helps me a lot too.

Just 1 quick question though: Does `$snappy->removeTemporaryFiles()` deletes all tmp files in that directory or only the tmp files that was created for creating this particular PDF file?  

In my production site, I have parallel queue workers where different pdfs are created simultaneously. So wondering if this command will end up deleting even the other workers tmp files as well.

**Comment by ethanclevenger91** [comment]
@Mr-Anonymous Each worker would have a unique instance of the class, right? Each class maintains [its own array of temporary files](https://github.com/KnpLabs/snappy/blob/master/src/Knp/Snappy/AbstractGenerator.php#L27) (it doesn't just wipe the directory), so it should only delete temporary files created by that specific worker. Right?

**Comment by Mr-Anonymous** [comment]
@ethanclevenger91 You are right. I have been having this in my production server and it doesn't seem to be wiping the directory and concurrent processes seems to be going fine.
