### ISSUE TITLE
Shouldn't it be a factory, rather than singleton?

### ISSUE THREAD

**Issue by garygreen** [barryvdh/laravel-snappy#246]
Been scratching my head wondering why our PDFs are generating with previous set of options, and it's because this package only creates a singleton instance, which means you can't customise options on a per-pdf basis. For example:

**Creates a PDF with a header**

```php
Pdf::loadHTML('<p>PDF with header.</p>')
    ->setOption('header-html', 'My Header')
    ->save('header.pdf');
```

**Attempting to create a PDF without a header - still has the header because `Pdf` is a singleton, so it remembers the previous set option.**

```php

Pdf::loadHTML('<p>PDF without header.</p>')
    ->save('without-header.pdf');
```

You could reset the header with the second command, but what if you had loads of options and you wasn't sure what options were previously set - there isn't a `resetOptions()` of some kind.

Ideally shouldn't certain functions be `factory` / maker like?

**Comment by barryvdh** [comment]
Yeah guess so
