### ISSUE TITLE
Use wkhtmltopdf as portable without windows or linux installer

### ISSUE THREAD

**Issue by essivision** [barryvdh/laravel-snappy#249]
Hi,
I wanna to use `laravel-snappy` in my project, but my project may install on linux or windows platform. It's depends on customer server platform. Now I want to use wkhtmltopdf binary as composer or every portable way. I can use php function code for detect x64 or x86 customer server platform. 

In `laravel-snappy` manual there is my requirement: [https://github.com/KnpLabs/snappy#wkhtmltopdf-binary-as-composer-dependencies ](https://github.com/KnpLabs/snappy#wkhtmltopdf-binary-as-composer-dependencies)

I use 
```
$ composer require h4cc/wkhtmltopdf-i386 0.12.x
$ composer require h4cc/wkhtmltoimage-i386 0.12.x
```
and 
```
$ composer require h4cc/wkhtmltopdf-amd64 0.12.x
$ composer require h4cc/wkhtmltoimage-amd64 0.12.x
```
Every things is good after composer installation and files copied. When I change `Snappy.php` config like this:
```
'binary'  => '"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf"',
```
Everything is okay but I don't use it, because it's not portable. I want to use this format:
```
'binary'  => base_path('vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64'),
```
That's not work and error me:
```
The exit status code '1' says something went wrong: stderr: "'wkhtmltopdf-amd64' is not recognized as an internal or external command, operable program or batch file.
```

 My development system is Windows 10

What's your solutions?

Thanks

**Comment by Richol55486** [comment]
maybe you can't use that type file in window.
that file type is for linux or ubuntu.
it's right ?

**Comment by CopyJosh** [comment]
Yeah I'm having this same issue as well.. the instructions don't seem to hint that this is not a windows capable solution, which is a little misleading, but not surprising.

**Comment by oberoivarun** [comment]
I use docker and have incorporated it into my build process. The containers pull the libraries and set them up. It's portable enough. Try it.

**Comment by g3rryok** [comment]
i dont recomend you to use h4cc/wkhtmltopdf anymore, as they did not update that anymore (could bring SSL issue). Use stand alone wkhtmltopdf instead.
