### ISSUE TITLE
style media print

### ISSUE THREAD

**Issue by carlituxman** [barryvdh/laravel-snappy#25]
I possible (like your dompdf) force to use media="print" style to generate the pdf?

**Comment by shad0wfir3** [comment]
have u got this working yet? Im stuck trying to get a different style for display and print
```
@media print{
    body {
       font-size:10pt;
    }
}
```

**Comment by zardilior** [comment]
Does that work?

**Comment by Elidrake** [comment]
I was able to get this to work by using the setOption method, passing `('print-media-type', true)`.
