### ISSUE TITLE
how to use absolute css in laravel snappy

### ISSUE THREAD

**Issue by Richol55486** [barryvdh/laravel-snappy#251]
css absolute property working well on html.
![screenshot_1](https://user-images.githubusercontent.com/28510084/34264630-781a5468-e6ae-11e7-843f-1fcb5b249b13.png)
then when i convert to pdf with snappy that absolute property not working.
![screenshot_2](https://user-images.githubusercontent.com/28510084/34264678-a080badc-e6ae-11e7-9982-47e4bd8127d1.png)
please help me.
thank you

**Comment by Richol55486** [comment]
Just solved

**Comment by mohamad68** [comment]
@Webdev55486  how do you solve the problem ?
I use css-flex but it dose n't work in converted pdf

**Comment by Webdev55486** [comment]
for the absolute position.
i set css like below
top: calc( 50% - 34px )
left: calc ( 34% - 20px)
this css code working well in html.
but this is not working when convert to pdf.
so I just calculate that top and left position on the javascript and and set again.
with this solution that working well on pdf.
That's all

**Comment by mohamad68** [comment]
@Webdev55486  thank you for replay
