### ISSUE TITLE
Array to string conversion exception when generating PDF

### ISSUE THREAD

**Issue by iainheng** [barryvdh/laravel-snappy#252]
I encounter `Array to string conversion` ErrorException when trying to generate a PDF on my production server running CentOS. 

```php
$pdf->download(strtolower('file.pdf');
```

However, the same code run perfectly on my local development machine running Windows 10 with MAMP installation.

![image](https://user-images.githubusercontent.com/3263759/34342695-9962b24a-e9f2-11e7-9b10-1f418e2ba14a.png)

After spending few hours trying to figure out the issue and I found that the error comes from `$env` variable in vendor/symfony/process/Process.php
```php
$this->process = proc_open($commandline, $descriptors, $this->processPipes->pipes, $this->cwd, $env, $this->options);
```

I am able to print out the `$env` array when I  `dd()` the `$env` just before the line `$this->process = ...` 

![snip_201712260351592](https://user-images.githubusercontent.com/3263759/34342730-2e090150-e9f4-11e7-8a7d-994d238b7140.png)

I can bypass the exception if I purposely put some dummy data in env variable inside my config file `/laravel/config/snappy.php` or set `$env` to `null` in `$this->process = proc_open($commandline, $descriptors, $this->processPipes->pipes, $this->cwd, $env, $this->options)`

```php
'pdf' => array(
        'enabled' => true,
        'binary'  => env('SNAPPY_PDF_BINARY'),
        'timeout' => false,
        'options' => array(),
        'env'     => [
            'test' => 'test'
        ],
    ),
```

I can't figure out what's the real problem here and hope to get some helps here. 

Thanks.

**Comment by ostrolucky** [comment]
I believe it might be this issue https://github.com/symfony/symfony/pull/25559
