### ISSUE TITLE
Generating blank pdf trying to include images

### ISSUE THREAD

**Issue by SergioReis97** [barryvdh/laravel-snappy#256]
Trying to generate a pdf results in empty blank page when header or footer has images.
```
$header = View::make('pdf.report.header',$data);
$footer = View::make('pdf.report.footer',$data);
$pdf = SnappyPDF::loadView('pdf.report.view', $data);
      return $pdf->setPaper('a4')
        ->setOrientation('portrait')
        ->setOption('images', true)
        //->setOption('header-html', $header)
        ->setOption('footer-html', $footer)
        ->setOption('enable-javascript', true) //loading js for google chart
        ->setOption('javascript-delay', 1000)
        ->setOption('no-stop-slow-scripts', true)
        ->stream('invoice.pdf');
```
If footer is only normal html without images, the pdf loads as it should (Except image tags doesnt load but that seems to be a completly different issue), but if it has an img tag, pdf doesn't load pages.
Example: 
This loads 1 blank page.

```
<div style="display: inline-block;font-size: 12px;padding-left: 20px;width:40%;border:0">
 aaa <img src="/var/www/html/project/public/images/footer.png" height="30" alt="LOGO" /> bbb
</div>
```
This loads correctly
```
<div style="display: inline-block;font-size: 12px;padding-left: 20px;width:40%;border:0">
 aaa bbb
</div>
```
Tried using these as src for img tag:
/var/www/html/project/public/images/footer.png
 public_path('images/footer.png')
 URL::asset('/images/footer.png') 
 http://via.placeholder.com/350x150
 http://via.placeholder.com/350x150.png
 base64image ( sample from [this](https://codebeautify.org/base64-to-image-converter#) website )

Edit : Forgot system info

```
$ php -v
PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )

$ cat /etc/*release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=18.2

$ vendor/h4cc/wkhtmltopdf-i386/bin/wkhtmltopdf-i386 -V
wkhtmltopdf 0.12.4 (with patched qt)

$ vendor/h4cc/wkhtmltoimage-i386/bin/wkhtmltoimage-i386 -V
wkhtmltoimage 0.12.4 (with patched qt)

//composer.json
"require": {
        "barryvdh/laravel-snappy": "^0.4.0",
        "h4cc/wkhtmltoimage-i386": "0.12.4",
        "h4cc/wkhtmltopdf-i386": "0.12.4",
        "laravel/framework": "5.5.*",
```

**Comment by vaggelis2018** [comment]
@SergioReis97 Did you find any solution on this?

**Comment by SergioReis97** [comment]
Sadly no, ended up building a tool so i could save my javascript charts and not run javascript when building the pdf so i could use DOMPDF
