### ISSUE TITLE
Can't stream, download, or loadhtml

### ISSUE THREAD

**Issue by isatria** [barryvdh/laravel-snappy#257]
I get the following error message : 

> is_dir(): open_basedir restriction in effect. File(/tmp) is not within the allowed path(s):
in AbstractGenerator.php (line 401)

**Comment by SergioReis97** [comment]
Please say the system you're running, how you installed the package and some related configuration files

**Comment by isatria** [comment]
Problem solved.
I use debian 7.
The problem occurs because the system can not create a folder for temporary files:
Knp\Snappy->AbstractGenerator file function `getTemporaryFolder`.

I changed the return value of `sys_get_temp_dir()` to `storage_path()`.
Thank you for responding
