### ISSUE TITLE
wkhtmltopdf not including Bootstrap 4 Styling At All

### ISSUE THREAD

**Issue by Dracaratos** [barryvdh/laravel-snappy#258]
Hey there,

Not sure if it's because Bootstrap 4 uses flexbox or what, but even after copying bootstrap.min.css to a local file and including it that way the PDF shows no sign of using the correct styles

My end result is this: 
[Resume (47).pdf](https://github.com/barryvdh/laravel-snappy/files/1683736/Resume.47.pdf)

The photo and the text _should_ be on the same row, using styling, but it treats each column as separate, here's the HTML I use

```
<div class="row">
          <div class="col" style="padding-bottom: 24px;">
            @if(Auth::user()->GetPhotos(Auth::user()->id) != null && Auth::user()->GetPrimaryPhoto(Auth::user()->id) != null)
              <?php $Photo = Auth::user()->GetPrimaryPhoto(Auth::user()->id) ?>
              <a href="{{'https://theareel.com/photos/'.Auth::user()->id.'/'.$Photo->photo_name}}" data-fancybox="images">
                <img class="img-responsive" style="display:inline-block; max-width: 15em; width: 100%; height: auto; box-shadow: 6px 6px 6px black; background: rgba(0,0,0,0.05)" id="{{$Photo->photo_name}}" src="{{'https://theareel.com/photos/'.Auth::user()->id.'/'.$Photo->photo_name}}">
              </a>
            @endif
          </div>
          <div class="col">
              <br>
              <p>Email: {{Auth::user()->email}}</p>
              <p>Age: {{Auth::user()->getAge()}} Height: {{floor((Auth::user()->height)/12)}}' {{Auth::user()->height - (floor((Auth::user()->height)/12)*12)}}"</p>
              <p>Eye Color: {{ucfirst(Auth::user()->eyecolor)}}</p>
              <p>Hair Color: {{ucfirst(Auth::user()->haircolor)}}</p>
              <p>Ethnicity: {{ucfirst(Auth::user()->ethnicity)}}</p>
          </div>
        </div>
```

Also, the Special Skills is supposed to be 4 columns each of the row, so 1/3 of the size each
```
                  <div class="col-4"><li class="list-group-item">{{$specialskill}}</li></div>
```

Thanks

**Comment by tobysommer** [comment]
I also noticed some issues w/ flexbox... (using Tailwind, but after removing flexbox and using floats, it worked...)

**Comment by Glideh** [comment]
I'm having this too with Bootstrap 4.
Bootstrap 3 had the `$enable-flex` SASS variable that we could set to false, but I can't find it in BS4

**Comment by DUBroquin** [comment]
If you use Laravel Mix, you can use [postcss autoprefixer](https://github.com/postcss/autoprefixer) to enable flex (only tested with Tailwind)

**Comment by Mr-Sloth** [comment]
I think I have the same issue. I got it working by adding to every `col` element `float: left`. Do you guys have any better solution?

**Comment by toix** [comment]
Haven't found a way to get Bootstrap 4 cols to work with WKHTMLTOPDF.
I switched to Puppeteer using PuPHPeteer and I am pretty happy with the step. No required feature was missing.

https://github.com/nesk/puphpeteer
https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md

**Comment by Mr-Sloth** [comment]
@toix really Thank you, I will definitely do the same as soon as I have time. 
Did it take long for you? Puphpeteer, would also just be a temporary replacement in the end I want to swap to puppeteer anyway.

**Comment by toix** [comment]
@Mr-Sloth It took me one week. But I used multiple features I had to implement in a different way for Puppeteer.
PuPHPeteer is just an Adapter for Puppeteer. I don't think there is a better way to use Puppeteer from PHP.

**Comment by damonbakker** [comment]
I personally ran into quite some trouble when flexbox was applied in bootstrap 4. Using a custom grid without flexbox seems to work fine though.

**Comment by byustephen** [comment]
Does anyone know how to load external css files for snappy? I can easily just have css in a style tag in the head section, but i'd love to have it as an external file. 

Also, it seems that Snappy and DomPdf don't like to work with Bootstrap OR large css files. So I've just have onpage css that doesn't use flexbox (classic margins, tables, and padding) and it works great.

**Comment by Mr-Sloth** [comment]
@byustephen It works for me by using direct url imports, not relative urls! 

```
$html .= '<style>';
$html .= ' @import "http://local.ip.or.url:port/path/to/css/your.css";';
$html .= ' @import "http://local.ip.or.url:port/path/to/css/bootstrap.min.css";';
$html .= '</style>';
```

**Comment by byustephen** [comment]
Well that's clever. Thanks for sharing a solution with me.

**Comment by abelardolg** [comment]
> Hey there,
> 
> Not sure if it's because Bootstrap 4 uses flexbox or what, but even after copying bootstrap.min.css to a local file and including it that way the PDF shows no sign of using the correct styles
> 
> My end result is this:
> [Resume (47).pdf](https://github.com/barryvdh/laravel-snappy/files/1683736/Resume.47.pdf)
> 
> The photo and the text _should_ be on the same row, using styling, but it treats each column as separate, here's the HTML I use
> 
> ```
> <div class="row">
>           <div class="col" style="padding-bottom: 24px;">
>             @if(Auth::user()->GetPhotos(Auth::user()->id) != null && Auth::user()->GetPrimaryPhoto(Auth::user()->id) != null)
>               <?php $Photo = Auth::user()->GetPrimaryPhoto(Auth::user()->id) ?>
>               <a href="{{'https://theareel.com/photos/'.Auth::user()->id.'/'.$Photo->photo_name}}" data-fancybox="images">
>                 <img class="img-responsive" style="display:inline-block; max-width: 15em; width: 100%; height: auto; box-shadow: 6px 6px 6px black; background: rgba(0,0,0,0.05)" id="{{$Photo->photo_name}}" src="{{'https://theareel.com/photos/'.Auth::user()->id.'/'.$Photo->photo_name}}">
>               </a>
>             @endif
>           </div>
>           <div class="col">
>               <br>
>               <p>Email: {{Auth::user()->email}}</p>
>               <p>Age: {{Auth::user()->getAge()}} Height: {{floor((Auth::user()->height)/12)}}' {{Auth::user()->height - (floor((Auth::user()->height)/12)*12)}}"</p>
>               <p>Eye Color: {{ucfirst(Auth::user()->eyecolor)}}</p>
>               <p>Hair Color: {{ucfirst(Auth::user()->haircolor)}}</p>
>               <p>Ethnicity: {{ucfirst(Auth::user()->ethnicity)}}</p>
>           </div>
>         </div>
> ```
> 
> Also, the Special Skills is supposed to be 4 columns each of the row, so 1/3 of the size each
> 
> ```
>                   <div class="col-4"><li class="list-group-item">{{$specialskill}}</li></div>
> ```
> 
> Thanks

@IAmDragon , how could you embed a picture into a pdf dinamically created? Did you use some version of Symfony?

Thanks.

**Comment by Dracaratos** [comment]
@abelardolg sorry I missed this

It was dynamically generated using wkhtmltopdf by generatic a webpage using Laravel's Blade Syntax that was similar to a resume. When the user wanted to it rendered the page statically then sent the render to WKHTMLPDF

**Comment by darrist** [comment]
Hi, understood that this is closed. I would just like to add my case here in case anyone searching.

I have manage to use Tailwind 2.0 + Laravel Mix to render correctly.

What I use in particular is:

1. Typical CSS reference using asset tag.
```
<head><link href="{{ asset('css/app.css') }}" rel="stylesheet"></head>`
```

2. I use a clearfix div after every flex
```
<div class="flow-root"></div>
```

3. I have a browserlist tag in package.json for autoprefixer to compile css that compatible with older webkit which WKHTMLPDF uses
```
  "browserslist": [
    "> 0.3%",
    "last 7 versions",
    "Android >= 4",
    "Firefox >= 20",
    "iOS >= 8"
  ]
```

4. I did not use any inline SVG and used `<img>` tag with fixed height and width.

Cheers.

**Comment by pathros** [comment]
@darrist  Could you please give more details? I am having the same problems, I have actually [posted a question](https://stackoverflow.com/q/65944326/1883256).

**Comment by Alrod8901** [comment]
> Does anyone know how to load external css files for snappy? I can easily just have css in a style tag in the head section, but i'd love to have it as an external file.
> 
> Also, it seems that Snappy and DomPdf don't like to work with Bootstrap OR large css files. So I've just have onpage css that doesn't use flexbox (classic margins, tables, and padding) and it works great.

@byustephen  After trying multiple options I have discovered that styles can be loaded as blade components.
So create a component for the styles component-css.blade.php where I include the styles
`<style>
     html, body {
         margin: 0 10px 0 0;
         padding: 0;
         background-color: #fff;
     }
<style/>`

Then load that component into the head of the view and the magic was done.
`<html >
<head>

    
    <x-component-css></x-component-css>
</head><body></body></html>`


I hope this can help you. I had years with duplicate styles in each view and this fixed it.

**Comment by Soban3** [comment]
> Hi, understood that this is closed. I would just like to add my case here in case anyone searching.
> 
> I have manage to use Tailwind 2.0 + Laravel Mix to render correctly.
> 
> What I use in particular is:
> 
> 1. Typical CSS reference using asset tag.
> 
> ```
> <head><link href="{{ asset('css/app.css') }}" rel="stylesheet"></head>`
> ```
> 
> 2. I use a clearfix div after every flex
> 
> ```
> <div class="flow-root"></div>
> ```
> 
> 3. I have a browserlist tag in package.json for autoprefixer to compile css that compatible with older webkit which WKHTMLPDF uses
> 
> ```
>   "browserslist": [
>     "> 0.3%",
>     "last 7 versions",
>     "Android >= 4",
>     "Firefox >= 20",
>     "iOS >= 8"
>   ]
> ```
> 
> 4. I did not use any inline SVG and used `<img>` tag with fixed height and width.
> 
> Cheers.

This tailwind solution works for me except for the colors. Do you know a workaround for that too? 😅
