### ISSUE TITLE
Saving file errors using utf-8 on Centos 6.9

### ISSUE THREAD

**Issue by yanivhs** [barryvdh/laravel-snappy#266]
We are using Laravel 5.4 with Snappy.
Trying to save a filename in non-English characters ( Hebrew in UTF-8 ).
The result is an empty filename -> ".pdf"
Testing the creation of the same pdf filename using exec with the wkhtmltopdf-amd64 is working as expected.

**Comment by viethung0o0** [comment]
Same issue

**Comment by Nationalcat** [comment]
#380 to support UTF-8 filename
