### ISSUE TITLE
Downloading an A4 results in a smaller sheet

### ISSUE THREAD

**Issue by Hiroki111** [barryvdh/laravel-snappy#271]
The issue that I've been facing is that downloaded PDF (A4) is always smaller than the original view, which is in HTML.

Here is a snippet of the code.

     return PDF::loadView('view.path', $data)->setOrientation('landscape')
            ->setOption('page-size', 'A4')
            ->setOption('margin-bottom', 0)
            ->setOption('margin-left', 0)
            ->setOption('margin-right', 0)
            ->setOption('margin-top', 0)
            ->download('file_name.pdf');

The content of the file itself is fine, but the size of the downloaded file is around 70% of that of the original one.

Has anyone seen a similar issue?

Any advice will be appreciated.

     "require": {
        "php": ">=7.1.3",
        "barryvdh/laravel-snappy": "^0.4.1",   
        "h4cc/wkhtmltoimage-amd64": "0.12.x",
        "h4cc/wkhtmltopdf-amd64": "0.12.x",    
        "laravel/framework": "5.6.*"
      },

**Comment by qwert1x** [comment]
I have similar issue

**Comment by qwert1x** [comment]
I downgraded wkhtmltopdf package to 0.12.3 and seems it's works
`composer require h4cc/wkhtmltopdf-amd64:0.12.3`

**Comment by Leoramsy** [comment]
> I downgraded wkhtmltopdf package to 0.12.3 and seems it's works
> `composer require h4cc/wkhtmltopdf-amd64:0.12.3`

I had the same issue and downgrading wkhtmltopdf package to 0.12.3 solved my issue as well
