### ISSUE TITLE
What should I use?

### ISSUE THREAD

**Issue by icangku** [barryvdh/laravel-snappy#274]
Laravel Snappy or Laravel Dompdf? 
Because I have to use Laravel Snappy for exporting with datatables, but I have my own custom export using Laravel Dompdf and it has been affected/broken by Laravel Snappy

**Comment by carltondickson** [comment]
I've tried both now when creating a PDF from HTML containing thousands of tables rows and a fair amount of CSS.
I would say Snappy performance and peak memory usage is much more reasonable.

Dompdf - 1000 rows - peak 160 MB - 76 seconds
Snappy - 1000 rows - peak 28 MB -  4 seconds
