### ISSUE TITLE
Remove Header and Footer to add terms and conditions

### ISSUE THREAD

**Issue by txuspy** [barryvdh/laravel-snappy#275]
@barryvdh 
I',m using Laravel 5.5 to create a PDF file using PHP, HTML, CSS.
I want to generate a PDF with and extra page without header and footer. It is to print terms and conditions at the end of my budget. 
I can generate the first 2 page with the issues but when I want to add the terms and contiditons I have the footer and header and the pdf options ( marging...) 
I have tried to remove header and footer using javascript when I loadView removing header and footer with css but I have a white space in those places but I need all the page.
     
```
        $presupuesto = ExpedientePresupuesto::findOrFail($id_presupuesto);
        $now = Carbon::now('Europe/Madrid');
        $header     = \View::make('expedientes.pdf.cabeceraPresupuesto', compact('now', 'request', 'presupuesto') )->render();
        $footerHTML = Footer::footerHtml($now);
        $footer     = \View::make('expedientes.pdf.piePresupuesto', compact( 'footerHTML', 'request', 'presupuesto') )->render();
        $pdf= \PDF::loadView('expedientes.pdf.cuerpoPresupuesto', compact('presupuesto', 'request'));
       return view('expedientes.pdf.cabeceraPresupuesto', compact('now', 'presupuesto', 'request'));
	$pdf->setPaper('a4');
        $pdf->setOption('header-html', $header );
        $pdf->setOption('footer-html', $footer );
        $pdf->setOption('footer-spacing', 10 );
```

My question is it possible to add other page with differents optios in the same PDF?  I mean, the first part of the PDF has header footer and anything I want and the last part has no header, other spacing... 
Somenting like that ( does not working)

 ```
        $pdf.= \PDF::loadView('expedientes.pdf.terms', compact('presupuesto', 'request'));
        $pdf->setPaper('a4');
        $pdf->setOption('header-html', '' );
        $pdf->setOption('footer-html',  '');
        $pdf->setOption('footer-spacing', 10 );
        return $pdf->stream( $now . '-PresupuestoFP.pdf');
```

**Comment by ghanshyamtank59** [comment]
Yes, It is possible.

[Click here](https://github.com/barryvdh/laravel-snappy/issues/182)

**Comment by txuspy** [comment]
Thank you a lot. 
I found the same solution with other libray , [Lara-pdf-merger](https://github.com/deltaaskii/lara-pdf-merger) but I'm would like to do diferent. 
I would like create an unique PDF without merge and not saving anything or deleting those PDF parts.

**Comment by 2acode** [comment]
Hi @txuspy,
i have now same problem, did you solved without merge?
Thanks
