### ISSUE TITLE
Page size seems random

### ISSUE THREAD

**Issue by ghost** [barryvdh/laravel-snappy#280]
I have an incredibly complex view that needs to be rendered in as PDF in laravel.  Mostly Snappy has been working ok, but today I noticed about 10% of my PDFS have different page sizes.  Most are 8.5x11 but the few that aren't are some weird size of 8.26x11.8.  I've tried setPaper, page-size, and page-width.  I've tried forced settings in css for the body width, everything I could think of and these few pdfs generated from the same code render smaller regardless of settings.  
I need to generate nearly 3000 PDFS all from the same code, I can't have 10% of them off like this.  I've looked at dompdf but the comments there say complex HTML is better using snappy.  
Anyone have any thoughts? Ideas?  I'm sure the issue is with wkhtmltopdf but really this is just bizarre

**Comment by barryvdh** [comment]
You could try using Puppeteer perhaps.

**Comment by surgiie** [comment]
@ghost Any luck with this?
