### ISSUE TITLE
Multiple unresolved functions and 'unknown network error'

### ISSUE THREAD

**Issue by realj42** [barryvdh/laravel-snappy#283]
Hi - I an looking at code using laravel-snappy.  It has recently started failing with the following set of errors. 
`[2018-06-15 16:29:28] production.ERROR: RuntimeException: The exit status code '1' says something went wrong:
stderr: "Loading pages (1/6)
[>                                                           ] 0%
[======>                                                     ] 10%
QSslSocket: cannot resolve CRYPTO_num_locks
QSslSocket: cannot resolve CRYPTO_set_id_callback
QSslSocket: cannot resolve CRYPTO_set_locking_callback
QSslSocket: cannot resolve sk_free
QSslSocket: cannot resolve sk_num
QSslSocket: cannot resolve sk_pop_free
QSslSocket: cannot resolve sk_value
QSslSocket: cannot resolve SSL_library_init
QSslSocket: cannot resolve SSL_load_error_strings
QSslSocket: cannot resolve SSLv3_client_method
QSslSocket: cannot resolve SSLv23_client_method
QSslSocket: cannot resolve SSLv3_server_method
QSslSocket: cannot resolve SSLv23_server_method
QSslSocket: cannot resolve X509_STORE_CTX_get_chain
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
QSslSocket: cannot resolve SSLeay
QSslSocket: cannot call unresolved function CRYPTO_num_locks
QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
QSslSocket: cannot call unresolved function SSL_library_init
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function sk_num
[===============>                                            ] 26%
[==============================>                             ] 50%
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function SSL_library_init
[============================================================] 100%
Counting pages (2/6)                                               
[============================================================] Object 1 of 1
Resolving links (4/6)                                                       
[============================================================] Object 1 of 1
Loading headers and footers (5/6)                                           
Printing pages (6/6)
[>                                                           ] Preparing
[==>                                                         ] Page 1 of 23
[====>                                                       ] Page 2 of 23
[=======>                                                    ] Page 3 of 23
[==========>                                                 ] Page 4 of 23
[============>                                               ] Page 5 of 23
[===============>                                            ] Page 6 of 23
[==================>                                         ] Page 7 of 23
[====================>                                       ] Page 8 of 23
[=======================>                                    ] Page 9 of 23
[=========================>                                  ] Page 10 of 23
[============================>                               ] Page 11 of 23
[===============================>                            ] Page 12 of 23
[=================================>                          ] Page 13 of 23
[====================================>                       ] Page 14 of 23
[=======================================>                    ] Page 15 of 23
[=========================================>                  ] Page 16 of 23
[===========================================>                ] Page 17 of 23
[==============================================>             ] Page 18 of 23
[=================================================>          ] Page 19 of 23
[===================================================>        ] Page 20 of 23
[======================================================>     ] Page 21 of 23
[=========================================================>  ] Page 22 of 23
[============================================================] Page 23 of 23
Done                                                                        
Exit with code 1 due to network error: UnknownNetworkError
QSslSocket: cannot call unresolved function CRYPTO_num_locks
QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback`

I suspect the unresolved functions have always been there but did not cause an error.  I tried updating to the latest versions of wkhtmltopdf-amd64 but that has not helped.  Any ideas?  What is the network activity for anyway?  The pdf still seems to be generated OK but the error causes my Larvavel page to crash (debug output on).

**Comment by pcartagena74** [comment]
I get a similar error.  I also just switched to 0.12.5 (dev-master) and it didn't resolve it.

The most confusing piece of this is that, in my production environment (heroku) I can print PDF receipts.  In my test environment (also heroku) there was only 1 difference (font awesome 5 URL) and so I downgraded to v4 and made the receipt as it is in production and it still won't work.

I've attached the source html for each of the receipts.  Again, the production version IS creating PDF receipts and the test version is not.

Upon comparing them, there's a bunch of script txt that was inserted in the production version which isn't needed and so it is removed from the test version.

The few https links that exist, even in the error output, are shown to be ignored.  But the links exist in both versions so I wouldn't think they are the cause.

I am at a loss.  Please help!

[test_receipt.txt](https://github.com/barryvdh/laravel-snappy/files/2532847/test_receipt.txt)
[prod_receipt.txt](https://github.com/barryvdh/laravel-snappy/files/2532848/prod_receipt.txt)

**Comment by pcartagena74** [comment]
I determined what caused the issue.  I use Heroku and I was on Cedar-14.  This stack is phasing out by May 2020 and I've tried switching it again in my test environment and these errors have returned.

I'm searching for ways to make this work using the Heroku-18 stack and would appreciate any pointers.

**Comment by ajcastro** [comment]
any updates on this? I also encountered this

**Comment by ajcastro** [comment]
solution here: https://github.com/barryvdh/laravel-snappy/issues/222
