### ISSUE TITLE
CentOS 7 - SELinux | Permission denied

### ISSUE THREAD

**Issue by 2acode** [barryvdh/laravel-snappy#294]
Hi,
with SELinux active the httpd can't write using external pro.

The only solution found is this (without disable SELinux):
sudo semanage permissive -a httpd_t

Found here:
https://github.com/barryvdh/laravel-snappy/issues/238

But is this the best way?
Thanks

**Comment by pjona** [comment]
@2acode I'm using someting like this: `chcon -R -t httpd_sys_script_exec_t  /var/www/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64`
