### ISSUE TITLE
Libxrender

### ISSUE THREAD

**Issue by Sekonda** [barryvdh/laravel-snappy#3]
# [Libxrender](https://launchpad.net/ubuntu/+source/libxrender)

I spent a few hours trying to get this working today, I found my problem... Turns out I didn't have [libxrender](https://launchpad.net/ubuntu/+source/libxrender) installed on my server. 

I just wanted to submit this somewhere incase others are getting errors but followed steps seemingly correctly.
## Solution

Ran the following command and accepted/updated the package.

```
sudo apt-get install libxrender1 
```

**Comment by EnglishAdam** [comment]
Have just had to install it on a forge.laravel server, running Laravel 5.6, PHP 7.2

It works a treat. Thank you very much for your solution.

This is perhaps not the place to say, but for anybody else having related issues with **wkhtmltopdf**, ensure you have installed the proper binaries:

```
# 32 Bit systems
> composer require h4cc/wkhtmltopdf-amd64 0.12.x
> composer require h4cc/wkhtmltoimage-amd64 0.12.x

# 64 Bit systems
> composer require h4cc/wkhtmltopdf-i386 0.12.x
> composer require h4cc/wkhtmltoimage-i386 0.12.x
```

Then correctly reference them from within your code:
```
$pdf->binary = base_path('vendor/bin/wkhtmltopdf-amd64');
```

Then (as above) install libxrender on your hosted server:
```
> sudo apt-get install libxrender1 
```

**Comment by chrisharrison** [comment]
@EnglishAdam 32bit is i386, 64bit is amd64.
