### ISSUE TITLE
Namespace missing PdfFaker.php

### ISSUE THREAD

**Issue by karmendra** [barryvdh/laravel-snappy#307]
When I run `php artisan ide-helper:generate` I get following error

> PHP Fatal error:  Class 'PdfWrapper' not found in /home/vagrant/Code/mrm/vendor/barryvdh/laravel->snappy/src/PdfFaker.php on line 5
>
>   Symfony\Component\Debug\Exception\FatalErrorException  : Class 'PdfWrapper' not found
>
>  at /home/vagrant/Code/mrm/vendor/barryvdh/laravel-snappy/src/PdfFaker.php: 5
>  1: <?php
>  2:
>  3: use PHPUnit\Framework\Assert as PHPUnit;
>  4:
>  5: class PdfFaker extends PdfWrapper
>  6: {
>  7:    protected $view;
>  8:
>  9:    /**
>10:      * Load a View and convert to HTML

When I checked the code I found that Namespace is missing in PdfFaker.php.

Can you please do the needed fix?

**Comment by karmendra** [comment]
I just saw that there are couple of pending PRs for this, close this issue when any of those gets merged. Appreciate everyone's contribution for a lovely package like this, makes life so much easier for all developers.

Thanks.

**Comment by Omranic** [comment]
Fix merged #306 👍

**Comment by Omranic** [comment]
@c0defre4k  Fixed version still not tagged yet.

@barryvdh can we tag the newly fixed version please?

**Comment by barryvdh** [comment]
Yes is fixed and tagged
