### ISSUE TITLE
Don't show images

### ISSUE THREAD

**Issue by feralheart** [barryvdh/laravel-snappy#311]
I want to render it as a pdf, but it don't load the images:
[TYRANITAR.pdf](https://github.com/barryvdh/laravel-snappy/files/2363735/TYRANITAR.pdf)

**Comment by Amit-singh311** [comment]
Hii! I am facing the same issue, It loads some of the images which are in gradient. Please let me know if you find some solution.

**Comment by feralheart** [comment]
I had to use the absolute path (`/var/www/projectfolder/path-to-the-image/something.png`)

**Comment by stevenspinoza** [comment]
For future reference:
Using **localhost wont work** for this, **use a another domain** ie. your-project.test, then **it will work** when using **{{asset()}}** o **{{public()}}** for accessing your images.
