### ISSUE TITLE
TOC Styling?

### ISSUE THREAD

**Issue by AugmentBLU** [barryvdh/laravel-snappy#318]
Hello, how do we style the TOC? I can't find anything about which classes it may use. 

Thanks!

**Comment by harrysbaraini** [comment]
As far as I know wkhtmltopdf only renders a HTML page to PDF as it is, so you style it as you would do in a regular HTML page.

**Comment by AugmentBLU** [comment]
That's what I thought but how do we know which styles the TOC is using? Is there any docs that give us a clue?
