### ISSUE TITLE
When wkhtmltopdf as composer dependency will be updated to 0.12.5 ?

### ISSUE THREAD

**Issue by manelsanz** [barryvdh/laravel-snappy#320]
Hi,
I know that is not a problem of this fabulous package, but the dependency as a composer package of wkhtmltopdf is not the current stable (0.12.4 => 0.12.5) and that version have some bugs like https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3001...

Thanks.

**Comment by OmathiasO** [comment]
Just had the same question, and obviously @manelsanz already opened this issue, so I'm hanging on to this.. would be very helpful to update wkhtmltopdf dependency to 0.12.5

**Comment by Langstra** [comment]
Couldn't you just try to use the latest version of wkhtmltopdf. It is  minor version change, so the API should be the same and laravel-snappy should be able to work with it.

**Comment by iraklisg** [comment]
I run into https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3001 as well :cry:
