### ISSUE TITLE
 Do not create temporary file

### ISSUE THREAD

**Issue by dalcero** [barryvdh/laravel-snappy#323]
Hello.
I have Ubuntu 18.04 and Laravel 5.3. I did all the tests found in forums and none worked.
I noticed that it does not create the temporary file, I can not find the solution ..

composer.json
"barryvdh/laravel-snappy": "^0.4.3", "h4cc/wkhtmltoimage-amd64": "0.12.x", "h4cc/wkhtmltopdf-amd64": "0.12.x"

snappy.conf
'binary' => base_path('vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64'),

Error
The exit status code '1' says something went wrong: stderr: "Loading pages (1/6) [> ] 0% [======> ] 10% [============> ] 21% [================> ] 28% libpng warning: iCCP: known incorrect sRGB profile [======================> ] 38% [=========================> ] 42% [============================================================] 100% QPainter::begin(): Returned false Error: Unable to write to destination Exit with code 1, due to unknown error. " stdout: "" command: /var/www/are_you/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64 --lowquality --margin-bottom '30' --margin-left '20' --orientation 'landscape' --encoding 'utf-8' --footer-html '/tmp/knp_snappy5be57c0cc76973.72037235.html' '/tmp/knp_snappy5be57c0cc76220.67485469.html' '/home/fitConnect.pdf'.

**Comment by bhattraideb** [comment]
I am also getting this error. Does anyone solved this??

**Comment by mihai-craita** [comment]
Also getting this error. Are you using php7.4?

**Comment by bhattraideb** [comment]
@mihai-craita , I am using PHP7.2.

**Comment by pitriglg22** [comment]
Hey there.. I got the same error notification. Do you guys find the solution?

**Comment by mihai-craita** [comment]
@pitriglg22 for me this was related to inaccessibles urls like "file://....", links injected in the page by plugins.
The "sRGB profile" error might be of incorrect css values.

**Comment by pitriglg22** [comment]
@mihai-craita big thankyou for your response.. but by the way i choose to use mpdf hehe
