### ISSUE TITLE
Unable to add CSS filter or -webkit-filter property

### ISSUE THREAD

**Issue by saad3074** [barryvdh/laravel-snappy#324]
Hi i am adding filter & -webkit-filter property to image but when creating pdf it not work. what i can do for this .

**Comment by saad3074** [comment]
@barryvdh

**Comment by saad3074** [comment]
While creating PDF filter and -webkit-filter CSS property can not work.

**Comment by Langstra** [comment]
Probably nothing, this is not supported by wkhtmltopdf I believe.
