### ISSUE TITLE
Input Forms

### ISSUE THREAD

**Issue by warkior** [barryvdh/laravel-snappy#337]
Is there a secret to making PDFs that allow people to fill out the form fields and print with their answers? I'm using this code, and it doesn't seem to do it. Not sure what I'm doing wrong.

```
$snappy = app()->make('snappy.pdf');
$snappy->setOption('enable-forms', true);
$pdf = $snappy->getOutputFromHtml($html);
```

**Comment by stevebauman** [comment]
Hi @warkior, I would ask this on the root [Snappy](https://github.com/KnpLabs/snappy) or [wkhtmltopdf](https://github.com/wkhtmltopdf/wkhtmltopdf) GitHub repos.

This package simply wraps those into a simple interface and calls [Snappy](https://github.com/KnpLabs/snappy) under the hood.

You can see all the options for `wkhtmltopdf` here: https://wkhtmltopdf.org/usage/wkhtmltopdf.txt

Related:

https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4275

I would also check your `wkhtmltopdf` version to ensure you're using the latest.
