### ISSUE TITLE
Loading External/Internal CSS - Tailwindcss if Possible

### ISSUE THREAD

**Issue by ekcltfrm** [barryvdh/laravel-snappy#339]
Hi, I am trying to get the css styling working for my pdf documents. So far no such luck. 

1. Is it possible to use CDN style sheet documents? When I add say bootstrap stylesheet cdn to my view's head section, I get the error below;
`The exit status code '1' says something went wrong: stderr: "Loading pages (1/6) [> ] 0% [======> ] 10% [======> ] 11% Error: Failed to load https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css, with network status code 3 and http status code 0 - Host not found`

2. I tried adding the entire bootstrap file inline, in that case, there is no error but it seems flexbox is not working at all. Only styling of text properties (font background color etc) changed. 

What am I missing here?  Ideally, I use tailwindcss on my app, Is it possible for me to use that? If so, How could I do that?

**Comment by Mr-Sloth** [comment]
1. Look at my comment here:
https://github.com/barryvdh/laravel-snappy/issues/258#issuecomment-474707844

2. Flexbox is not working with wkhtml at all, the thread explains some workarounds, but in the end if you want to stick with wkhtml at the moment you simply can´t use flexbox.
