### ISSUE TITLE
Using --viewport-size on Snappy

### ISSUE THREAD

**Issue by VitorArjol** [barryvdh/laravel-snappy#34]
Hi,
I'm using a admin panel with Twitter Bootstrap 3, and my pdfs are getting the responsible styles. I was looking for this option (--viewport-size) on the wkhtmltopdf docs, but there aren't any examples.

Is it possible to use this option with Snappy? Or there is other way to fix the Bootstrap display styles?

Thanks

**Comment by VitorArjol** [comment]
Nevermind, I was just using wrong the "setOption" of the wrapper.

It's just return PDF::loadFile('http://site.com')->setOption('viewport-size', '1366x1024' )->stream('file.pdf');

:D

**Comment by suarezgl** [comment]
Thanks!

**Comment by surgiie** [comment]
@vitorarjol This helped me solve a problem ive been dealing with for several hours :D 
Cheers mate!
