### ISSUE TITLE
CSS Failed Load, Docker environment 

### ISSUE THREAD

**Issue by apapazisis** [barryvdh/laravel-snappy#340]
ocal.ERROR: The exit status code '139' says something went wrong:
stderr: "Loading pages (1/6)
[>                                                           ] 0%
[======>                                                     ] 10%
[=======>                                                    ] 12%
**Error: Failed to load http://bau.test/pdf/bootstrap.min.css?id=ec3bb52a00e176a7181d, with network status code 1 and http status code 0 - Connection refused
Warning: Failed to load http://bau.test/css/app.css?id=81a5043f2bb2d2e37845 (ignore)
Error: Failed to load http://bau.test/css/pdf.optimization.css?id=04ab1c8463db52aad4ed, with network status code 1 and http status code 0 - Connection refused
Error: Failed to load http://bau.test/css/thg.pdf.optimization.css?id=51f91facea1435f0728f, with network status code 1 and http status code 0 - Connection refused
Warning: Failed to load http://bau.test/img/logo_big.png (ignore)**
[============================================================] 100%
Counting pages (2/6)                                               
[============================================================] Object 1 of 1
Resolving links (4/6)                                                       
[============================================================] Object 1 of 1
Loading headers and footers (5/6)                                           
[======>

**Comment by apapazisis** [comment]
Not able to generate pdf because css can not be loaded.

What I include in my Laravel Blade files is as an example

<link rel="stylesheet" href="{{url(mix('css/pdf.optimization.css'))}}">

**Comment by DanjBethel** [comment]
> 

Did you ever actually figure this out?

**Comment by kkallasm** [comment]
Same problem here. Any progress?
