### ISSUE TITLE
PDF save loadView displaying command line

### ISSUE THREAD

**Issue by AdoZiad** [barryvdh/laravel-snappy#341]
Hello,

I have a strange situation where the command is shown but not executed.

I have the following:

Debian 7
Laravel 5.3

config/app.php
`'PDF' => Barryvdh\Snappy\Facades\SnappyPdf::class,`

Controller.php
```
PDF::loadView('reports.contractLetter', compact('contract'))
            ->save(storage_path('app/public/contracts/').$contract->CId.'/Lettre_contract_'.$contract->ContractId.'_'.$dat.'.pdf');
```

I get the following result displayed on a white page:
`"/usr/local/bin/wkhtmltopdf --lowquality '/tmp/knp_snappy5cd3e1ba1d35d9.23726491.html' '/xxx/storage/app/public/contracts/558/Lettre_contract_144563_09-05-2019.pdf'"`

If i copy / paste the above result in the terminal it generate the pdf.

The above method was working a couple of days ago but now for some reason it's not anymore and i can't figure out why.

Many thanks in advance for your help.

Regards.

**Comment by AdoZiad** [comment]
Anyone???

**Comment by newtella** [comment]
Hey just try this:

$date = Carbon::now()->format('Y-m-d');
$pdf = PDF::loadview('reports.contractLetter', compact(contract'))->
save(storage_path("app\public\contracts\Lettre_contract_{$order->id}_{$date}.pdf"));

Happy Coding!

**Comment by AdoZiad** [comment]
Hello,

Thanks for your reply.

Still not working...

I simplified things and still get the same results...

I created the HTML file with the following (in tmp):
<h1>Bill</h1><p>You owe me money, dude.</p>

I try to save the html file to the location as below:
$pdf = PDF::loadFile('/tmp/knp_snappy5cf8288a5fc8c9.72712846.html')
->save(storage_path("app/public/contracts/{$contract->CId}/Contract_{$contract->ContractId}_{$dat}.pdf"));

When i launch the page to generate the pdf file i get:
"/usr/local/bin/wkhtmltopdf --lowquality '/tmp/knp_snappy5cf8288a5fc8c9.72712846.html' '/xxx/storage/app/public/contracts/3151/Contract_1343101_2019-06-05.pdf'"

And the file is not generated to PDF.

Any help would be much appreciated.

Regards.

**Comment by newtella** [comment]
You're using PDF::loadFile thats used with URLs like https://github.com/, 

Example:

$pdf = PDF::loadFile('https://github.com/')->save(storage_path("invoices\Lettre_contract_{$order->id}_{$ndate}.pdf"));

return $pdf->stream('github.pdf');

try it! if doesn't work check the installation, maybe you forget something.

Use PDF::loadview  😋

Good Luck.

[Lettre_contract_2_2019-06-05.pdf](https://github.com/barryvdh/laravel-snappy/files/3259193/Lettre_contract_2_2019-06-05.pdf)

**Comment by AdoZiad** [comment]
Hi,

Unfortunately still no luck in making it working... I tried the suggested method above with no luck.

wkhtmltopdf is working fine when i issue the command in SSH.

On the same server i have another Laravel project where laravel-snappy is working fine. I have the impression that this is related to incompatibility with other packages installed but still can't figure out which one.

If any other ideas, please feel free to share.

Regards.

Ziad
