### ISSUE TITLE
Laravel Snappy Error download

### ISSUE THREAD

**Issue by temmy-virtuoso** [barryvdh/laravel-snappy#347]
Hi i have problem when i download pdf with laravel snappy show error like this 

The exit status code '1' says something went wrong: stderr: "'C:\xampp\htdocs\laravel_snappy_pdf\vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64' is not recognized as an internal or external command, operable program or batch file. " stdout: "" command: C:\xampp\htdocs\laravel_snappy_pdf\vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64 --lowquality --orientation "potrait" --page-size "a4" 

Here is my config :

return array(

    'pdf' => array(
        'enabled' => true,
        'binary' => base_path('vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64'),
        'timeout' => false,
        'options' => array(),
        'env'     => array(),
    ),
    'image' => array(
        'enabled' => true,
        'binary'  => 'vendor/h4cc/wkhtmltoimage-amd64/wkhtmltoimage',
        'timeout' => false,
        'options' => array(),
        'env'     => array(),
    ),

);

Can help for this error?

**Comment by kleuchart98** [comment]
same problem..
same error : **The exit status code '1' says something went wrong: stderr: "'C:\laragon\www\boomerangWeb\laravel_supplier_portal\vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64' is not recognized as an internal or external command, operable program or batch file. " stdout: "" command: C:\laragon\www\boomerangWeb\laravel_supplier_portal\vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64 --lowquality --orientation "landscape" "C:\Users\TDCLIC~1\AppData\Local\Temp\knp_snappy5d23501b955fa0.08704730.html" "C:\Users\TDCLIC~1\AppData\Local\Temp\knp_snappy5d23501b95d6c9.42723756.pdf".**

same config : 

`return array(

    'pdf' => array(
        'enabled' => true,
        'binary' => base_path('vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64'),
        'timeout' => false,
        'options' => array(),
        'env'     => array(),
    ),
    'image' => array(
        'enabled' => true,
        'binary' => base_path('vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltoimage-amd64'),
        'timeout' => false,
        'options' => array(),
        'env'     => array(),
    ),


);`

**Comment by kleuchart98** [comment]
I found the solution to this problem, you have to install wkhtmltopdf for windows with composer : 

composer require wemersonjanuario/wkhtmltopdf-windows "0.12.2.3"

and use this on app/snappy.php

return array(
    'pdf' => array(
        'enabled' => true,
        'binary' => base_path('vendor/wemersonjanuario/wkhtmltopdf-windows/bin/64bit/wkhtmltopdf.exe'),
        'timeout' => false,
        'options' => array(),
        'env'     => array(),
    ),
    'image' => array(
        'enabled' => true,
        'binary' => base_path('vendor/wemersonjanuario/wkhtmltopdf-windows/bin/64bit/wkhtmltoimage.exe'),
        'timeout' => false,
        'options' => array(),
        'env'     => array(),
    ),
);

**Comment by thebigtank** [comment]
the Still did not work

> I found the solution to this problem, you have to install wkhtmltopdf for windows with composer :
> 
> composer require wemersonjanuario/wkhtmltopdf-windows "0.12.2.3"
> 
> and use this on app/snappy.php
> 
> `return array(
> 
> ```
> 'pdf' => array(
>     'enabled' => true,
>     'binary' => base_path('vendor/wemersonjanuario/wkhtmltopdf-windows/bin/64bit/wkhtmltopdf.exe'),
>     'timeout' => false,
>     'options' => array(),
>     'env'     => array(),
> ),
> 'image' => array(
>     'enabled' => true,
>     'binary' => base_path('vendor/wemersonjanuario/wkhtmltopdf-windows/bin/64bit/wkhtmltoimage.exe'),
>     'timeout' => false,
>     'options' => array(),
>     'env'     => array(),
> ),
> ```
> 
> );`

this solution did not work..can you please explain better how you did it?
