### ISSUE TITLE
I cannot render all images on PDF

### ISSUE THREAD

**Issue by SaizDev** [barryvdh/laravel-snappy#350]
Greetings,

Some images are render and some others not. I cannot find an error pattern because some .jpg are showed and others .jpg not. They are similar in size and so on.  Both images are in the public folder, using the absolute path. Imagine that I use a for to show them and some items are not showed. They use the same code.

I don't know what more data would you need to help me. Feel free to ask but please, Help me!

Thank you

**Comment by SaizDev** [comment]
I tried also for those images that are not render to use base64 image and still not working.

**Comment by nioperas06** [comment]
I tried with png images and everything work fine. Can you your jpg file to png?

**Comment by SaizDev** [comment]
I can only render png files if the file has transparent background...

**Comment by striderwhitepderas** [comment]
Same issue here, one image loads, another doesn't. Making sure to use the correct relative pathing.

**Comment by SaizDev** [comment]
I have solved this issue by updating my OS. From Debian 9 to Debian 10 and now all images are shown properly. Hope you solve soon your problem mate.

**Comment by viniciuspsw** [comment]
I have the same problem. In my local environment with Windows 10 works well, but in production server with Ubuntu 18.04 only a few images are showing.

**Comment by SaizDev** [comment]
@viniciuspsw What version of the different technologies are you using? Check the versions of whtmltoPDF

**Comment by viniciuspsw** [comment]
@SaizDev I've been tested with versions 0.12.5 and 0.12.4 and faced the same issue in both versions for Linux.

The PDF is a large report and it has almost 1.3k pages and after 480 pages it doesn't render any image. All the images are optimized and has 200kb.

**Comment by SaizDev** [comment]
Then the problem could be the time you give the plugin to render the PDF. Maybe you have to change the config parameters to give your system more time.
