### ISSUE TITLE
Cannot print in portrait

### ISSUE THREAD

**Issue by SigalZ** [barryvdh/laravel-snappy#351]
Hello,

I am using this code:
`$pdf->setPaper('a4')->setOrientation('portrait');`

But it still prints in landscape.

Am I doing something wrong?

**Comment by nioperas06** [comment]
Hi @SigalZ  did you try with 'A4'?

**Comment by SigalZ** [comment]
@nioperas06 yes I did. Still, landscape

**Comment by SigalZ** [comment]
Today is suddenly started printing in portrait. Hurray
