### ISSUE TITLE
 toc选项设置为true不起作用 The TOC option set to true does not work

### ISSUE THREAD

**Issue by swgswg** [barryvdh/laravel-snappy#357]
`
 $headerFooter = [
            'encoding' => 'UTF-8',
            'enable-internal-links' => true,
            'keep-relative-links'=>true,
            'enable-external-links' => true,
            'header-html' => $headerHtml,
            'header-font-size' => 8,
            'header-line' => true,
            'header-spacing' => 5,
            'footer-center' => '[page] / [toPage]',
            'footer-font-size' => 8,
            'margin-top' => 15,
            'margin-bottom' => 10,
            'toc' => true,
            'toc-header-text' => 'Sommaire',
        ]
`
add toc option no directory appears on pdf

**Comment by icaroscherma** [comment]
I'm having the same issue. The Table of Contents it's not being generated when I set the `toc` option as true.
I will take a deeper look to see if it's a Laravel wrapper issue, if it's related to my wkhtmltopdf version, or environment deprecation (I'm using PHP 7.4 with Laravel 8).
