### ISSUE TITLE
Needs header and footer in each page but header image is not added in PDF, while footer image is working properly

### ISSUE THREAD

**Issue by Himashukla** [barryvdh/laravel-snappy#359]
I have already tried all solutions related to the header - footer issues which are already here. But none are working for me. That's why I'm opening this new issue.

version of laravel framework and package
**"barryvdh/laravel-snappy": "^0.4.5",
"laravel/framework": "^6.0",**

code in the **controller**
```

$headerHtml = view()->make('admin.productpdf.header')->render();
$footerHtml = view()->make('admin.productpdf.footer')->render();
$pdf = PDF::loadView('admin.productpdf.pdf')
        ->setOption('margin-top', '0mm')
	->setOption('margin-left', '0mm')
	->setOption('margin-right', '0mm')
	->setOption('margin-bottom', '28mm')
	->setOption('header-html', $headerHtml)
	->setOption('footer-html', $footerHtml);
return $pdf->stream('ProductCatalog.pdf');


```

code in **header.blade.php** file
`<img src="{{asset('h1.jpg')}}" style="width: 1000px; height: 150px; margin-left: -20px;">`

code in **footer.blade.php** file
`<img src="{{asset('f1.jpg')}}" style="width: 1000px; height: 130px; margin-left: -20px;">`

and this is my output

![image](https://user-images.githubusercontent.com/51231672/65014976-d7e74080-d93d-11e9-857a-6cb0c6d233a4.png)

**Comment by enricooliva** [comment]
You need to set margin-top to value, not 0. For instance setOption('margin-top', '44mm')

**Comment by Himashukla** [comment]
I already tried that but it's not working. And i did it other way.

**Comment by DanielBASouza** [comment]
You need to add the <!DOCTYPE html> to the header file.

**Comment by Himashukla** [comment]
@DanielBASouza I already tried the other way and I have put the header image in the pdf blade file and it's working perfectly. Now header image is showing only on first PDF page.
But still, I have tried your solution, but It's not working.

**Comment by 4rnol** [comment]
$footerHtml= '<div style="bottom: 0; width: 100%; text-align: center; font-size: 10px; color: #000; padding: 10px 0; border-top: 1px solid #000;">
                        <p style="margin: 0;">© 2021 Oltre Assicurazioni S.p.A. - P.IVA 13001840155</p>
                    </div>';
        $htmlContent = view('atc::atc-reports.creditsave-v2.report-pdf.index', [
            'report_json' => json_decode(file_get_contents($json_report)),
            'assets' => $assets,
            'atcReport' => $atcReport,
            'atcRequest' => $atcRequest
        ])->render();

        return SnappyPdf::loadHTML($htmlContent)
            ->setPaper('a4')
            ->setOption('enable-local-file-access', true)
            ->setOption('margin-bottom', '20mm')
            ->setOption('footer-html', $footerHtml)
            ->download('report-creditsafe-'.$atcReport->id.'.pdf'); 

with this works well
