### ISSUE TITLE
laravel issues 

### ISSUE THREAD

**Issue by Nemikhan** [barryvdh/laravel-snappy#360]
hi 
i am new to the laravel framework. i wana try to generate pdf report but there is some issues while generating pdf. i wana a project source code.

**Comment by stevebauman** [comment]
This isn't a support forum, and you gave absolutely no code usage or any information to help you whatsoever.

You can inspect all the source code on the [wkhtmltopdf](https://wkhtmltopdf.org) GitHub repository.
