### ISSUE TITLE
CSS displaying incorrectly on server but correctly locally

### ISSUE THREAD

**Issue by filip-nifti** [barryvdh/laravel-snappy#368]
Hi, im using Laravel 5.7 and laravel snappy 0.4.5.
Im loading css inline (bootstrap 4 included.) Its dirty i know.
When rendering the PDF locally it works perfectly but when i create them on the server the css is a bit off. It uses another font and the tables look different (Background-colors not being applied in table headers etc.)

What could be the issue causing the pdfs to be different?

**Comment by brianyudanto** [comment]
for the font, you can try to add 

`@font-face{
        font-family: 'Arial-Unicode-Bold';
	src: url('D:/yourProject/public/fonts/Arial-Unicode-Bold.ttf'); <-- full path
}`

**Comment by joefreire** [comment]
I have the same issue here

**Comment by joefreire** [comment]
I found a solution, check if css file is a absolut path like  <link href="{{ public_path() . '/css/pdf.css' }}" rel="stylesheet" type="text/css"/>
