### ISSUE TITLE
Laravel 6 compatibility

### ISSUE THREAD

**Issue by dthiery** [barryvdh/laravel-snappy#370]
Is laravel-snappy compatible with Laravel 6? I see compatibility listed as "Laravel 5" on the documentation.

**Comment by standaniels** [comment]
I think it is, check commit https://github.com/barryvdh/laravel-snappy/commit/9be767fc7a082665a84945f36c70b0cbead91ce9. I guess the docs haven't been updated just yet.

**Comment by SodomousPrime** [comment]
Laravel is at 6.5.x now will it be compatible?

**Comment by Lloople** [comment]
Yes it is. If you want to check the compatibility just open the `composer.json` file and check the version constraint for Illuminate components
