### ISSUE TITLE
Pdf not generated in background

### ISSUE THREAD

**Issue by andrepaes** [barryvdh/laravel-snappy#372]
Hello,
I'm developing an application that works perfectly when the pdf is generated by a "normal process" (when a logged user click on generate button pdf).
My question is, I'm trying to send these pdf by email so I'm trying to generate it in the background but the package throws this error:
The exit status code '127' says something went wrong:
stderr: "sh: /var/www/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64: not found

I'm pretty sure that everything is installed and working fine because I can manually generate a pdf.
Thanks in advance,
André Luiz

**Comment by w-brychcy** [comment]
Does your background process have access to the library? 
Also in your path project part is missed - generally vendor is inside some project.
