### ISSUE TITLE
error while loading shared libraries: libXrender.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by arkniazi** [barryvdh/laravel-snappy#375]
Stack trace
The exit status code '127' says something went wrong: stderr: "/home/abdul/rtdo/rtdo/vendor/h4cc/wkhtmltopdf-i386/bin/wkhtmltopdf-i386: error while loading shared libraries: libXrender.so.1: cannot open shared object file: No such file or directory " stdout: "" command: /home/abdul/rtdo/rtdo/vendor/h4cc/wkhtmltopdf-i386/bin/wkhtmltopdf-i386 --lowquality '/tmp/knp_snappy5dfe8e0f6fce58.61775052.html' '/tmp/knp_snappy5dfe8e0f6fd546.63857032.pdf'.

**Comment by ajcastro** [comment]
try this
https://www.cyberciti.biz/faq/debian-ubuntu-linux-wkhtmltopdf-error-while-loading-shared-libraries-libxrender-so-1/
