### ISSUE TITLE
error to print pdf in linux

### ISSUE THREAD

**Issue by TranceDevCode** [barryvdh/laravel-snappy#376]
Hello, i have a problem with the configuration file in config/snappy.php
programming in windows i have this configuration, work really good, the problem is when i put the code in my production app in linux, the configuration is not the same....

```
<?php

return array(
    'pdf' => array(
        'enabled' => true,
       'binary' => '"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe"',       
       //'binary' => '"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf"',
        'options' => array(),
    ),
    'image' => array(
        'enabled' => true,
        'binary' => '"C:\Program Files\wkhtmltopdf\bin\wkhtmltoimage.exe"',
        'options' => array(),
    ),
);
```

I try with this configuration but is not working...

``` 'binary'  => '/usr/local/bin/wkhtmltopdf-amd64', ```

and with this line too 

``` 'binary' => base_path('vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64'), ```

but is not working...

have ubuntu 
php 7.0
laravel 5.5

Thanks

**Comment by hkp22** [comment]
Today, I have published tutorial on this package. I have explained it in Ubuntu OS. And it has worked fine for me. 
I think there must be an issue with the path of the binary file.
You should watch this [Laravel-snappy tutorial](https://www.youtube.com/watch?v=P43fuBbmD1c), You might find the issue with your installation.

**Comment by hkp22** [comment]
Today, I have published a tutorial on this package. I have explained it in Ubuntu OS. And it has worked fine for me. 

I think there must be an issue with the path of the binary file.

You should watch this **[Laravel-snappy tutorial](https://www.youtube.com/watch?v=P43fuBbmD1c)**, You might find the issue with your installation.
