### ISSUE TITLE
0.2 should support Laravel 4.* as well

### ISSUE THREAD

**Issue by johnnycaol** [barryvdh/laravel-snappy#38]
It looks like version 0.2 only supports Laravel 5.0.\* while it should support 4.\* as well.
There is a bug in 0.1.\* on Laravel 4.\* (Response not found) so I guess the best option would be to support Laravel 4.\* in version 0.2.

Here is the error I got when I tried to update to version 0.2:
![screen shot 2015-02-03 at 16 43 02](https://cloud.githubusercontent.com/assets/3135448/6030194/d09551d4-abc3-11e4-80eb-16a476d22fbe.png)

**Comment by barryvdh** [comment]
Better just fix it in 0.1. what commit solved it?

**Comment by johnnycaol** [comment]
This one `61026f119581f7d6677962e0538404d929b2eb44` from @grahammccarthy Thank you!

**Comment by barryvdh** [comment]
Okay you can use 0.1.x@dev untill it's tagged.

**Comment by johnnycaol** [comment]
Hey @barryvdh Thanks for the reply. I tried to use 0.1.x@dev, but it seems the bug is not fixed there.

**Comment by barryvdh** [comment]
What is the error exactly?

**Comment by johnnycaol** [comment]
![screen shot 2015-02-05 at 10 14 46](https://cloud.githubusercontent.com/assets/3135448/6062712/dfee42e6-ad1f-11e4-99ec-c31af2cb18cc.png)

**Comment by barryvdh** [comment]
But why don't you have a Response class?

**Comment by johnnycaol** [comment]
I have, but i looks like it needs some reference. like in https://github.com/barryvdh/laravel-snappy/commit/61026f119581f7d6677962e0538404d929b2eb44

**Comment by barryvdh** [comment]
I've fixed it like this: https://github.com/barryvdh/laravel-snappy/commit/ffd67955f9112ad6c8e76c0972b761c14f4db793

**Comment by johnnycaol** [comment]
It seems 0.1.x@dev still requires 5.0 on packagist.
![screen shot 2015-03-11 at 15 08 42](https://cloud.githubusercontent.com/assets/3135448/6604693/934915f0-c800-11e4-9e7c-266167c0f992.png)

**Comment by barryvdh** [comment]
Fixed
