### ISSUE TITLE
Css display: grid not work

### ISSUE THREAD

**Issue by temmy-virtuoso** [barryvdh/laravel-snappy#383]
Hi i have problem with css syntax display: grid when i added this script it doesnt work

 ```
ul {
            display:grid;
            grid-template-columns: repeat(2, auto);
            grid-template-rows: repeat(6, auto);
        }
```
Any solution about this problem?

**Comment by TimFoerster** [comment]
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3661

**Comment by LouisVdwl** [comment]
Take a look here it works https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1522#issuecomment-34928787
