### ISSUE TITLE
Unable to convert Hindi language HTML to PDF

### ISSUE THREAD

**Issue by concetto-saurabh** [barryvdh/laravel-snappy#385]
I m translating the Hindi language report to PDF.
The project is on the Linux server.
I m unable to convert the Hindi language report to PDF

**Comment by veed76** [comment]
Hi @concetto-saurabh 
It's working for me: https://prnt.sc/s2rx9u
Set the meta tags in your HTML
```
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
```

**Comment by concetto-saurabh** [comment]
@veed76 
I am facing these issue in live Linux Server
Do you have the solution for that..?

**Comment by NishantTadvi** [comment]
I have faced this issue before and its related not having fonts installed for hindi(other langauge) on linux system you need to install it,

for ubuntu-
$ apt-cache search font
this command will give you list of font find suitable once and install it by
$ sudo apt-get install {font_name}

**Comment by dishanilang** [comment]
Hi,
I am trying to translate gujarati lang. report to PDF. It works perfectly fine in my local xampp server but when I uploaded my code on server, It does not print gujarati font in PDF.
Can anyone help me in this?

**Comment by govindtotla** [comment]
I am facing the same issue with Hindi Unicode Font. I have a simple HTML with some static Hindi language content in HTML file. I am trying to generate a pdf (Export pdf) but hindi characters are replaced with ?????? ?????. 
<p>नमस्ते, यह हिंदी पाठ है।</p>

If you use this HTML p tag on [pdfcroud ](https://pdfcrowd.com/) it will generate the correct PDF file.
I did not found anything which can solve this issue.
