### ISSUE TITLE
line break before element if added with @include

### ISSUE THREAD

**Issue by leicha2** [barryvdh/laravel-snappy#389]
Hi,
there seems to be an error with ```@include``` when using it inside blade files thats used for pdf generation with snappy.
```@include``` adds a line break before the included element.
For example if there is a code:
```html
<h2>header</h2>
<hr style="border: 2px solid red;" width="60%">
```
it works as needed, but if i add ```<hr>``` element there with ```@include```
```html
<h2>header</h2>
@include('page.with.hrelement')
```
there now is a linebreak/empty line between ```<h2>``` and ```<hr>``` elements. 
Margins and paddings ar set to 0.

**Comment by ahuggins** [comment]
What is the error?
