### ISSUE TITLE
margin in centimeter

### ISSUE THREAD

**Issue by KdamPrai** [barryvdh/laravel-snappy#390]
How can we set margin in centimeter?

`PDF::loadView('export_pdf', compact('data'))`
`        ->setOrientation('landscape')`
`        ->setOption('page-size', 'A4')`
`        ->setOption('margin-bottom', 1)`
`        ->setOption('margin-left', 2.5)`
`        ->setOption('margin-right', 0.5)`
`        ->setOption('margin-top', 1)`
`        ->download('data.pdf'); `

**Comment by MedouanyTaoufik** [comment]
wkhtmltopdf uses millimeter (mm) as a unit, so multiply your values (in centimeter) by 10 to get it in mm.

**Comment by MedouanyTaoufik** [comment]
Add unit to the value
`->setOption('margin-bottom', '1cm')`
or just multiply the values by 10 to convert it to millimeter (mm)
