### ISSUE TITLE
PDF header and footer laravel snappy

### ISSUE THREAD

**Issue by RaniaLM** [barryvdh/laravel-snappy#391]
hello! I have a problem with including footer in laravel snappy

$pdf = \PDF::loadView('sales.sale_form1', [
            'sale' => $sale, 'items' => $items, 'client' => $client
        ])->setOption('footer-html', route('pdf.footer'));

I use this code but it does not include the footer

**Comment by RaniaLM** [comment]
$headerHtml = view()->make('sales.header')->render();
        $footerHtml = view()->make('sales.footer')->render();
        $pdf = \PDF::loadView('sales.sale_form1', [
            'sale' => $sale, 'items' => $items, 'client' => $client
        ])->setOption('footer-html', $footerHtml);

I used this method too

**Comment by barryvdh** [comment]
You need to pass an (absolute) URL to the footer/header. So render it through a route.

**Comment by RaniaLM** [comment]
@barryvdh  how pls?

**Comment by barryvdh** [comment]
Create a route that renders the footer html and pass that as option.

**Comment by eradionov** [comment]
Has anyone solved this issue?
Seems nothing works and it does not even work if URL is passed

**Comment by 4rnol** [comment]
$footerHtml= '<div style="bottom: 0; width: 100%; text-align: center; font-size: 10px; color: #000; padding: 10px 0; border-top: 1px solid #000;">
                        <p style="margin: 0;">© 2021 Oltre Assicurazioni S.p.A. - P.IVA 13001840155</p>
                    </div>';
        $htmlContent = view('atc::atc-reports.creditsave-v2.report-pdf.index', [
            'report_json' => json_decode(file_get_contents($json_report)),
            'assets' => $assets,
            'atcReport' => $atcReport,
            'atcRequest' => $atcRequest
        ])->render();

        return SnappyPdf::loadHTML($htmlContent)
            ->setPaper('a4')
            ->setOption('enable-local-file-access', true)
            ->setOption('margin-bottom', '20mm')
            ->setOption('footer-html', $footerHtml)
            ->download('report-creditsafe-'.$atcReport->id.'.pdf'); 

with this works well
