### ISSUE TITLE
 It is possible to have in the same project DomPDF and laravel snappy?

### ISSUE THREAD

**Issue by AlonsoCauich** [barryvdh/laravel-snappy#392]
It is possible to have in the same project DomPDF and laravel snappy.
Since there is pdf implemented with DomPDF.
And I need to add some with graphics and I want to use laravel snappy, but without affecting the existing ones it is possible.?

---
Es posible tener en el mismo proyecto DomPDF y laravel snappy.
Dado que hay pdf implementado con DomPDF.
Y necesito añadir unos con gráficas y quiero usar laravel snappy, pero sin afectar a los existentes es posible.?

**Comment by barryvdh** [comment]
You can, but might have conflicting Facades. Ifnyoubuse the full namespace it should be fine.

**Comment by AlonsoCauich** [comment]
how can I configure the full namespace? 
Where should I modify it?
---
¿Cómo puedo configurar el espacio de nombres completo?
¿Dónde debería modificarlo?

**Comment by barryvdh** [comment]
I think the easiest is probably to add both Facades to app/config.php in the facades array, like described here: https://github.com/barryvdh/laravel-snappy#laravel
And name 1 DomPDF, the other SnappyPdf

**Comment by nusendra** [comment]
![image](https://user-images.githubusercontent.com/8466308/109911606-f7625c80-7cdc-11eb-9f35-862f9b056d47.png)

@AlonsoCauich this solves my problem

**Comment by wahhend** [comment]
I also need to add this on composer.json because PDF alias keep registering snappy even though I declare snappy as SnappyPDF

`"extra": {
        "laravel": {
            "dont-discover": [
                "barryvdh/laravel-snappy"
            ]
        }
    },`
