### ISSUE TITLE
Is it possible to change the temp directory?

### ISSUE THREAD

**Issue by priithansen** [barryvdh/laravel-snappy#4]
I could not figure out if it is possible to change the location of temp files generated?
On windows there can be some permission problems with "C:\WINDOWS\TEMP"

**Comment by wmather** [comment]
I came across this problem on my production server as the default temp directory is C:\Windows\Temp and the IUSR didn't have permission for it. It would show a blank page and error with: The exit status code '1' says something went wrong: stderr: "" stdout: "" command: C:\wkhtmltopdf\bin\wkhtmltopdf.exe --lowquality  --orientation "landscape" --page-size "a4" "C:\Windows\TEMP\knp_snappy54ae6e51708894.00613610.html" "C:\Windows\TEMP\knp_snappy54ae6e51708896.81344313.pdf"

From PHP 5.5, you have the php.ini "sys_temp_dir" setting, which you can change to somewhere that the process user has access to

**Comment by andreich1980** [comment]
@barryvdh They have tmp-dir-setter 
https://github.com/KnpLabs/snappy/blob/4e55d129d8bc5b92cb7049325929bb6cecada229/src/Knp/Snappy/AbstractGenerator.php#L554
Could you please tell me how could I change tmp folder using your package?
Tried `PDF::loadFile('http://www.github.com')->setTemporatyFolder('C:\Temp')->inline('github.pdf');`
but it says that `'Barryvdh\Snappy\IlluminateSnappyPdf' does not have a method 'setTemporatyFolder'`

**Comment by carlituxman** [comment]
try using ->setTemporaryFolder
you are using ->setTemporatyFolder('C:\Temp') (note the t instead r)

**Comment by carlituxman** [comment]
works for you @andreich1980 ?

if I use setTemporaryFolder:

PDF::loadFile('http://www.github.com')->setTemporaryFolder(storage_path('/tmp'))->save('github.pdf');

 throw error Call to undefined method Barryvdh\Snappy\IlluminateSnappyPdf::save()

**Comment by andreich1980** [comment]
@carlituxman Thanks for your answer, I haven't tried. I already use laravel-pdf package.
