### ISSUE TITLE
Binary accessing for laravel vapor serverless

### ISSUE THREAD

**Issue by shineraj94** [barryvdh/laravel-snappy#400]
Hello!,

php = 7.3
laravel = 7.2
 
Is there any support for accessing binaries other than vendor folder or any temporary folder? 
Because I am using Laravel Vapor & they are not permitting to touch vendor folder in a serverless concept,
Any support for Laravel vapor ?

**Comment by erictet** [comment]
Hi there,

I'm also having the same issue. The error message is along the lines of:
```
The exit status code '127' says something went wrong:
stderr: "sh: /tmp/var/task/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64: Permission denied
```

Currently using [DomPDF ](https://github.com/barryvdh/laravel-dompdf)as a workaround, but would prefer Snappy in the long term.

Cheers
