### ISSUE TITLE
Random spacing between table rows

### ISSUE THREAD

**Issue by Saengsri** [barryvdh/laravel-snappy#402]
I am experiencing an issue when generating pdfs through Laravel Snappy and wkhtmltopdf. When the pdf is generated sometimes there are extra spaces between the table rows. Right now we use the table rows for our invoices, and the extra spacing occurs on big invoices with a lot line items or on small invoices with a few line items. 

Please let me know if there are any solutions to this issue. Thank you.

**Comment by TylerAHolden** [comment]
same issue

**Comment by nurasikin** [comment]
same, but currently i just use css to fix it. have not found solid solution.

**Comment by TylerAHolden** [comment]
For anyone else that stumbles upon this, I believe my solution was CSS: 
```
tr { 
    page-break-inside: avoid; 
}
```

**Comment by vishalinfyom** [comment]
> For anyone else that stumbles upon this, I believe my solution was CSS:
> 
> ```
> tr { 
>     page-break-inside: avoid; 
> }
> ```

@TylerAHolden Thank you so much dear, it was really really helpful, we had almost two full days to find this issue.

Thank you so much again for the fix.
