### ISSUE TITLE
wkhtmltopdf 12.6 not working with local files

### ISSUE THREAD

**Issue by schonhose** [barryvdh/laravel-snappy#408]
It seems wkhtmltopdf 12.6 now disables access to local files by default. [Stackoverflow](https://stackoverflow.com/questions/62315246/wkhtmltopdf-0-12-6-warning-blocked-access-to-file).

This can be solved by passing a command line parameter `--enable-local-file-access`.

Version 12.6 does not work currently if local files are needed, however, changing to 12.5 works for now.

**Comment by lucas-santana** [comment]
I had the same problem on Windows x64 machine. 

You have to use the **public_path()** method to load yours assets.

wkhtmltopdf disables local file access by default in the 0.12.6 version.

Add the '**enable-local-file-access**' option in the config\snappy.php: 

    'pdf' => [
            'enabled' => true,
            'binary'  => env('WKHTML_PDF_BINARY', '/usr/local/bin/wkhtmltopdf'),
            'timeout' => false,
            'options' => [
                'enable-local-file-access' => true,
                'orientation'   => 'landscape',
                'encoding'      => 'UTF-8'
            ],
            'env'     => [],
        ],
    
        'image' => [
            'enabled' => true,
            'binary'  => env('WKHTML_IMG_BINARY', '/usr/local/bin/wkhtmltoimage'),
            'timeout' => false,
            'options' => [
                'enable-local-file-access' => true,
                'orientation'   => 'landscape',
                'encoding'      => 'UTF-8'
            ],
            'env'     => [],
        ],
I'm using 0.12.6 on Windows x64 and works fine.

**Comment by schonhose** [comment]
yes, you are correct. Passing the `enable-local-file-access` variable using the snappy configuration will fix this error. I wonder if this option should be added by default or at least mentioned in the docs.
