### ISSUE TITLE
header-html and footer-html options

### ISSUE THREAD

**Issue by dereckmartin** [barryvdh/laravel-snappy#41]
Can you clarify how to use the options header-html and footer-html?  Is this a blade template, actual HTML text, or a path to a html file somewhere.

**Comment by juniorrosul** [comment]
I tried this, but without success:
```php
return \PDF::loadHTML($view)
			->setPaper('a5')
			->setOption('header-html',$header)
			->setOption('footer-html',$footer)
			->stream('report.pdf');
```

Header and Footer are renderized with success.

**Comment by juniorrosul** [comment]
now i have made some modifications in my code:

in the controller i have created a function to generate a temporary file in the controller:

```php

	/**
     * Creates a temporary file.
     * The file is not created if the $content argument is null
     *
     * @param string $content   Optional content for the temporary file
     * @param string $extension An optional extension for the filename
     *
     * @return string The filename
     */
    protected function createTemporaryFile($content = null, $extension = null){
    	$filename = rtrim(sys_get_temp_dir(), DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR . uniqid('easymed_emr', true);

    	if (null !== $extension) {
    		$filename .= '.'.$extension;
    	}

    	if (null !== $content) {
    		file_put_contents($filename, $content);
    	}

    	$this->temporaryFiles[] = $filename;

    	return $filename;
    }
```
the function above was extracted from AbstractGenerator from Knp Snappy
and than i call this function in \PDF::loadHTML: 

```php
return \PDF::loadHTML($view)
			->setPaper('a5')
			->setOption('header-html',$this->createTemporaryFile($header,'html'))
			->setOption('footer-center',utf8_decode('Página [page] de [topage] - Impresso em '.date('\ d/m/Y\ \ \à\s\ H:i')))
			->stream('report.pdf');
```

this temp file was created in system temp file:
```
C:\Users\username\AppData\Local\Temp
```

**Comment by barryvdh** [comment]
So those options require the full path name? Perhaps I can create a simple helper method for this to load a view or something. Also, isn't that method available already, without having to copy it?

**Comment by juniorrosul** [comment]
You can create a route, but my route was protected by auth and the wkhtmltopdf cant load the page.

**Comment by slickorange** [comment]
Not sure if I am missing something about your requirements - but simply creating my header as an html file and then doing this, did the trick:

`$pdf->loadView('quote.rendered_blockquote', ['quote' => $quote])
		->setOption('header-html', url().'/header.html');`

**Comment by MeiRct** [comment]
@slickorange There is a clear preference to avoid a creation of static html files. 
That's why the modern frameworks have routes that render views, without a need of single files existence like in the past.

@barryvdh It would be very useful to have an ability to use a view (or even better- a partial), together with `header-html` and `footer-html` options. Do you think it's possible and not too hard to implement?

@juniorrosul Can you please provide some more info about your temporary file approach? Where did you put the `createTemporaryFile()` function? Do you store a plain HTML in `$content`, and how do you generate it?

**Comment by juniorrosul** [comment]
@MeiRct, sorry for the long time, here the answers:

1. i put ```createTemporaryFile()``` function in BaseController
1. you can generate plain HTML using ```$content = \View::make('template')->render();```

**Comment by amritshrestha** [comment]
simply you can put header.html in storage folder away from general public and access it using `storage_path('header.html')` and use juniorrosul 's first answer.
```
$header = storage_path('header.html')
... ->setOption('header-html', $header) .... ```

you can take a look at [wkhtmltopdf file](http://wkhtmltopdf.org/usage/wkhtmltopdf.txt) for further info.

**Comment by pawlakzn** [comment]
`    ->setOption('header-html', $header);`

Just remember that your header/footer need to have a DOCTYPE

Add
`<!DOCTYPE html>`
at the beginning of header/footer and 

```
 $pdf = PDF::loadHTML($content)
              ->setPaper('a4')
                ->setOption('header-html', $header);
```

will work perfectly.

**Comment by francisortega** [comment]
`->setOption();` doesn't seem to exist. All I see is setOptions().

Are there any other ways?
