### ISSUE TITLE
Insert image in pdf

### ISSUE THREAD

**Issue by radcloudcorp** [barryvdh/laravel-snappy#414]
Hello good afternoon. I've tried several ways to insert an image in the pdf and I can't. I've tried it with some versions of snnapy and wkhtmltopdf and I couldn't. I saw a video on youtube at https://www.youtube.com/watch?v=P43fuBbmD1c&t=13s where the person can do it without complications. I try to do it in the same way even with the same photo link that he uses http://placekitten.com/130/130 but the error is and the pdf is not generated. I would be very grateful for any help.

Test with snnapy 0.4.6 and 0.4.8, and wkhtmltopdf versions 0.12.5 and 0.12.6

**Comment by ChaplyginWezom** [comment]
@radcloudcorp Hi! Have you tried to set _'enable-local-file-access'_ option to _true_ and print image using real path to it instead of url?

`PDF::setOption('enable-local-file-access', true)->loadView('pdf.example', $data);`

`<img src="/c/real-path-to-file/image.png">`

**Comment by mohamedjagne** [comment]
hhhh

**Comment by hammadshah01** [comment]
When you print PDF without image it throw some error to use images in PDF file then you can modify your controller and blade file

//FOR CONTROLLER
PDF::setOption('enable-local-file-access', true)->loadView('pdf.example', $data);


//FOR BLADE (**_PLZ USE  PUBLIC_PATH() INSTEAD OF ASSET()_** )
<header>
    <img src="{{ public_path('images/print-logo.png') }}" width="450px" height="auto" alt="">
</header>

**Comment by hammadshah01** [comment]
> @radcloudcorp Hi! Have you tried to set _'enable-local-file-access'_ option to _true_ and print image using real path to it instead of url?
> 
> `PDF::setOption('enable-local-file-access', true)->loadView('pdf.example', $data);`
> 
> `<img src="/c/real-path-to-file/image.png">`

yes thats legit use public_path('you file loacal address')
