### ISSUE TITLE
Declaration of getFileContents($filename) must be compatible with getFileContents(string $filename): string

### ISSUE THREAD

**Issue by hotslab** [barryvdh/laravel-snappy#417]
I am getting this error 

```Declaration of Barryvdh\Snappy\IlluminateSnappyPdf::getFileContents($filename) must be compatible with Knp\Snappy\AbstractGenerator::getFileContents(string $filename): string```

when trying to run the following function:

```
$pdf = PDF::loadHTML($html);
```
I am using version 0.4.8 and my php version is 7.4.14.

My hunch is the error is occuring because of the new Typed Properties feature that was recently added in php 7.4. Would welcome if ths issue was quickly resolved.

**Comment by craftyshaun** [comment]
This is also triggered during a dump using barryvdh/laravel-ide-helper during a composer update.

```
php artisan ide-helper:generate
PHP Fatal error:  Declaration of Barryvdh\Snappy\IlluminateSnappyPdf::getFileContents($filename) must be compatible with Knp\Snappy\AbstractGenerator::getFileContents(string $filename): string in /home/vagrant/code/app.cslocal.dev/vendor/barryvdh/laravel-snappy/src/IlluminateSnappyPdf.php on line 27
 Script php artisan ide-helper:generate handling the post-update-cmd event returned with error code 255
``
Both packages are by @barryvdh so it should be easily traceable. 

This broke after a composer update so some new code was pulled down somewhere but I can't work out where to pin the versions to resolve

**Comment by craftyshaun** [comment]
I've edited the source of as per #410 and it stops the PHP Error.
@barryvdh can you please merge when your ready
