### ISSUE TITLE
Can i use laravel-dompdf and laravel-snappy together in same laravel project ?

### ISSUE THREAD

**Issue by ashanUD** [barryvdh/laravel-snappy#418]
Can i use laravel-dompdf and laravel-snappy together in same laravel project ? because i have to work with simple dompdf and complcated html which use snappy. i need to have both in same laravel prject. but the PDF class clashing when using both.

**Comment by mralston** [comment]
Yes, you can and it works fine. I'm transitioning a project at the moment and have both libraries installed. If you're using the facade aliases then you need to make sure you give one or other of them a different alias name in your `config/app.php` file. If you're using both from within the same class, then make sure you give them different names when you import them with your `use` statements or provide the fully qualified class names.

**Comment by nusendra** [comment]
@ashanUD me also got this problem. when i use both dompdf with snappy together in one project, i can't call dompdf. It always call snappy instead of dompdf

**Comment by nusendra** [comment]
![image](https://user-images.githubusercontent.com/8466308/109911678-1365fe00-7cdd-11eb-8282-cd30b39f6318.png)

@ashanUD this solves my problem. Just change PDF to DomPDF.
