### ISSUE TITLE
Bootstrap grid system

### ISSUE THREAD

**Issue by rkelly92** [barryvdh/laravel-snappy#42]
I found a couple of post (for instance, https://laracasts.com/discuss/channels/general-discussion/pdfs-and-laravel) suggesting that bootstrap's grid system worked with snappy. However, I've had no success trying to do this. The font does change and classes like text-center also do have an effect, but cols don't and they're the main reason I'm trying to use bootstrap.

**Comment by rkelly92** [comment]
Upon further research (http://stackoverflow.com/questions/19705880/converting-twitter-bootstrap-page-into-pdf-with-wkhtmltopdf-span-issue) I found that using xs cols does work.

**Comment by yakuzaaaa** [comment]
This problem still persists, using col-xs-* still does not work.

**Comment by mochadwi** [comment]
Thank you very much for making this clear 👍 @ghost

**Comment by marcelogarbin** [comment]
Very good. Thank's
