### ISSUE TITLE
The exit status code '127'

### ISSUE THREAD

**Issue by thetnswe** [barryvdh/laravel-snappy#426]
I am still having the following error after everything is installed including libxrender1 and libfontconfig1. wkhtmlto libraries are already copied to "/usr/bin" folder and already give the execute permissions. Don't know what am I missing.. Somebody please help me out.
chmod +x /usr/bin/wkhtmltoimage-amd64
chmod +x /usr/bin/wkhtmltopdf-amd64

/usr/bin/wkhtmltopdf-amd64 http://google.com google.pdf is working fine running from shell

```
  $pdf = App::make('snappy.pdf.wrapper');
  $pdf->loadHTML('<h1>Test</h1>');
  return $pdf->download('test.pdf');
```
The above code also working fine.. 

It's happening in 
```
return PDF::loadFile('https://google.com')->download('test.pdf'); and 
return PDF::loadFile('http://google.com')->download('test.pdf'); and 
return PDF::loadView('contact_us', [])->download('invoice.pdf'); 
```

and other features as well      

The exit status code '127' says something went wrong: stderr: "/usr/bin/wkhtmltopdf-amd64: /opt/lampstack-7.4.16-1/common/lib/libuuid.so.1: no version information available (required by /lib/x86_64-linux-gnu/libfontconfig.so.1) /usr/bin/wkhtmltopdf-amd64: symbol lookup error: /lib/x86_64-linux-gnu/libfontconfig.so.1: undefined symbol: FT_Done_MM_Var " stdout: "" command: /usr/bin/wkhtmltopdf-amd64 --lowquality --encoding 'UTF-8' '/tmp/knp_snappy6072e717e2efe5.21499310.html' '/tmp/knp_snappy6072e717e2f853.41538873.pdf'.

**Comment by shunhua** [comment]
解决了吗？同样的问题

**Comment by richardjacob** [comment]
![image](https://github.com/barryvdh/laravel-snappy/assets/88606372/66443aee-cdb2-45ed-a343-9f1b76e1574a)

any solutions?
