### ISSUE TITLE
Convert Graph to PDF 

### ISSUE THREAD

**Issue by u-stack** [barryvdh/laravel-snappy#435]
i am converting graph to pdf in laravel facing this problem
![pdf](https://user-images.githubusercontent.com/70132352/119193828-a839f580-ba9b-11eb-8dff-8578fc6efacc.PNG)

**Comment by raul-mg** [comment]
Try change binary path to:   "c:\wkhtmltopdf\wkhtmltopdf" with this "\" slash and without ".exe"
