### ISSUE TITLE
issues loading css

### ISSUE THREAD

**Issue by Kobershan** [barryvdh/laravel-snappy#437]
im using laravel 8 with php 8 and im using tailwind with inline editing. 

When the pdf is opened it doesn't use any of the css provided.

**Comment by RickZurc** [comment]
Same problem

**Comment by ousid** [comment]
many you want to add you `CSS` inside style tag inside `head`

Or if your styles doesn't look right you must double check the autoprefix css.

Take a look here if you want to add autoprefix css
https://autoprefixer.github.io/
