### ISSUE TITLE
Error: Failed to load http://www.google.com/, with network status code 3 and http status code 0 - Host www.google.com not found Error

### ISSUE THREAD

**Issue by raul-mg** [barryvdh/laravel-snappy#442]
Binaries installed and test from console ---- check
Laravel 8 with barryvdh/laravel-snappy installed ---- check
try this example: 

Route::get('/test', function () {
    return PDF::loadFile("http://www.google.com")->inline('test.pdf');
});

not working, this is laravel log lines:

2021-07-10 02:42:13] local.ERROR: The exit status code '1' says something went wrong:
stderr: "Loading pages (1/6)
[>                                                           ] 0%
[======>                                                     ] 10%
Error: Failed to load http://www.google.com/, with network status code 3 and http status code 0 - Host www.google.com not found
Error: Failed loading page http://www.google.com (sometimes it will work just to ignore this error with --load-error-handling ignore)
Exit with code 1 due to network error: HostNotFoundError
"
stdout: ""
command: D:\wkhtmltopdf\bin\wkhtmltopdf --lowquality --orientation "landscape" --encoding "UTF-8" --enable-local-file-access "http://www.google.com" "d:\Users\raul\AppData\Local\Temp\knp_snappy60e90904d8a707.05853766.pdf". {"userId":1,"exception":"[object] (RuntimeException(code: 1): The exit status code '1' says something went wrong:
stderr: \"Loading pages (1/6)
[>                                                           ] 0%
[======>                                                     ] 10%
Error: Failed to load http://www.google.com/, with network status code 3 and http status code 0 - Host www.google.com not found
Error: Failed loading page http://www.google.com (sometimes it will work just to ignore this error with --load-error-handling ignore)
Exit with code 1 due to network error: HostNotFoundError
\"
stdout: \"\"
command: D:\\wkhtmltopdf\\bin\\wkhtmltopdf --lowquality --orientation \"landscape\" --encoding \"UTF-8\" --enable-local-file-access \"http://www.google.com\" \"d:\\Users\
aul\\AppData\\Local\\Temp\\knp_snappy60e90904d8a707.05853766.pdf\". at D:\\Workspace\\Clientes\\Tribunal\\proyectos\\cedulasestadisticas\\cedulas\\vendor\\knplabs\\knp-snappy\\src\\Knp\\Snappy\\AbstractGenerator.php:381)
[stacktrace]

I test from console and binary its working fine

**Comment by manggaraaaa** [comment]
same problem..

**Comment by TidianeRolland** [comment]
I have the same problem
