### ISSUE TITLE
Question for documentation: What's the best alternative for Laravel 8?

### ISSUE THREAD

**Issue by dave-driesmans** [barryvdh/laravel-snappy#449]
I understand laravel-snappy is only Laravel 5.
DOMPdf gives me many font troubles that i never experienced with Laravel Snappy. 

What would be to way forward for people that want to upgrade?

**Comment by zarulizham** [comment]
My current project is Laravel 8. Works as expected.

**Comment by barryvdh** [comment]
It should work fine for Laravel 8
