### ISSUE TITLE
getFileContents not compatible with knplabs/knp-snappy 1.3

### ISSUE THREAD

**Issue by andreshg112** [barryvdh/laravel-snappy#450]
This package:
![image](https://user-images.githubusercontent.com/15859884/138327831-6ad99e2e-3022-4ce7-9e8c-316aead0b037.png)

Other package:
![image](https://user-images.githubusercontent.com/15859884/138327967-8497a354-8d50-4a78-b653-388c03bee730.png)

This package has knplabs/knp-snappy: ^1, so 1.3 can be installed, but it has problems.

**Comment by alyas20** [comment]
also have same problem with this
