### ISSUE TITLE
I followed the solution presented above and the got the following error:

### ISSUE THREAD

**Issue by KasunDA** [barryvdh/laravel-snappy#452]
i get the same issue .
The file 'c:/openserver/userdata/temp\knp_snappy61b2f28f1469b6.91199185.pdf' was not created (command: C:\OpenServer\domains\bitool-web-sk\vendor/wemersonjanuario/wkhtmltopdf-windows/bin/64bit/wkhtmltopdf --lowquality "c:/openserver/userdata/temp\knp_snappy61b2f28f1447b7.69600953.html" "c:/openserver/userdata/temp\knp_snappy61b2f28f1469b6.91199185.pdf").

I followed the solution presented above and the got the following error:
The file 'C:\Users\razaz\AppData\Local\Temp\knp_snappy5d7f74227dbb83.62339559.pdf' was not created (command: C:\xampp\htdocs\EDO_Roster\vendor\wemersonjanuario\wkhtmltopdf-windows\bin\64bit\wkhtmltopdf --lowquality --enable-javascript --javascript-delay "5000" --enable-smart-shrinking --no-stop-slow-scripts "C:\Users\razaz\AppData\Local\Temp\knp_snappy5d7f74227d6c75.83364670.html" "C:\Users\razaz\AppData\Local\Temp\knp_snappy5d7f74227dbb83.62339559.pdf").

_Originally posted by @iraxaxaidi in https://github.com/barryvdh/laravel-snappy/issues/60#issuecomment-531741763_

**Comment by KasunDA** [comment]
The file 'myfile.pdf' was not created (command: C:\OpenServer\domains\bitool-web-sk\vendor/wemersonjanuario/wkhtmltopdf-windows/bin/64bit/wkhtmltopdf --lowquality --margin-bottom "0" --orientation "landscape" --page-size "a4" "c:/openserver/userdata/temp\knp_snappy61b2f54d0de489.92918382.html" "myfile.pdf").

**Comment by alexhackney** [comment]
Did you get an error or was it just not created that you can see?

One thing I see just looking at the code, is that the paths are weird.

```
"c:/openserver/userdata/temp**\**knp_snappy61b2f54d0de489.92918382.html"
Slash flipped

"myfile.pdf"
Not a full path, so it's probably creating it where ever the command originates from, which may not be what you're expecting.
```
