### ISSUE TITLE
Image opacity

### ISSUE THREAD

**Issue by tibelchior** [barryvdh/laravel-snappy#453]
Hello, it doesn't matter what type of image I use, it is always displayed with a very low opacity.

![download (2)](https://user-images.githubusercontent.com/5125117/147004594-b11317bd-e50f-478b-af4c-f38609a0d6cc.jpg)

I read the configurations for wkhtmltoimage but there's nothing about image opacity.
I also found someone else with the same problem on Stackoverflow, but the answers there doesn't fix this issue.

Is this a known problem or have I missed something?

**Comment by alexhackney** [comment]
@tibelchior what does the original image look like? Is it a transparent image? You would usually set opacity in the css for the view or html you're loading.

**Comment by tibelchior** [comment]
@alexhackney thanks for the reply, but there's no transparency in the original image. This only happens with the PDF.

**Comment by alexhackney** [comment]
@tibelchior weird, I just started using this package and haven't seen that yet.

Alex
