### ISSUE TITLE
Even though I run the command chmod +x /usr/local/bin/wkhtmltopdf, I got permission error

### ISSUE THREAD

**Issue by aknEvrnky** [barryvdh/laravel-snappy#457]
The exit status code '126' says something went wrong: stderr: "sh: /usr/local/bin/wkhtmltopdf: Permission denied ".
This is what I get the error.
I'm using plesk@centos 7 machine. I've installed wkhtmltopdf through yum install.
I've run chmod +x command, chown user wkhtmltopdf command, rebooted the machine but still can't use the program.

**Comment by alexhackney** [comment]
@aknEvrnky what happens when you run 
```
/usr/local/bin/wkhtmltopdf -V
```

On the server?
