### ISSUE TITLE
The exit status code '1' says something went wrong: stderr: "The system cannot find the path specified. " 

### ISSUE THREAD

**Issue by umairali** [barryvdh/laravel-snappy#46]
I m using this code in controller but i m facing this error

```
public function getPDF()
{
    $pdf = PDF::loadView('ab');
    return $pdf->download('invoice.pdf');
}
```

error

The exit status code '1' says something went wrong: stderr: "The system cannot find the path specified. " stdout: "" command: /usr/local/bin/wkhtmltopdf --lowquality "C:\Users\Admin\AppData\Local\Temp\knp_snappy552137b1a973a8.95135225.html" "C:\Users\Admin\AppData\Local\Temp\knp_snappy552137b1aa4969.49985920.pdf". 

![capture](https://cloud.githubusercontent.com/assets/5318005/6996988/c4cda670-dbc1-11e4-9011-931ce427fba4.PNG)

**Comment by barryvdh** [comment]
did you install wkhtml2pdf in that dir? If not, install It there or change the path in the config.

**Comment by umairali** [comment]
Please check this

![capture1](https://cloud.githubusercontent.com/assets/5318005/6997066/be4c9bcc-dbc5-11e4-8210-4bf9a20859ac.PNG)

**Comment by barryvdh** [comment]
Yeah so publish the config and change the location as described.

**Comment by umairali** [comment]
Thanks but now i am facing this error

![capture2](https://cloud.githubusercontent.com/assets/5318005/7001399/41359102-dc51-11e4-83e2-cc783eb95508.PNG)

**Comment by umairali** [comment]
I am using XAMP on windows 8.1

**Comment by umairali** [comment]
My issue solved with command

        'binary' => 'C:/wkhtmltopdf/wkhtmltopdf.exe',

When i am using this commands i m facing error 

        'binary' => base_path('vendor/h4cc/wkhtmltopdf-i386/bin/wkhtmltopdf-i386')

I think this command is for linux only?

**Comment by muhghazaliakbar** [comment]
i have changed on my config but still error
![screenshot_120](https://cloud.githubusercontent.com/assets/8321936/8394946/68c719a8-1d82-11e5-8527-86c181fe3c2f.png)

**Comment by umairali** [comment]
which operating system you are using

**Comment by muhghazaliakbar** [comment]
Windows 8.1 and Xampp 3.2.1

**Comment by umairali** [comment]
cut all files from wkhtmltopdf bin folder from program files and create an new folder in C drive and paste bin folder files in this folder and use this link

C:/wkhtmltopdf/wkhtmltopdf.exe

**Comment by umairali** [comment]
Download and install wkhtmltopdf 

Windows (MSVC 2013)	32-bit / 64-bit	for Windows Vista or later; bundles VC++ Runtime 2013

from this link
http://wkhtmltopdf.org/downloads.html

now copy wkhtmltopdf folder from program files and paste in c:/ drive now copy all the files from inner wkhtmltopdf folder and paste in c:/wkhtmltopdf folder

like this

![wkhtmltopdf](https://cloud.githubusercontent.com/assets/5318005/8423758/d185ff78-1f07-11e5-904b-c8ae92cebe11.PNG)
 
now use this path in laravel snappy config file

'binary' => 'C:/wkhtmltopdf/wkhtmltopdf.exe',

![config](https://cloud.githubusercontent.com/assets/5318005/8423774/2737cc12-1f08-11e5-9c34-92f74d890220.PNG)

**Comment by muhghazaliakbar** [comment]
Owh nice, works xD i forget to place to C:\ 

app cannot read whitespace C:\Program Files. thanks

**Comment by kenny26** [comment]
I'm having the exact same issue, if I follow umairali guide, it works.. However I want to install it using composer, not by installation exe file.. Install using composer doesn't generate any .exe file, and the file produce this error. Any suggestion is appreciated..

**Comment by NassarX** [comment]
@umairali Really Thank you for you answer it works prefectly now :)

**Comment by umairali** [comment]
You are very welcome. :)

**Comment by abdullahrahimee** [comment]
i have the same problem as above. i am using laravel 5 and windows 8.1. i couldnt find config.php file in laravel 5. what do i have to do?

**Comment by umairali** [comment]
check snappy.php file in config folder

**Comment by NassarX** [comment]
You can publish the config-file with

php artisan vendor:publish

**Comment by arryanggaputra** [comment]
can we use binary config from the vendor? I don't want to install to my computer

**Comment by avinashi37** [comment]
hey umairali,

I have performed steps exactly said by you but I still get the same error

I have installed wkhtmltox-0.12.3-dev-79ff51e_msvc2013-win64.exe

in C: drive and also set path in 
![capture](https://cloud.githubusercontent.com/assets/15361976/12256532/c23d353e-b923-11e5-9fab-060e9c42d3f7.PNG)

but still same error

![capture1](https://cloud.githubusercontent.com/assets/15361976/12256547/e13517ae-b923-11e5-9d8a-c4a774d9f363.PNG)

please help

**Comment by umairali** [comment]
Find snappy file in config folder and change pdf binary path

'binary' => 'C:/wkhtmltopdf/wkhtmltopdf.exe',

**Comment by avinashi37** [comment]
Yah , my mistake....
After changing snappy.php in vendor folder using publish command changes automatically done in config/snappy.php

**Comment by jsgspotifi** [comment]
umairali, could you do a little tutorial, or steps on how to install the snappy. I found the instructions in the main website confusing. Thank you so much, this would be a great help!

**Comment by kailash10jangir** [comment]
I have the same error also. i am use this 'binary' => 'C:/wkhtmltopdf/wkhtmltopdf.exe', in my snappy.php  by using this my whole website is not working. what should i do please help me
![kk](https://cloud.githubusercontent.com/assets/16118278/21418392/f4889d98-c846-11e6-8719-7f7343348433.png)

**Comment by umairali** [comment]
Can you share screenshot of your wkhtmltopdf folder in c drive

**Comment by sachinkumar121** [comment]
Change the content of snappy.php file as below(double quotes in single quotes)

'binary' => '"C:/wkhtmltopdf/wkhtmltopdf.exe"',

**Comment by Dictator1999** [comment]
Everything looks good for windows local server. But would you please tell us about real server where may do not available wkhtmltopdf. I like to use composer to install h4cc/wkhtmltoimage-i386 inside my vendor (project folder). It does not work in local server as well as real server. Its 32-bit operating system.

**Comment by msslgomez** [comment]
Having trouble with these commands, if I don't do them I get this same error but Laravel cmd is not letting me, says 'cp' is not recognized as an internal or external command
```
cp vendor/h4cc/wkhtmltoimage-amd64/bin/wkhtmltoimage-amd64 /usr/local/bin/
cp vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64 /usr/local/bin/
```

How to do this on Windows or how can I fix this?

**Comment by hiren1903** [comment]
The exit status code '-1073741819' says something went wrong: stderr: "Loading pages (1/6)
 [> ] 0%
[======> ] 10%
[=======> ] 13%
Error: Failed to load http://www.google.com/jsapi, with network status code 3 and http status code 0 - Host www.google.com not found
 " stdout: "" command: C:/wkhtmltox/bin/wkhtmltopdf.exe --lowquality --enable-javascript --javascript-delay "5000" --enable-smart-shrinking --no-stop-slow-scripts

**Comment by LQTam** [comment]
> The exit status code '-1073741819' says something went wrong: stderr: "Loading pages (1/6)
> [> ] 0%
> [======> ] 10%
> [=======> ] 13%
> Error: Failed to load http://www.google.com/jsapi, with network status code 3 and http status code 0 - Host [www.google.com](http://www.google.com) not found
> " stdout: "" command: C:/wkhtmltox/bin/wkhtmltopdf.exe --lowquality --enable-javascript --javascript-delay "5000" --enable-smart-shrinking --no-stop-slow-scripts

if your blade view has an image, use public_path

**Comment by hashirhamxa** [comment]
@hirenpatel1903  did you find the mistake

**Comment by shahid23-dev** [comment]
![image](https://user-images.githubusercontent.com/107908573/178466747-e25feb9e-c843-4366-a110-d229afd2ef0a.png)

after changing the binary i got this

**Comment by Zeeshan-ali58** [comment]
I have applied almost every solution suggested by community. But i am still facing the issue. Can someone help me in this. Attached my snappy.php and wkhtmltopdf screenshots.
![Untitled](https://github.com/barryvdh/laravel-snappy/assets/72882265/fb86980d-d11b-44e6-a5b4-131383c2cb2b)
![Untitled-12](https://github.com/barryvdh/laravel-snappy/assets/72882265/51b6911c-b6e0-4594-abdd-9e75005214f1)

**Comment by Poornima1996** [comment]
hi, 
I am getting,
"The exit status code '1' says something went wrong: stderr: "The system cannot find the path specified. " stdout: "" command: /usr/local/bin/wkhtmltopdf --lowquality "C:\Users\POORNI~1\AppData\Local\Temp\knp_snappy6558567bdd7795.73450274.html" "C:\Users\POORNI~1\AppData\Local\Temp\knp_snappy6558567bddb761.92326280.pdf"."

How to solve

**Comment by sachinkumar121** [comment]
> hi, I am getting, "The exit status code '1' says something went wrong: stderr: "The system cannot find the path specified. " stdout: "" command: /usr/local/bin/wkhtmltopdf --lowquality "C:\Users\POORNI~1\AppData\Local\Temp\knp_snappy6558567bdd7795.73450274.html" "C:\Users\POORNI~1\AppData\Local\Temp\knp_snappy6558567bddb761.92326280.pdf"."
> 
> How to solve

It seems like you are using windows systems. try to run the exe natively and make sure  wkhtmltopdf exists. 

`C:/wkhtmltopdf/wkhtmltopdf.exe <file.html>`
