### ISSUE TITLE
Preparing for Laravel 9 - illuminate/filesystem

### ISSUE THREAD

**Issue by arborrow** [barryvdh/laravel-snappy#460]
I am beginning to try and see how my app is going to do in preparation for Laravel 9. I received the following feedback from composer update that I figured I would share in the hopes that it will help prepare this package for Laravel 9. 

Problem 1
    - Conclusion: don't install barryvdh/laravel-snappy v0.4.7 (conflict analysis result)
    - Conclusion: don't install barryvdh/laravel-snappy v0.4.8 (conflict analysis result)
    - illuminate/filesystem[v5.6.0, ..., 5.8.x-dev] require php ^7.1.3 -> your php version (8.0.15) does not satisfy that requirement.
    - illuminate/filesystem[v6.0.0, ..., v6.19.1] require php ^7.2 -> your php version (8.0.15) does not satisfy that requirement.
    - illuminate/filesystem[v7.0.0, ..., v7.28.4] require php ^7.2.5 -> your php version (8.0.15) does not satisfy that requirement.
    - illuminate/filesystem[v8.0.0, ..., v8.11.2] require php ^7.3 -> your php version (8.0.15) does not satisfy that requirement.
    - Root composer.json requires barryvdh/laravel-snappy ^0.4.7 -> satisfiable by barryvdh/laravel-snappy[v0.4.7, v0.4.8, 0.4.x-dev (alias of dev-master)].
    - Conclusion: don't install laravel/framework v9.0.0-beta.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.0.0-beta.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.0.0-beta.4 (conflict analysis result)
    - barryvdh/laravel-snappy 0.4.x-dev is an alias of barryvdh/laravel-snappy dev-master and thus requires it to be installed too.
    - Conclusion: don't install laravel/framework v9.0.0-beta.1 (conflict analysis result)
    - barryvdh/laravel-snappy dev-master **requires illuminate/filesystem ^5.5|^6|^7|^8** -> satisfiable by illuminate/filesystem[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev].
    - Only one of these can be installed: illuminate/filesystem[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev], laravel/framework[v9.0.0-beta.1, ..., 9.x-dev]. laravel/framework replaces illuminate/filesystem and thus cannot coexist with it.
    - Root composer.json requires laravel/framework ^9.0 -> satisfiable by laravel/framework[v9.0.0-beta.1, ..., 9.x-dev].

**Comment by jabools** [comment]
It's already in progress (#458). Initial L9 support was added in #459 :)

**Comment by arborrow** [comment]
Awesome, good to hear. I'll go ahead and close this since it is a duplicate of #458 and #459. Peace - Anthony
