### ISSUE TITLE
Docker + error the exit status code '127'

### ISSUE THREAD

**Issue by ssheduardo** [barryvdh/laravel-snappy#467]
Hi,
I uses laravel with docker, whe install the package and want generate a PDF, ever show the error 127.
`
    "message": "The exit status code '127' says something went wrong:\nstderr: \"sh: /var/www/html/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64: not found\n\"\nstdout: \"\"\ncommand: /var/www/html/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64 --lowquality --orientation 'landscape' --page-size 'a4' --footer-font-size '6' --footer-right '[page]' '/tmp/knp_snappy6221db37c4dfb2.95689427.html' '/var/www/html/public/reports/export/Sj5jTHOkii0Yi0rmmwrH.pdf'.",`

But if use Laravel without docker, not have the error.

The binary exists, in container docker I see the binary

![image](https://user-images.githubusercontent.com/1160138/156740942-bbc4d47c-6cf0-4155-8af3-e0e6f2955464.png)

Where are the error?

**Comment by OrkunAkarOctopusLabs** [comment]
add missing libs to your docker file 

[https://github.com/barryvdh/laravel-snappy/issues/68#issuecomment-314012014](url) like this
