### ISSUE TITLE
Problem with header/footer and encoding

### ISSUE THREAD

**Issue by paulocastellano** [barryvdh/laravel-snappy#47]
Hello,

i have problem with header and footer with encode:

return PDF::loadView('pdf.my_pdf', $data)
            ->setOption('encoding', 'utf-8')
            ->setPaper('a4')
            ->setOption('footer-center', 'Cabeçalho')
            ->setOption('footer-font-size', '8')
                        ->stream('my_pdf.pdf');

But always footer output is: <strong>Cabealho</strong>.

My view have:
meta http-equiv="Content-Type" content="text/html; charset=UTF-8"
Thanks

**Comment by caioladislau** [comment]
I've this same problem.

**Comment by rtfmfm** [comment]
In case you still have this problem, I selved it this way:
Create a view: 
`
<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<div style="text-align: center;">
{{ trans('msg.invoice_footer_text') }}
</div>
`

In the Controller:
`
$pdf = PDF::loadView('invoices.invoice_pdf', compact('data'))
            ->setOption('margin-top', 10)
            ->setOption('margin-left', 10)
            ->setOption('margin-right', 10)
            ->setOption('margin-bottom', 20)
            ->setOption('orientation', 'portrait')
            ->setOption('footer-font-size', 10)
            ->setOption('footer-html', view('invoices.pdfFooter'))
            ->setOption('encoding', 'utf-8')
            ->setPaper('a4'); 
`
