### ISSUE TITLE
The option '0' doesn't exist.

### ISSUE THREAD

**Issue by geraldofebrian** [barryvdh/laravel-snappy#470]
I tried to put `--disable-forms` inside snappy config but doesn't work. Tried another also didn't work.

```
'pdf' => [
        'enabled' => true,
        'binary'  => env('WKHTML_PDF_BINARY', '/usr/local/bin/wkhtmltopdf'),
        'timeout' => 60,
        'options' => ['--disable-forms'],
        'env'     => [],
    ],

```

How to solve it?

**Comment by mralston** [comment]
I believe Snappy (or Laravel Snappy) assumes the options array contains key-value pairs. As you've only passed a value, the key is 0. Also, I think it adds the -- for you, so you don't need to. It will be trying to execute something like this:

```
/usr/local/bin/wkhtmltopdf --0=--disable-forms <input> <output>
```

Try this instead:

```php
'pdf' => [
        'enabled' => true,
        'binary'  => env('WKHTML_PDF_BINARY', '/usr/local/bin/wkhtmltopdf'),
        'timeout' => 60,
        'options' => ['disable-forms' => true],
        'env'     => [],
    ],
```
