### ISSUE TITLE
Can't load header and footer

### ISSUE THREAD

**Issue by lucas-gestonauta** [barryvdh/laravel-snappy#479]
I've tried a lot of different ways to make a basic footer, but with no success, just don't load anything. After forcing an error, I could see this message: 

"The switch --footer-center, is not support using unpatched qt, and will be ignored."

When I check the version of wkhtmltopdf via terminal, it returns: wkhtmltopdf 0.12.6 (with patched qt).

The binary path of snappy.php is like this:
'binary'  => 'wkhtmltopdf',
That was the only way that works for me.

The real folder of the file is /usr/local/bin/wkhtmltopdf, but if I change the value from "wkhtmltopdf" to "/usr/local/bin/wkhtmltopdf" it returns error code 127 (not found).

If I run "/usr/local/bin/wkhtmltopdf --footer-center 'Page [page] of [topage]'  www.google.com /home/lucassouzap/test.pdf" it works perfectly rendering the footer! Even only "wkhtmltopdf --footer..." also works via terminal.

Just don't know what binary file the app is using and don't know what to do to make the footer render... 

I'm using Laravel Sail, Ubuntu 20.04 on docker.

**Comment by JerryBels** [comment]
Hey, I'm hitting the same issue, did you find a solution?
