### ISSUE TITLE
Multiple pages?

### ISSUE THREAD

**Issue by lowerends** [barryvdh/laravel-snappy#5]
For starters: thanks for the nice package, it integrates really well with Laravel.

I'm looking for a way to add pages to the generated pdf, for example by way of calling the loadView method multiple times on the same PdfWrapper object. So something like addView instead of loadView. 

Any thoughts on the feasibility of this for this package?

**Comment by ghprod** [comment]
works for me :+1:

**Comment by salacis** [comment]
For Laravel 5.x I needed to do a html entity decode like this. `{!!html_entity_decode($page->body)!!}`
[https://laracasts.com/discuss/channels/general-discussion/rendering-html-from-database-table-to-view-blade-issue-or](url)

**Comment by roni-estein** [comment]
Anyone have any luck with this in Laravel 5.5+? I've got it all set up but it just keeps rendering the first page over again. If you swap the order you load the pages in it picks the new first page and renders that. I can't quite nail down whats causing that.

```
$pages = array();

        $pages[] = \View::make('template.compression.rx.layouts.2-fax-coversheet', ['order' => $this->order, 'user' => $this->user]);
        $pages[] = \View::make('template.compression.rx.1', ['user' => $this->user]);


        //return $pages;
        $pdf = PDF::loadView('emails.empty.multi-page', ['pages' => $pages]);

        dd($pdf);
//        $pdf  = PDF::loadView('template.compression.rx.layouts.2-fax-coversheet', ['order' => $this->order, 'user' => $this->user]);
        $data = $pdf->output();

return
            $this->view('emails.empty.single')->attachData($data,'rx-'.$this->order->id),['mime' =>'application/pdf']);

```

here is the multi page email view

```

<style type="text/css" media="print">
    div.page
    {
        page-break-after: always;
        page-break-inside: avoid;
    }
</style>

@foreach($pages as $page)
    <div class="page">
        {!! html_entity_decode($page) !!}
    </div>
@endforeach

```

when I dd($pdf) it just repeats the first page for as many pages as there are. It's unexpected.

Thanks

**Comment by Luciferkalis** [comment]
@barryvdh 

i have a html content which is retrieved from database. i just add it to loadView function and the content display correctly. But when i generate PDF it will display the content only one page and second page was not generated. can u please show some example program for generated pdf with multiple content depends upon dynamic content.

Thanks.

**Comment by arnold-unified** [comment]
@roni-estein I also experienced that

> I've got it all set up but it just keeps rendering the first page over again.

the following fixed the problem for me:

```
$pages = [
    '<html>...</html>',
    '<html>...</html>'
];
$pdf->loadHTML($pages);
```

**Comment by randyhamzahh** [comment]
I am getting strange characters like this Â when trying this code  `{!! html_entity_decode($page) !!}` . How can I remove these
