### ISSUE TITLE
Problem with big images

### ISSUE THREAD

**Issue by abengardino** [barryvdh/laravel-snappy#53]
Hey guys, has anyone had trouble when including images in your PDF files? For some reason I get a broken PDF file every time I try to include my images, but it turns out OK if I exclude them.

Here are the kind of images I'm talking about:
![h_20150529_162718](https://cloud.githubusercontent.com/assets/2564290/7925663/190bda5a-089e-11e5-8db4-b3a77fc6c801.jpg)

It also works fine if I save my HTML to a file and use wkhtmltopdf from the command line. Any ideas?

Win7 64 bits - wkhtmltopdf 0.12.2.2

**Comment by JeroenVanOort** [comment]
What do you mean by 'broken'? And is this something that has to do with laravel-snappy of a problem with wkhtmltopdf in general?

**Comment by abengardino** [comment]
Broken meaning Chrome or Adobe Reader won't open it. I posted this here
because like I said, if I save the HTML to a file and invoke wkhtmltopdf
from the CLI, I get it right.

2015-06-04 11:27 GMT-03:00 Jeroen van Oort <notifications@github.com>:

**Comment by barryvdh** [comment]
Are you using Vagrant? Real server? PHP Dev server?

Dev server can cause blocking issues.

**Comment by abengardino** [comment]
Hey Barry, thanks for taking a look. I'm using XAMPP 3.2.1. I tried opening
the corrupt PDF file with a text editor and the last object created seems
to be the image:

<<
/Type /XObject
/Subtype /Image
/Width 2422
/Height 447
/BitsPerComponent 8
/ColorSpace /DeviceRGB
/Length 7 0 R
/Filter /DCTDecode
>>
stream

and all the "binary" stuff after that stream label...

2015-06-04 11:35 GMT-03:00 Barry vd. Heuvel <notifications@github.com>:
