### ISSUE TITLE
Laravel 5.1 compatibility

### ISSUE THREAD

**Issue by JeroenVanOort** [barryvdh/laravel-snappy#54]
How can we assure swift compatibility with 5.1 when it comes out? I haven't seen breaking changes for packages, so it might be as simple as changing the version number in composer.json.

I'm happy to help out where if necessary, but I simply don't know what to do.

**Comment by barryvdh** [comment]
Can you try it with L5.1? Allowed it in composer.json in https://github.com/barryvdh/laravel-snappy/commit/34c4419a34dac528aed022295bac5f8fe6b12e13

**Comment by JeroenVanOort** [comment]
Seems to be just fine. In my current setup, I can only test the PDF functions and not the Image functions though.

**Comment by barryvdh** [comment]
I don't think anything big changed :)
