### ISSUE TITLE
class 'Barryvdh\Snappy\IlluminateSnappyImage' does not have a method 'make'

### ISSUE THREAD

**Issue by VerzatileTom** [barryvdh/laravel-snappy#61]
I followed the installation process and I did a test...
$pdf = App::make('snappy.pdf.wrapper');
$pdf->loadHTML('Test');
return $pdf->stream();

And error shows that says:
call_user_func_array() expects parameter 1 to be a valid callback, class 'Barryvdh\Snappy\IlluminateSnappyImage' does not have a method 'make'

How can i resolve this?

**Comment by kikz4life** [comment]
im experiencing this too.

**Comment by MeisamMulla** [comment]
I have this happening as well

**Comment by asinia01** [comment]
Yup.  I am as well

**Comment by msdme** [comment]
This is happening to mee too..
