### ISSUE TITLE
Custom PDF size

### ISSUE THREAD

**Issue by eriktobben** [barryvdh/laravel-snappy#62]
Hi!

How can I set the size of the PDF? I need it to be 25x54mm.

**Comment by eriktobben** [comment]
Does anyone know? I see from the documentation that I can use "page-height", but how do I set it with the facade?

**Comment by azamudio1971** [comment]
i use this
$pdf = SnappyPdf::loadView('salidas.pdf', compact('salida', 'title'))
    ->setOption('page-width', '215.9')
    ->setOption('page-height', '139.7');

**Comment by Dhavalc2012** [comment]
> 
> 
> What unit of measurement is this, btw? I want to make it A4 Size or Legal Size

You can use setPaper('a4') function for setting it to A4.

**Comment by mohamadyuzrie** [comment]
I know this is a long-ago post, but just to answer the question after a trial and error, the `setOption()` unit of measurement is `mm`
