### ISSUE TITLE
Image loading from external sources

### ISSUE THREAD

**Issue by tao** [barryvdh/laravel-snappy#64]
Hello,

I am using the library to create PDF reports, however the website runs on a load balanced server. I have three load balanced servers A, B, and C and I generate thumbnails of 500x500+ pixels on each server as required. The original images are stored on S3.

``` php
<img
    alt="{{ $media->name }}"
    src="{{ env('APP_URL') }}/filesystem/cache/media/{{ $media->uuid }}-500x500.{{ $media->extension }}"
    data-src="{{ env('APP_URL') }}/api/v1/thumbnail/{{ $media->uuid }}"
    data-src-retina="{{ env('APP_URL') }}/api/v1/media/thumbnail/{{ $media->uuid }}?view=retina"
/>

// Lazy Loading image script
<script type="text/javascript" src="/assets/unveil/jquery.unveil.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $("img").unveil();
    });
</script>
```

However if the html page is loaded on server A, the thumbnails are saved to server A, and the pdf may be generated on server B, and then no images will be loaded on the pdf as they don't exist on the server B filesystem.

All I do is: on pdf generation, I disable the javascript and the image is loaded from the "src" attribute instead of "data-src", which works really well when I only have one server enabled and I have no problem generating PDF files. However as soon as I switch on more than one server it gets confused and starts serving images that don't exist yet from server B and server C.

When thumbnails are generated they are also saved on Amazon S3, so instead of using the local path, I would like to update my code to fetch all the thumbnails from S3. However as soon as I updated my code to use:

``` php
src="https://s3-eu-west-1.amazonaws.com/{$bucket}/storage/{$path}"
```

I have a problem where the images no longer load, they must either time out or there is some other issue loading them. This S3 url works fine in the HTML view, it also works on the PDF view because only about half of the S3 images load, then the PDF is generated with some missing images and a blue background where the image should be.

The servers are all on Amazon AWS in the same network so the S3 media loads really fast. I could scale up the server to have a faster processor maybe? but then it would cost too must just to generate some pdf files...

Any tips or ideas?

Maybe there is a way to generate and save the pdf document to file and let it take as long as it needs to load the images, then I can serve the pre-generated pdf file? 

Is there any way I can let the code run a bit longer so all the images are loaded first before the pdf is returned?

Cheers,

![screen shot 2015-08-24 at 12 26 55 am](https://cloud.githubusercontent.com/assets/1446331/9430683/d7da12f0-49f6-11e5-9907-68167648efc1.png)

**Comment by coco-itu** [comment]
I think I have the same problem. Loading the images from Instagram. The PDF returned is missing a significant amount of images.

**Comment by iraeeu** [comment]
I have it working fine now, I changed my load balancer so I could use sticky sessions, so then if a user loads a PDF file it should fetch the images from the same server.

I didn't find a solution for loading external images from AWS S3, so I'm not too sure how you could deal with the same problem with Instagram. I can suggest you try download all the images to your server first and then load the PDF images from the local copies.
