### ISSUE TITLE
Multiple PDF

### ISSUE THREAD

**Issue by chikitovivas** [barryvdh/laravel-snappy#66]
How can i create a single stream(), but with multiple PDF?

**Comment by mthomas88** [comment]
Hey mate,

I know this is late, but I'll answer this ticket just incase you're still stuck or if anyone else has this problem.

The package is a wrapper for KNP Snappy which is an interface for WKHTMLTOPDF and you can't really merge PDF's with that software to my knowledge.

I had a situation where a user was generating a PDF from some HTML on the page but also uploaded a bunch of PDF's to add to it... which got me stuck for awhile but this is what I did.

1. Create the PDF as you need it from your HTML.
3. Save to Filesystem and store the path in your DB or pass it to the next step.
2. Dispatch job and use this package: "clegginabox/pdf-merger": "dev-master",
3. Run a for loop for every PDF you want, add it whatever order.
4. Save to the filesystem.
5. Boom! You've got a merged PDF your original and any extra uploaded documents you needed.
