### ISSUE TITLE
Laravel 5.0.x - The package doesn't work when updating Composer file

### ISSUE THREAD

**Issue by jferrettiboke** [barryvdh/laravel-snappy#67]
Today I updated my composer file with `composer update` command and I saw when I pushed to BitBucket how some files were deleted. Before to upgrade my composer all were good. I am using Laravel 5.0.x.

```
+0 -106 vendor/knplabs/knp-snappy/README.markdown
+0 -104 vendor/knplabs/knp-snappy/src/Knp/Snappy/Process.php
+0 -21 vendor/knplabs/knp-snappy/src/autoload.php
+0 -31 vendor/knplabs/knp-snappy/test/Knp/Snappy/ProcessTest.php
+0 -41 vendor/phpspec/phpspec/features/matchers/developer_users_array_key_value_matcher.feature
```

The error is this:

```
RuntimeException in AbstractGenerator.php line 364:
Unable to write in directory: C:\Windows\TEMP
```

I saw in `vendor/barryvdh/laravel-snappy/composer.json` that another dependency is set with `*`. I think the problem could be from that `"knplabs/knp-snappy": "*"`. Maybe, this dependency was updated to new version and this package (`laravel-snappy`) has to be updated too according `knp-sanappy` changes.

Any solution? Thank you.

**Comment by ninadpchaudhari** [comment]
Had errors regarding "Unable to write in directory: C:\Windows\TEMP"
Got solved by adding full control to 2 users : 
"IUSR"
"IIS_IUSRS"

Package works with Laravel 5.1 , at version 0.2.x 
and have kept  ```` "knplabs/knp-snappy": "*" ```` Which currently loads 0.4.2
