### ISSUE TITLE
cannot connect to X server

### ISSUE THREAD

**Issue by garf** [barryvdh/laravel-snappy#70]
Receiving this error, when generating PDF.

```
RuntimeException in AbstractGenerator.php line 336: The exit status code '1' says something went wrong:
stderr: "wkhtmltopdf: cannot connect to X server
"
stdout: ""
command: /usr/local/bin/wkhtmltopdf --lowquality '/tmp/knp_snappy56001481ef8a95.44050466.html' '/tmp/knp_snappy56001481ef9171.94980132.pdf'.
```

**Comment by shaneparsons** [comment]
Any updates on this?

**Comment by rawzone** [comment]
Same for me. Running it in homestead... Working strangely without X on a staging server.

**Comment by pabloacevedo** [comment]
Someone has a solution? that happens to me too.

**Comment by rawzone** [comment]
@pabloacevedo I used this as a workaround https://github.com/JazzCore/python-pdfkit/wiki/Using-wkhtmltopdf-without-X-server

Did however make my own shell script wrapper and changed resolution etc.

**Comment by pabloacevedo** [comment]
Thank you very much, but this solution worked for my.

https://www.ab-heute-programmieren.de/pdfs-laravel-mit-wkhtmltopdf-erstellen/
