### ISSUE TITLE
How to enable JavaScript to render a PDF view?

### ISSUE THREAD

**Issue by jferrettiboke** [barryvdh/laravel-snappy#73]
I would like to enable JavaScript to render a PDF view. What is the right way?

Thanks!

**Comment by arifmahmudrana** [comment]
I do have the same issue. I am trying to render a chart using JavaScript using canvas element. @jferrettiboke did you find any solution.

**Comment by jferrettiboke** [comment]
Yes, I did. Try the next piece of code.

```
$pdf->setOption('enable-javascript', true);
$pdf->setOption('javascript-delay', 13500);
$pdf->setOption('enable-smart-shrinking', true);
$pdf->setOption('no-stop-slow-scripts', true);
```

Where `$pdf` is a instance to PDF. Something like `$pdf = PDF::loadView('invoice'), $data);`.

I hope you can solve your doubts.

**Comment by arifmahmudrana** [comment]
@jferrettiboke thanks I already solved. I add **`javascript-delay`** in my option & I have really a small javascript chart(**`chartjs`**) to run so small delay

    return app('snappy.pdf.wrapper')->setOption('javascript-delay', 5000)
               ->loadHTML(view('frontend.food-nutrition.food.pdf', get_defined_vars())
               ->render())->download($id . '.pdf');

**Comment by dorsho88** [comment]
@arifmahmudrana This was really helpful, thank you for sharing your solution.

**Comment by oberoivarun** [comment]
I was having a major problem with svgs and images. I'm going to reference this in all the places where i found people facing the same issue. Setting the options mentioned above helped me! @jferrettiboke  Thanks a ton!

**Comment by HarshaV198** [comment]
i given height through javascript in pixel its taking more height than i given

**Comment by admicaa** [comment]
You can see this working example right here https://github.com/admicaa/larabook

**Comment by XeguisX** [comment]
Tengo este tipo de Convención a Pdf.
`$view = view('Informes.informeAlumno.informealumno',
        compact('grado','seccion','mes'));
$pdf = \App::make('dompdf.wrapper');
        $pdf->loadHTML
![Sin título](https://user-images.githubusercontent.com/48564316/69541354-e9a91d80-0f56-11ea-994c-ceefe3fa3378.jpg)
($view)->setPaper('a4','landscape');
        return $pdf->stream('Informe Individual.pdf');`

y dentro de mi vista tengo algunas peticiones en ajax

`<script>

$(document).ready(function() {

    var tFacturado, tCancelado , tSaldo;

        $.get("informeIndividualAgrupa/"+$("#grado").val()+"/"+$("#seccion").val()+"",function(response,document){
            $("#div1").empty()
            for (i = 0; i < response.length; i++) {
                $.get("informeIndividual/"+response[i].idMatricula+"/"+$("#mes").val()+"",function(response,document){
                    tFacturado =  0;
                    tCancelado = 0;
                    tSaldo = 0;

                    $("#div1").append(
                        "<br>"+
                        "<header>"+
                        "<center>"+
                        "<img src='images/encabezado.PNG'width='98%'>"+
                        "</center>"+
                        "</header>"+
                        "<br>"+
                        "<table id='table"+response[0].idMatri+"' style='width:100%'>"+
                            "<tbody>"+
                                "<tr>"+
                                    "<td colspan='4'><strong>ALUMNO: "+response[0].nombreCompleto+"</strong></td>"+
                                "</tr>"+
                                "<tr>"+
                                    "<td colspan='2'><strong>CONSULTA INVIDUAL</strong></td>"+
                                    "<td colspan='2'><strong>AÑO LECTIVO 2020</strong></td>"+
                                "</tr>"+
                                "<tr>"+
                                    "<td colspan='2'><strong>GRADO "+response[0].grado+"</strong></td>"+
                                    "<td colspan='2'><strong>GRUPO "+response[0].seccion+"</strong></td>"+
                                "</tr>" +
                                "<tr>"+
                                    "<th>Mes</th>"+
                                    "<th>Facturado</th>"+
                                    "<th>Cancelado</th>"+
                                    "<th>Saldo</th>"+
                                "</tr>"
                                );

                                for (j = 0; j < response.length; j++) {

                                    $('#table'+response[0].idMatri).append(
                                        "<tr>"+
                                        "<th>"+response[j].mes+"</th>"+
                                        "<th>"+response[j].facturado+"</th>"+
                                        "<th>"+response[j].cancelado+"</th>"+
                                        "<th>"+response[j].saldo+"</th>"+
                                        "</tr>"
                                    );

                                    tFacturado =  tFacturado + response[j].facturado;
                                    tCancelado = tCancelado + response[j].cancelado;
                                    tSaldo = tSaldo + response[j].saldo;
                                }

                                $('#table'+response[0].idMatri).append(
                                    "<tr>"+
                                    "<th>Total</th>"+
                                    "<th>"+tFacturado+"</th>"+
                                    "<th>"+tCancelado+"</th>"+
                                    "<th>"+tSaldo+"</th>"+
                                    "</tr>"

                                );

                                $('#table'+response[0].idMatri).append(
                                    "</tbody>"+
                                    "</table>"
                                );

                });
            }
        });
})

</script>`

y esto no funciona normalmente , me manda el pdf en blanco al no cargar los scripts

**Comment by codinaguillermo** [comment]
XeguisX ... ¿Pudiste resolver ese problema? A mi me sucede lo mismo, No carga el código JS, ni los ajax y el navegador al pasar 60s me da error. En una vista sin JS ni Ajax anda de 10. Pero en otra vista debo hacer un dibujo con JS y no anda el DomPDF. mi mail es codinaguillermo@gmail.com. Saludos

**Comment by QuinterosDani** [comment]
@XeguisX  ¿Pudiste resolver ese problema?, tengo el mismo problema y ya voy un buen rato tratando de resolverlo sin éxito agradecería cualquier aporte que pueda resolver mi problema, gracias de antemano

**Comment by nikonachev** [comment]
I want to use JavaScript in my Blade template to add or change dynamically the HTML but I don't know how to enable it in dompdf.
I have a simple Blade:
`<!DOCTYPE html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <style>
    .page-break {
        page-break-after: always;
    }
    *{ font-family: DejaVu Sans !important;}
    </style>
    <title>Hi</title>
</head>
<body>
  <h1 id="demo">Test PDF</h1>
  <script type="text/javascript">
    function insertHtml() {
      document.getElementById("demo").innerHTML = "I have changed!";
    }
    insertHtml()
</script>
</body>`
I use Laravel Filament actions to generate the PDF.
`Tables\Actions\Action::make('pdf') 
                    ->label('PDF')
                    ->color('success')
                    ->icon('heroicon-s-download')
                    ->action(function (Model $record) {
                        return response()->streamDownload(function () use ($record) {
                            echo Pdf::setOption('javascript-delay', 13500)->loadHTML(
					Blade::render('pdf', ['record' => $record]), 'UTF-8'
                            )->stream();
                        }, 'Test-' . $record->number . '.pdf');
                    }), `
When I click on the action button the PDF is generated but the JavaScript is not take into account and the outputted text in the PDF is still "Test PDF" instead "Test PDF".
Can you help me to solve this problem?

Thank you in advance.

**Comment by nikonachev** [comment]
I want to use JavaScript in my Blade template to add or change dynamically the HTML but I don't know how to enable it in dompdf.
I have a simple Blade:
```blade
<!DOCTYPE html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <style>
    .page-break {
        page-break-after: always;
    }
    *{ font-family: DejaVu Sans !important;}
    </style>
    <title>Hi</title>
</head>
<body>
  <h1 id="demo">Test PDF</h1>
  <script type="text/javascript">
    function insertHtml() {
      document.getElementById("demo").innerHTML = "I have changed!";
    }
    insertHtml()
</script>
</body>
``` 
I use Laravel Filament actions to generate the PDF.
```php
Tables\Actions\Action::make('pdf') 
                    ->label('PDF')
                    ->color('success')
                    ->icon('heroicon-s-download')
                    ->action(function (Model $record) {
                        return response()->streamDownload(function () use ($record) {
                            echo Pdf::loadHTML(
					Blade::render('pdf', ['record' => $record]), 'UTF-8'
                            )->stream();
                        }, 'Test-' . $record->number . '.pdf');
                    }), 
``` 
When I click on the action button the PDF is generated but the JavaScript is not take into account and the outputted text in the PDF is still "Test PDF" instead "Test PDF".
Can you help me to solve this problem?

Thank you in advance.

**Comment by Gor91** [comment]
Hi @arifmahmudrana 
I want to render html with javascript before converting it to pdf. Is it work from you side?
