### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by erllm** [barryvdh/laravel-snappy#83]
I have tried searching everywhere, followed the readme.md to a T and I am still unable to get laravel-snappy installed into Laravel 4.x and working. 

wkhtmltopdf is installed on my server (Ubuntu 14.04) and working just fine from the command line.

I require the package in composer as so:
```
"require": {
		"laravel/framework": "4.0.*",
		"barryvdh/laravel-snappy": "0.1.x@dev"
	},
```

then ran ***composer update*** from the command line, and get the following output:
```
> php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies (including require-dev)
Killed
```

I then added the Service Provider in app.php, but when I try to create the config file per the readme.md, I get the following: 

***$php artisan config:publish barryvdh/laravel-snappy***

```
  [InvalidArgumentException]
  Configuration not found.

config:publish [--path[="..."]] package
```

Also, I get an errror when trying to test the code, that says the following:

***PHP Fatal error: Class 'Barryvdh\DomPDF\ServiceProvider' not found***

**Comment by juniorrosul** [comment]
Try to execute ```composer update``` with verbose level (```composer update -vvv```) your composer update It is not ending running

**Comment by erllm** [comment]
I executed it with verbose level and it finishes fine. But when I use the test code:

`$pdf = App::make('snappy.pdf.wrapper');`
`$pdf->loadHTML('<h1>Test</h1>');`
`return $pdf->stream();`

I still get the following: **PHP Fatal error: Class 'Barryvdh\DomPDF\ServiceProvider' not found**

Sorry, this is my first project working with composer. I'm following the directions exactly but it doesn't seem to work. I did find that I had to do sudo composer update -vvv rather than non-sudo to get it to work. That may have been part of the problem before, but still didn't help this time. 

I also still cannot publish the config file. Same error as before. 

Thanks for your help - hopefully you have more advice to lend.

**Comment by erllm** [comment]
Sorry, I did fix this. The issue was that I did not have enough memory to run composer update. If you have the same problem and you are stumped, check out your memory_limit and/or available RAM. I had to create a 1G swapfile which fixed this immediately.
