### ISSUE TITLE
error composer

### ISSUE THREAD

**Issue by carlituxman** [barryvdh/laravel-snappy#84]
I have this error with:
 composer require barryvdh/laravel-snappy:
 The requested package barryvdh/laravel-snappy could not be found in any version, there may be a typo in the package name.

**Comment by litan1106** [comment]
+1

**Comment by barryvdh** [comment]
Hmm weird, tags were missing from Packagist. Updated them manually; https://packagist.org/packages/barryvdh/laravel-snappy

Should be good in couple of minutes.

**Comment by juniorrosul** [comment]
this resolve in my case:

```
...
"barryvdh/laravel-snappy": "0.1.x-dev",
...
```
