### ISSUE TITLE
stream() and download() are giving me blank pages

### ISSUE THREAD

**Issue by EricWVGG** [barryvdh/laravel-snappy#85]
The following tests are giving me blank PDF files…
```
return PDF::loadHTML('<p>Where is my money?</p>')->stream();
return PDF::loadHTML('<p>Where is my money?</p>')->download('test.pdf');
return PDF::loadView('template', ['message'=>'money'])->stream();
```

This is giving me a three-page blank PDF file…
```
return PDF::loadFile('http://www.github.com')->download('github.pdf');
```
… and this is actually giving me a *good* file, albeit buried away in the /tmp folder…
```
PDF::generateFromHtml('<p>Where is my money?</p>', '/tmp/test.pdf');
```
… so I know wkhtmltopdf is working on some level. Am I overlooking something dumb?

**Comment by Trikke** [comment]
+1

**Comment by KuenzelIT** [comment]
Maybe you are missing permissions in the php temp directory, which is used if you use download or stream. In this case /tmp/ has sufficient permissions.

**Comment by Houbsi** [comment]
did you try inline and save?

**Comment by ssamuel645** [comment]
@EricWVGG did you solved it? Having the same issue here, can't  find a solution :/

**Comment by EricWVGG** [comment]
I can't even recall what project this was for.

**Comment by ssamuel645** [comment]
Well, thanks anyway.
