### ISSUE TITLE
problem when update to laravel 5.2

### ISSUE THREAD

**Issue by bendo01** [barryvdh/laravel-snappy#87]
When install / update to laravel 5.2 i've got this message form composer, is there any solution for this ?
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - barryvdh/laravel-snappy v0.2.0 requires illuminate/filesystem 5.0.x -> satisfiable by illuminate/filesystem[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4].
    - barryvdh/laravel-snappy v0.2.1 requires illuminate/filesystem 5.0.x|5.1.x -> satisfiable by illuminate/filesystem[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.6, v5.1.8].
    - don't install illuminate/filesystem v5.0.0|don't install laravel/framework v5.2.0
    - don't install illuminate/filesystem v5.0.22|don't install laravel/framework v5.2.0
    - don't install illuminate/filesystem v5.0.25|don't install laravel/framework v5.2.0
    - don't install illuminate/filesystem v5.0.26|don't install laravel/framework v5.2.0
    - don't install illuminate/filesystem v5.0.28|don't install laravel/framework v5.2.0
    - don't install illuminate/filesystem v5.0.33|don't install laravel/framework v5.2.0
    - don't install illuminate/filesystem v5.0.4|don't install laravel/framework v5.2.0
    - don't install illuminate/filesystem v5.1.1|don't install laravel/framework v5.2.0
    - don't install illuminate/filesystem v5.1.13|don't install laravel/framework v5.2.0
    - don't install illuminate/filesystem v5.1.16|don't install laravel/framework v5.2.0
    - don't install illuminate/filesystem v5.1.2|don't install laravel/framework v5.2.0
    - don't install illuminate/filesystem v5.1.20|don't install laravel/framework v5.2.0
    - don't install illuminate/filesystem v5.1.22|don't install laravel/framework v5.2.0
    - don't install illuminate/filesystem v5.1.25|don't install laravel/framework v5.2.0
    - don't install illuminate/filesystem v5.1.6|don't install laravel/framework v5.2.0
    - don't install illuminate/filesystem v5.1.8|don't install laravel/framework v5.2.0
    - Installation request for laravel/framework 5.2.* -> satisfiable by laravel/framework[v5.2.0].
    - Installation request for barryvdh/laravel-snappy 0.2.x -> satisfiable by barryvdh/laravel-snappy[v0.2.0, v0.2.1].

**Comment by barryvdh** [comment]
Should be fixed in @dev

**Comment by bendo01** [comment]
@barryvdh thank you :)
