### ISSUE TITLE
Urdu Font Issue on Centos

### ISSUE THREAD

**Issue by umairali** [barryvdh/laravel-snappy#88]
I m trying to create pdf in urdu but urdu fonts not working i m using centos. Please suggest any thing

![capture](https://cloud.githubusercontent.com/assets/5318005/12017975/ee60b5e2-ad7e-11e5-8fc1-203a8340d082.PNG)

**Comment by KuenzelIT** [comment]
If I understand the whole thing correctly, then it's a problem with wkhtmltopdf, not with snappy. So maybe you should ask the wkhtmltopdf developers.

**Comment by ClickerVinod** [comment]
I ALSO HAVE SAME ISSUE PLZ HELP HOW TO FIX THIS
![image](https://user-images.githubusercontent.com/17634341/77181696-b7b55b80-6af1-11ea-959a-82be984b3577.png)

**Comment by MudassarCIS** [comment]
I have used this urdu font in snappy pdf "Jameel-Noori-Nastaleeq.ttf" its working fine for urdu , 

If any one knows any other font for make snappy pdf , then please tell me , i want to create ulternate option for make pdf but fonts i have tried are have some issues in making pdf , only  1 font working correctly so far , Jameel-Noori-Nastaleeq.ttf
