### ISSUE TITLE
Call to undefined method Knp\Snappy\Pdf::loadView()

### ISSUE THREAD

**Issue by leonardosapiras** [barryvdh/laravel-snappy#89]
When I tried to get an pdf from the code below I got "Call to undefined method Knp\Snappy\Pdf::loadView()"

$data = [];
$pdf = PDF::loadView('test_view', $data);
return $pdf->download('test.pdf');

In my config/app.php I set the provider index 'Barryvdh\Snappy\ServiceProvider', and I also set the alias  'PDF'       => 'Barryvdh\Snappy\Facades\SnappyPdf'

I am working with Laravel 5.1

**Comment by chrislandeza** [comment]
Did you import the class? 

    use Barryvdh\Snappy\Facades\SnappyPdf as PDF;

**Comment by chopf** [comment]
Looks like you're IDE probably automatically imported `Knp\Snappy\Pdf` when you typed `PDF::`.
To use the facade that you've properly set up, just put `$pdf = \PDF::loadView('test_view',$data);`
Facades will automatically resolve from `\<facadeName>::` to the class listed in `config/app.php` automatically, removing the need for the line above that Chris suggested.
