### ISSUE TITLE
exceeded the timeout of 60 seconds ?

### ISSUE THREAD

**Issue by joruzani** [barryvdh/laravel-snappy#9]
Hi, I'm having a hard time making this work and don't know what to check.

Symfony \ Component \ Process \ Exception \ ProcessTimedOutException   The process "/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf --lowquality '/tmp/knp_snappy539a1b5171a923.27143750.html' '/tmp/knp_snappy539a1b5171b010.24930374.pdf'" exceeded the timeout of 60 seconds.

Thats been thrown.

Any ideas? 
I already check that the bin is working

Thanks for any help =)

**Comment by webdevilopers** [comment]
Still checking the port problem. Any help would be appreciated!
Feel free to follow my steps on my gist:
https://gist.github.com/webdevilopers/e0d34a1c04ef2050a450

**Comment by webdevilopers** [comment]
I tried to get the command:
```php
            $html = $this->renderView('AppBundle:Bundle:list.html.twig', $viewParameters);

            $snappy = $this->get('knp_snappy.pdf');

            echo $snappy->getInternalGenerator()->getCommand($html, 'test.pdf', array(
                    'orientation' => 'Landscape',
                    'images' => true,
                    'enable-javascript' => true
                ));
```

The result is a simple
```
wkhtmltopdf --lowquality --orientation 'Landscape' --images --enable-javascript ' 
```

I think the command is incomplete since it uses a symfony2 twig rendered template as `$input`, @colejarczyk?

**Comment by webdevilopers** [comment]
I found the root of my problems caused by the PHP built-in server because it is single-threaded, @colejarczyk . 

Fur further details:
https://gist.github.com/webdevilopers/e0d34a1c04ef2050a450#comment-1368355

Thanks anyway!

**Comment by colejarczyk** [comment]
I would never thought that you'll trying to test wkhtmltopdf in PHP built-in server :)
To get full command, edit Abstract Generator class and echo command from method execute.
Use Vagrant as environment for testing.

**Comment by webdevilopers** [comment]
Believe me @colejarczyk , it was not my choice! ;) And yes, Vagrant is next! :)

**Comment by Wayne-Wen** [comment]
I meet the same timeout problem in our production server. It is weird that most of time, everything works fine and we can generate the PDF. I am using {{ HTML::style('my.css') }} or {{ HTML::script('my.js') }} for all css and js file. Does anyone know how to fix this problem?

**Comment by kenng** [comment]
I have the same problem and was only realized it was due to the unstable version of wkhtmltopdf (0.11rc1). Wkhtmltopdf was hang and not returned and causing the timeout. Switching to 0.12.1 fixed the problem.

**Comment by akshaykhale1992** [comment]
I have the same problem but in my case temp html files aren't being created and It works fine for few views but for one view its giving me problem
The view causing problem is reading data from a rest api and contains few images.
when I print the view content it's proper but when I try to create PDF its giving me timeout error.
Please help me.
Thanks in advance!

**Comment by fatihict** [comment]
I also run the PHP built in server and get a timeout-error if i try to access external css/js files. If i inline everything then it works like a charm.

**Comment by webdevilopers** [comment]
Did you check my comment @fatihict ?
https://github.com/barryvdh/laravel-snappy/issues/9#issuecomment-69172040

**Comment by fatihict** [comment]
@webdevilopers Yes, i saw you comment. Thanks for your help.

**Comment by mininoz** [comment]
humiv

**Comment by rvanlaak** [comment]
We also have the timeout, but it is expected because the html result is huge so it does really take Snappy over 60 seconds to generate the PDF. All issues I've found are related to `wkhtmltopdf` is waiting for content, but none of them actually provide a solution to increase the timeout for the `Process` component. Is there another option next to calling `set_time_limit()` before the PDF will be generated?

**Comment by eveyrat** [comment]
Thanks @rvanlaak.

**Comment by bgarrison25** [comment]
@rvanlaak if i set this in the AppServiceProvider will all calls to Snappy pdf now have this timeout?

**Comment by rvanlaak** [comment]
@bgarrison25 you've got a link to the class you mean? We don't use this laravel wrapper bridge but use the [KnpSnappyBundle](https://github.com/KnpLabs/KnpSnappyBundle), but I can't find the file in that bundle or even in this bundle or [`snappy`](https://github.com/KnpLabs/snappy) itself.

**Comment by Lednerb** [comment]
@barryvdh 
Maybe my issue #129 has the same solution as @rvanlaak https://github.com/barryvdh/laravel-snappy/issues/9#issuecomment-193173498 mentioned.

**Comment by CharlyPoppins** [comment]
On our dedicated the timeout issue was solved by disabling ipv6.

**Comment by syc-pad** [comment]
I had similar issue.
I solved it by calling `{{public_path('css/mycss.css')}}` instead of `URL::to()` or `asset()`

**Comment by michaelvickersuk** [comment]
Specifying a timeout value in `config/snappy.php` stopped this error occurring in my project.

**Comment by Lednerb** [comment]
> > I had similar issue.
> > I solved it by calling `{{public_path('css/mycss.css')}}` instead of `URL::to()` or `asset()`
> 
> It worked for me ! Anyone can explain this?

The wkhtmltopdf does not use the actual browser domain to resolve the files.
The wkhtmltopdf binary is on your machine and needs the real file path to the associated files like images and stylesheets.

With `public_path()` you get the full path string like `/var/www/html/public/css/mycss.css` instead of `http://example.org/css/mycss.css`.

I had the same issue before.

**Comment by eldinphp** [comment]
If someone else has this problem, well I found this kind-of solution

Delete every redirects you have in hosts file (in linux its etc/hosts) except for example

mysite.test 127.0.0.1

also edit httpd-vhosts.conf file and delete other vhosts you have.. then run command from terminal
./ngrok http mysite.test:80

It should work.

**Comment by elvincali** [comment]
> I had similar issue.
> I solved it by calling `{{public_path('css/mycss.css')}}` instead of `URL::to()` or `asset()`

Thanks!!!!, This has worked for me.

**Comment by sushansht** [comment]
I have this issue too. Mine is because of image in pdf which was taken form asset. I remove the image it works.

**Comment by jagadeshanh** [comment]
I had the same issue, it was because of internet (slow or not working), I then switched to different network and works fine. Just in case anyone have the same problem :-)
