### ISSUE TITLE
Failing to load resources from http://localhost:8888

### ISSUE THREAD

**Issue by coco-itu** [barryvdh/laravel-snappy#93]
Ok I have spent about 2 hours trying to debug this. 

My laravel app is served on port 8888

`php -S localhost:88888 -t public/`

Here's the code that outputs a rendered view

`$imageObjects = json_decode(Order::findOrFail($order_id)->collage) ;

```
   $pdf = PDF::loadView('pdf.frame_2_2', compact('imageObjects'));

   return $pdf->stream('invoice.pdf');`
```

Snappy crashes when trying to resolve a development url on port 8888 (http://localhost:8888/uploads/images/image.jpg). 

However it works if I serve my app on port 8080 

`php -S localhost:8080 -t public`

Hope this will be fixed in the future. Also hope this issue will help others. 

Thanks for the building this wrapper!

**Comment by KuenzelIT** [comment]
How can the webserver port be related to snappy failing? Did you find a solution?
