### ISSUE TITLE
Laravel 5, Windows 7, PDF

### ISSUE THREAD

**Issue by khandurdyiev** [barryvdh/laravel-snappy#97]
Can i configure laravel-snappy which will be work on windows 7? I have local project on this os.
`$pdf = \PDF::loadView('invoice');
return $pdf->setOption('viewport-size', 1366)->stream('invoice-' . $id . '.pdf');`

config snappy.php
`<?php

return array(

```
'pdf' => array(
    'enabled' => true,
    'binary' => base_path('vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64'),
    'timeout' => false,
    'options' => array(),
),
'image' => array(
    'enabled' => true,
    'binary' => '/usr/local/bin/wkhtmltoimage',
    'timeout' => false,
    'options' => array(),
),
```

);
`
It work on linux, but it don't work on windows 7, if i run this code

**Comment by KuenzelIT** [comment]
Does it work from command line?
Does the base_path to wkhtmltopdf have any whitespaces?
Are the directory permissions set correctly for the PDFs to be generated?

These are some of the problems I had.

**Comment by islamw** [comment]
I solve my problem earlier, thanks.

2016-03-04 14:59 GMT+02:00 kuenzelIT <notifications@github.com>:

**Comment by KuenzelIT** [comment]
Maybe you want to share your solution? :)

**Comment by korimatsu** [comment]
can you share with me your solution i have the same problem :'(  karimstam@gmail.com

**Comment by korimatsu** [comment]
ok solved see here https://github.com/barryvdh/laravel-snappy/issues/60
