### ISSUE TITLE
margin on background

### ISSUE THREAD

**Issue by carlituxman** [barryvdh/laravel-snappy#98]
Hi, I have a background image without margins, but in the pdf has a blank margin. 
How can I solve it?
I need the background to all the page.

**Comment by carlituxman** [comment]
I solved with 
'margin-top'=> '0mm', 'margin-right'=> '0mm', 'margin-bottom'=> '0mm', 'margin-left'=> '0mm',

in options

but now I have a second page in blank, can I force one page?

**Comment by carlituxman** [comment]
solved with: ->setOption('disable-smart-shrinking',true)->setOption('zoom','0.78')

**Comment by mprandot** [comment]
@carlituxman 
to set margin's i would use  `->setOption()` method?
like `setOption('margin-top', 0 ) ...`?
